### ISSUE TITLE
Do not move favorite apps list when notification closes

### ISSUE THREAD

**Issue by ryandude10** [8bitPit/Niagara-Issues#764] opened 2019-02-20 01:48 UTC
It seems weird when the favorites apps list moves up when the homescreen notification closes. Can we leave the favorite app list stationary and make the clock shrink when a homescreen notification appears and enlarge when it disappears?

**Comment by 8bitPit** [comment] 2019-02-20 12:01
Sorry, I don't fully get you. Do you mean heads up notifications? Like this one:
![image](https://user-images.githubusercontent.com/9284845/53090378-885ba600-350f-11e9-96c6-70e9cd359bed.png)

**Comment by ryandude10** [comment] 2019-02-20 13:02
So currently the launcher has the clock at the top, a collapsible spot for
the music player then your favorite apps. When the music player shows up on
the screen it pushes the favorite apps list down. When you close the player
the favorite apps shift up closer to the clock. It seems weird to me that
the favorite apps should shift to retake that space. I would prefer that
the clock resizes to take up that space and the favorite apps are
stationary and do not move.

**Comment by 8bitPit** [comment] 2019-02-20 14:27
Ah okay, understood. That issue was also requested by someone in the Telegram group, here is the link:

**Comment by 8bitPit** [comment] 2019-02-20 14:27
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/243

**Closed** 2019-02-20 14:28 UTC
Labels: duplicate
