### ISSUE TITLE
Custom notification summary schedule

### ISSUE THREAD

**Issue by dsouzadrian** [8bitPit/Niagara-Issues#1737] opened 2021-10-25 19:24 UTC
Is your feature request related to a problem?
Currently I do not know what the schedule for the notification summary is. I believe its once in the morning and then another at night. That's a too few for me and I find myself opening the notification drawer to check if I missed out on something.

Describe the solution you'd like
I'd like to be able to define a custom schedule for the notification summary so users can select at what intervals they'd like to see their notification summary.

**Comment by Blake-LeBlanc** [comment] 2021-11-06 17:31
Same! 

For example, I'd like to receive update notification summaries at 7 AM, Noon, and 3:30 PM. Outside of those time windows, I'm pretty much in focus mode and only want certain contacts to breakthrough with phone calls, etc. Everyone and everything else can wait until I'm at one of the above "pause points" in my day.

**Comment by Maxr1998** [comment] 2022-01-02 18:07
Duplicate of #1651, please follow the progress/discussion over there, thanks!

**Closed by Maxr1998** 2022-01-02 18:07 UTC
