### ISSUE TITLE
"Custom-multi-theme support"

### ISSUE THREAD

**Issue by huberSamuel** [8bitPit/Niagara-Issues#990] opened 2019-09-09 14:36 UTC
At the moment i can't decide between two styles for my niagara launcher, mostly i use a more colourful approach, with the best app icons from several icon packs mixed, at night tho, i would prefer a black background, and a simple icon pack, which only has  white outlined icons.

Therefor it would be amazing, to save "themes", meaning the background & every icon i set for certain apps beeing saved as one "theme", between which i can switch in the settings,
AND
maybe a night-mode for themes, likewise to telegrams, which switches depending on a time trigger to a certain (darker) custom theme at night.

**Comment by 8bitPit** [comment] 2019-11-11 14:29
Hi @huberSamuel, apologies for my late reply.
> Therefor it would be amazing, to save "themes", meaning the background & every icon i set for certain apps beeing saved as one "theme", between which i can switch in the settings

I believe this is related to: #222, right?

> AND maybe a night-mode for themes, likewise to telegrams, which switches depending on a time trigger to a certain (darker) custom theme at night.

That's a neat idea, but I fear this feature would be too specific for a simple launcher like Niagara. My goal is to keep the app as clean as possible and only add the most essential options and just a handful of customization features.

**Comment by 8bitPit** [comment] 2020-01-25 20:34
Duplicate of #222

**Closed by 8bitPit** 2020-01-25 20:34 UTC
Labels: problematic
