### ISSUE TITLE
Customisable Google button?

### ISSUE THREAD

**Issue by NovaStorm64** [8bitPit/Niagara-Issues#1050] opened 2019-11-07 12:04 UTC
Hiya,
Google go is faster on my phone than Google so I'd appreciate it if the Google button could be mapped to Google go somehow, as right now I'm using the widget which continually makes me feel that I should just use Google instead.
Just an idea, you don't have to do anything about it.
Ta
(I set it to feature request but doesn't seem to show up, hmm)

**Comment by 8bitPit** [comment] 2019-11-07 21:38
Hey again. I believe your request is a duplicate of: #655

**Comment by 8bitPit** [comment] 2019-11-08 17:18
Duplicate of #655

**Closed by 8bitPit** 2019-11-08 17:18 UTC
Labels: duplicate
