### ISSUE TITLE
App box 

### ISSUE THREAD

**Issue by prfctvaccum** [8bitPit/Niagara-Issues#828] opened 2019-04-09 23:59 UTC
I find it very difficult to find the rest of my apps. I understand the concept, but it would be incredible that the other apps could also be seen in a "normal" way. In a "horizontal" way, grouped. Not only vertical.

Thank you!

**Comment by 8bitPit** [comment] 2019-04-10 10:17
Sorry, but I really think a traditional design would go against Niagaras fundamental ideas: https://github.com/8bitPit/Niagara-Issues/issues/473

**Comment by 8bitPit** [comment] 2019-04-10 10:18
Duplicate of #473

**Closed by 8bitPit** 2019-04-10 10:18 UTC
Labels: duplicate
