### ISSUE TITLE
Sort app drawer by notifications

### ISSUE THREAD

**Issue by Feckweed405** [8bitPit/Niagara-Issues#861] opened 2019-05-04 14:11 UTC
Make an option to sort apps in the drawer by those with notifications, by moving them to the top of the drawer. My scrolling thumb will thank you!

**Comment by Rod911** [comment] 2019-05-05 08:01
Related: #152 & #9

**Comment by 8bitPit** [comment] 2019-05-05 08:53
Duplicate of #9

**Closed by 8bitPit** 2019-05-05 08:53 UTC
Labels: duplicate
