### ISSUE TITLE
Random visual glitch on icons when returning to the home. 

### ISSUE THREAD

**Issue by brunano21** [8bitPit/Niagara-Issues#2683] opened 2024-05-10 04:20 UTC
### Describe the bug

When returning to home, the icon of the launched app shows a glitch which appears random in occurrence and shape as shows by the attached screen recording. Although I'm using a third-party icon pack (Linebit Light), the same occurs with the native launcher icons set. 

### Steps to reproduce

1. Launch an app. 
2. Return to home. 

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Google Pixel 8 Pro

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/4410485/d8766696-be49-41ee-a3aa-143e17adf299

**Comment by NiagaraSupport** [comment] 2024-05-14 07:48
Hey there, thanks for the report. 
We are aware of the current animation issues but are, unfortunately, also waiting for a fix. In the meantime, you might find this [secret command](https://niagaralauncher.app/app-link/secret-command?cmd=togglecloseappanimation), which turns off the app closing animations helpful. I'll close this as a duplicate of #2527 for now. I appreciate your understanding and patience.

**Closed by NiagaraSupport** 2024-05-14 07:48 UTC
Labels: bug
