### ISSUE TITLE
Support device policy enforced work profiles

### ISSUE THREAD

**Issue by voss** [8bitPit/Niagara-Issues#355] opened 2018-10-06 10:16 UTC
Any chance you'll support work profiles in the future? My phone has a work profile enforced via the Device Policy app, and I'm not able to see the apps living in the work profile when I use Niagara.

**Comment by 8bitPit** [comment] 2018-10-06 13:13
Hey voss, I am working on it right now :)

**Comment by 8bitPit** [comment] 2018-10-06 13:13
Duplicate of #93

**Closed by 8bitPit** 2018-10-06 13:13 UTC
Labels: duplicate

**Comment by voss** [comment] 2018-10-06 15:30
Amazing! Thank you (: 👍🏆
