### ISSUE TITLE
Summary Notification Time

### ISSUE THREAD

**Issue by Zavon** [8bitPit/Niagara-Issues#2022] opened 2022-08-16 23:22 UTC
### Describe the solution you'd like

The ability to adjust the summary Notification times for those who do not have a traditional schedule or for better flexibility. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment] 2022-08-18 14:32
Duplicate of #1651, you can follow the discussion there and mention your reason there.

Alternatively you can use the /summary command on Niagara search to call the notification summary at any point of time.

**Closed** 2022-08-29 20:15 UTC
