### ISSUE TITLE
Error closing attachment

### ISSUE THREAD

**Issue by AlecikFad** [8bitPit/Niagara-Issues#2923] opened 2024-09-19 16:25 UTC
### Describe the bug

When you need to close the application, a small bug occurs. Only recently preo Pixel 8 and encountered this problem.

### Steps to reproduce

1.Open any application 2. Close the application 

### Does the issue also occur with other 3rd-party launchers?

Notpplicable

### Device name

Google pixel 8

### Android version

Android 14

**Comment by NiagaraSupport** [comment] 2024-09-20 04:38
Hey there, thanks for the report.
Could you elaborate on what's wrong exactly?
Buggy animation / unintended behavior / crash are examples.

**Comment by AlecikFad** [comment] 2024-09-20 04:59
![Screenshot_20240920-075758](https://github.com/user-attachments/assets/e6104cd6-ec1d-4d5c-bf77-ab54cb542b2f)

Something like this

**Comment by NiagaraSupport** [comment] 2024-09-25 09:35
Ahh, I'm sorry to see this still hasn't been fixed. It's a well-known issue that affects most third-party launchers on pixel phones, and unfortunately, there's not much we can do from our side. I'll close this as a duplicate of #2527, but I'll check if we can do anything about it. Until then, you can try this [secret command](https://niagaralauncher.app/app-link/secret-command?cmd=togglecloseappanimations), which might help fix the issue, by disabling app closing animations.

**Closed by NiagaraSupport** 2024-09-25 09:35 UTC
Labels: bug

**Comment by AlecikFad** [comment] 2024-09-25 12:37
@NiagaraSupport 
Thanks for your support, but for some reason Secret command returns an error... 
![Screenshot_20240925-153708](https://github.com/user-attachments/assets/0b0d0665-5352-4ad0-9c9c-a932aa4b2318)

**Comment by NiagaraSupport** [comment] 2024-09-25 13:15
Ahh my bad, it's supposed to be [this](https://niagaralauncher.app/app-link/secret-command?cmd=togglecloseappanimations). Hope this helps

**Comment by AlecikFad** [comment] 2024-09-25 13:19
Oh, it worked! Thank you, much better.
