### ISSUE TITLE
Chrome search widget cut 

### ISSUE THREAD

**Issue by kristianruiz** [8bitPit/Niagara-Issues#1195] opened 2020-02-24 23:32 UTC
**Describe the bug**
Chrome search widget in homescreen is cut on right end portion. This happens everytime my device restarts. 

**To Reproduce**
1. Go to 'homescreen'
2. add 'chrome search' widget
3. restart device

**Smartphone (please complete the following information):**
 - Device: Huawei y6 2018 

**Screenshots**
![Screenshot_20200225-071641](https://user-images.githubusercontent.com/58711855/75200537-e402e400-57a0-11ea-9f5b-476c2cb3fcc1.jpg)

**Comment by 8bitPit** [comment] 2020-02-25 18:42
Thank you for the report, but I believe this is a duplicate of: #1072

**Comment by 8bitPit** [comment] 2020-02-27 09:07
Duplicate of #1072

**Closed by 8bitPit** 2020-02-27 09:07 UTC
Labels: bug, duplicate
