### ISSUE TITLE
YouTube quick actions widget's bottom half is invisible

### ISSUE THREAD

**Issue by stonemcstoned** [8bitPit/Niagara-Issues#2526] opened 2024-01-02 09:41 UTC
### Describe the bug

The bottom half of the YouTube quick actions widget'a bottom half works but it is not visible so i can't always tell what i am clicking.

### Steps to reproduce

Add the YouTube quick actions widget anywhere, a pop up folder or the home page.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

One UI Home

### Device name

Samsung Galaxy A10

### Android version

Android 11

### Screenshots / Screen recordings

What the widget is supposed to look like:

![Screenshot_20240102-123844_One UI Home](https://github.com/8bitPit/Niagara-Issues/assets/152992948/40213a4d-1f1d-4bcb-a881-24ccdee0536d)
![Screenshot_20240102-123854_One UI Home](https://github.com/8bitPit/Niagara-Issues/assets/152992948/2b17c48a-f7b1-424d-81cd-e17a74f97058)

What it looks like on Niagara Launcher:

![Screenshot_20240102-123821_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/152992948/d2711bb5-1086-436c-b2ab-4855b15c7d31)

**Comment by NiagaraSupport** [comment] 2024-01-19 09:10
Hi there and thank you for the report.
The issue is being worked on and will be fixed in the near future.

**Comment by Maxr1998** [comment] 2024-01-19 11:59
Relates to #2469.

**Comment by NiagaraSupport** [comment] 2024-01-19 14:42
I'll go ahead and close this then.

**Closed** 2024-01-19 14:43 UTC
Labels: bug

**Comment by Maxr1998** [comment] 2024-01-20 19:05
The related issue has a broader scope though and is already closed, thus I think we should keep this open.

I need to check this issue on my device though, I believe it actually works if you make the widget tall enough.
