### ISSUE TITLE
Horizontal mode

### ISSUE THREAD

**Issue by casungo** [8bitPit/Niagara-Issues#787] opened 2019-03-08 13:51 UTC
When i get out of a game or a video on youtube, Android takes like 2 seconds to switch to vertical, so I'd like to get a toggle where i can decide to activate/deactivate the auto-rotating launcher.

**Comment by 8bitPit** [comment] 2019-03-08 22:47
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/255

**Closed by 8bitPit** 2019-03-08 22:47 UTC
Labels: duplicate
