### ISSUE TITLE
Proton Calendar

### ISSUE THREAD

**Issue by nathangarff** [8bitPit/Niagara-Issues#2003] opened 2022-07-24 18:57 UTC
### Is your feature request related to a problem?

Yes.

I just upgraded to Pro, and I was looking forward to having calendar functionality built into my home screen to keep things simple, but Niagra doesn't support Proton Calendar. Proton Calendar is a more privacy-focused and secure app than Google Calendar, hence why I prefer it and many of their other apps.

### Describe the solution you'd like

Can Proton Calendar become functional with Niagra, and can it be implemented in the same way as Google Calendar? They are both really similar apps and look like they use similar programming/base.

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Just-SKY** [comment] 2022-07-24 21:32
I asked for the same thing, but it looks like that proton calendar is close for other apps. 
Here is the issue I opened, I hope it helps you to clarify your problem. 
👇🏼
#1599

**Comment by Rod911** [comment] 2022-08-01 17:51
Closing as duplicate of #1599

**Closed by Rod911** 2022-08-01 17:51 UTC
Labels: duplicate
