### ISSUE TITLE
Work Apps Support

### ISSUE THREAD

**Issue by lisbonjoker** [8bitPit/Niagara-Issues#2078] opened 2022-10-06 11:14 UTC
### Is your feature request related to a problem?

Easier way to hide Work Apps from work when not in use.

### Describe the solution you'd like

Check time schedule for work in order to hide in x days from x to x hours.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by schtocker** [comment] 2022-10-07 08:57
Seconding this. I'd love to have this features for folders; in the same way my music apps can pop to the top of my favourites when headphones connect, I'd love a folder of my work apps to pop to the top of my favourites when I'm at work. Integration with existing Android Work mode would be best!

**Comment by lisbonjoker** [comment] 2022-10-07 21:35
> pop to the top of my favourites when I'm at work. Integration with existing Android Work mode would be best!
That too would be an amazing idea, besides hiding them when they are disabled, but when enabled they pop over favorites as they are apps with higher importance during that time!

**Comment by Oddward** [comment] 2022-10-08 14:55
Your request is to make work apps hidden from the launcher entirely when not at work? Or to remove them from favorites when not at work? It's not too clear. Atm there's no functionality to completely hide apps on Niagara coz launchers aren't secure enough to do that reliably (easy to bypass and access the app from outside of the launcher), app lockers should be more reliable. On Niagara you would have to rename the app to hide it from even search.

As for popping up work apps that might be an issue of dynamic favorites which is a much bigger discussion with old github issues like #786 , but Android has a built-in feature called [Focus mode](https://www.blog.google/products/android/android-focus-mode/) to disable distracting apps from being launched and only enable your priority apps for a set duration or until you turn it off.

Automatic folder naming/categorization based on apps placed in a folder has been discussed a bit

**Comment by lisbonjoker** [comment] 2022-10-08 15:51
> Your request is to make work apps hidden from the launcher entirely when not at work? Or to remove them from favorites when not at work? It's not too clear.

just to simply hide it, you can still search for them, but the idea is to integrate with work mode so it auto hides and auto shows.

**Comment by rajk3303** [comment] 2022-10-28 12:29
+1
Would really love to see a similar implementation as of aosp launchers, work apps on a different page with a toggle to turn work apps on/off

Maybe swiping left on the main app screen
Or just a work apps folder, on opening, it shows the toggle and the apps

**Comment by Amorphous404** [comment] 2022-12-15 05:07
Since this is a duplicate of #537, I'll close this, you can add your feedback there.

**Closed** 2022-12-15 05:10 UTC
