### ISSUE TITLE
Support for work profile

### ISSUE THREAD

**Issue by vinaysajjanapu** [8bitPit/Niagara-Issues#1158] opened 2020-01-27 20:23 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the work profile apps appear in regular apps list and are visible even when work profile is turned off in system settings

**Describe the solution you'd like**
Work profile apps should be separated from regular apps. As the number of apps will be mostly less, you can add a section in the bottom of the main list. 

When work profile is turned off in settings, disable the work apps in list by graying them out or completely hiding them in the list.

**Comment by disacrol** [comment] 2020-01-27 20:34
Think this will be covered in #537.

**Comment by 8bitPit** [comment] 2020-01-30 22:24
Duplicate of #537

**Closed by 8bitPit** 2020-01-30 22:24 UTC
Labels: duplicate
