### ISSUE TITLE
Customize launcher with intents

### ISSUE THREAD

**Issue by 71** [8bitPit/Niagara-Issues#1389] opened 2020-10-19 08:09 UTC
I extensively use [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate) to automate things on my phone (many users use [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) for this).

These apps can send intents to other apps at e.g. different times, or when toggling bluetooth, airplane mode, and following many other events.

I wish I could:
- Show / hide apps with intents.
- Customize my favorites with intents.

A few things this could enable:
- Show different favorites when the phone is in airplane mode.
- Show different favorites at night.
- Hide work apps on a schedule.
- Hide entertainment apps after they've been used more than n minutes in a day, and show them again the next day.
- Add Duolingo to the favorites every day and hide it after it's been used more than 10 minutes.

Intents probably don't require a lot of work besides the boilerplate needed to receive them. They could be documented quickly, and probably don't require any specific UI elements.

Furthermore, they could close a lot of feature requests by delegating the work to other apps like Tasker.

**Comment by 8bitPit** [comment] 2020-11-02 11:31
Cool use cases @71, thanks for your suggestion! We plan to integrate Tasker/Automate into Niagara Launcher: #786 to set your favorites dynamically. Depending on how highly it will be requested, we might let the user also control other stuff via those apps.

**Comment by 8bitPit** [comment] 2020-11-02 11:32
Duplicate of #786

**Closed by 8bitPit** 2020-11-02 11:32 UTC
