### ISSUE TITLE
Option to not show icons

### ISSUE THREAD

**Issue by Shapitizer** [8bitPit/Niagara-Issues#1168] opened 2020-02-04 12:54 UTC
Could a toggle be added to remove icons from the apps list? So only the names of apps are shown

**Comment by 8bitPit** [comment] 2020-02-10 22:14
I believe this a duplicate of #140, right?

**Comment by 8bitPit** [comment] 2020-02-27 09:08
Duplicate of #140

**Comment by 8bitPit** [comment] 2020-02-27 09:08
Feel free to open the issue again in case my previous reply didn't help.

**Closed by 8bitPit** 2020-02-27 09:08 UTC
Labels: duplicate
