### ISSUE TITLE
Custom Icon persistent after APP update

### ISSUE THREAD

**Issue by sidneywebba** [8bitPit/Niagara-Issues#1038] opened 2019-10-27 20:05 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the individual apps on my phone update and the custom icons for each app configured on Niagara disappear. Every app defaults to its original icon after the update.

**Describe the solution you'd like**
I would like to be able to select a custom icon for an app and for it to persist between app updates.

**Comment by 8bitPit** [comment] 2019-10-27 21:45
Hi @sidneywebba. Unfortunately I couldn't reproduce this issue. I long pressed an app, tapped on "change icon", assigned it a custom icon and then updated the app. The icon "survived" the app update. Can you please share the version of Niagara Launcher you have installed, your device's model name & android version?

**Comment by 8bitPit** [comment] 2019-11-11 14:21
Feel free to open the issue again in case my previous reply didn't help.

**Closed by 8bitPit** 2019-11-11 14:21 UTC
Labels: bug
