### ISSUE TITLE
Ambidextrous Use

### ISSUE THREAD

**Issue by razortwo5** [8bitPit/Niagara-Issues#541] opened 2018-11-07 21:49 UTC
# Ambidextrous or left handed use.
An option to switch the slider over to the left edge would be much appreciated. An option to have a slider on both edges would also be nice. However, I would suggest that the sliders be regionally activated by a user set height and depth. That way it can prevent accidental swipes of the edge.

**Comment by mare-413** [comment] 2018-11-07 22:30
You can currently swipe on the left side to use the slider, but yes, i do think there should be an option to change that manually.

**Comment by 8bitPit** [comment] 2018-11-09 14:36
Duplicate of #12

**Closed by 8bitPit** 2018-11-09 14:36 UTC
Labels: duplicate
