### ISSUE TITLE
Long press Niagara button for a third shortcut

### ISSUE THREAD

**Issue by deboo117** [8bitPit/Niagara-Issues#2324] opened 2023-07-05 02:58 UTC
### Describe the solution you'd like

The Niagara button is incredibly useful and already has a Tap & Upward Swipe action.
A third gesture could easily be incorporated imo

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-07-12 18:24
Hi @deboo117, Thank you for reaching out!

Please refer to our "[Niagara Button](https://help.niagaralauncher.app/article/116-niagara-button)" article, where we explained our rationale behind using a single gesture on the Niagara button.

>**Why can we only utilize one swipe gesture?**

>We don't want to overload the Niagara button with dozens of gestures. That's because we want to keep everything simple and easy to remember, and only allowing one swipe gesture makes the behavior of the button more consistent with the behavior of app pop-ups. The swipe-up gesture is the easiest one to execute at the bottom right corner. If you want to keep your home screen free of apps, we recommend adding a pop-up to the Niagara button

**Comment by Amorphous404** [comment] 2023-07-12 18:26
- Duplicate of #1641

**Closed** 2023-07-12 18:25 UTC
