### ISSUE TITLE
Home screen cropped and centre.

### ISSUE THREAD

**Issue by Pierce913** [8bitPit/Niagara-Issues#2149] opened 2022-12-13 02:23 UTC
### Describe the bug

From time to time going to the home screen is rendered offset and clipped. When you press home again to bring up app search the go back to the home screen rendering is corrected. Not sure what conditions cause this but it often happens when coming back to the phone after some time. Attached screenshots show the crop and corrected rendering.

### Steps to reproduce

1. Press home.
2. Notice rendering looks clipped.
3. Press home again to bring up search.
4. Press back
5. Notice home screen now renders properly.

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Samsung Galaxy Note 10+

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20221213-130705_Niagara Launcher](https://user-images.githubusercontent.com/8165342/207210428-9ea51f69-24bd-458a-8093-2df06a53b9ea.jpg)
![Screenshot_20221213-130710_Niagara Launcher](https://user-images.githubusercontent.com/8165342/207210442-3a00cefd-cffd-45fd-ad26-3e8be2369e08.jpg)

**Comment by Amorphous404** [comment] 2022-12-13 06:13
Duplicate of #2144

**Closed** 2022-12-13 06:14 UTC
Labels: bug, duplicate
