### ISSUE TITLE
Scrollable widget in pop-up causes app/folder editing menu to come up

### ISSUE THREAD

**Issue by Migilang** [8bitPit/Niagara-Issues#2016] opened 2022-08-10 07:52 UTC
### Describe the bug

When having a scrollable widget in app/folder pop-up, the app/folder editing menu sometimes comes up unexpectedly when you scroll to the top or bottom end of the widget. If I exit just as the editing menu comes up, all the pop-ups fail to launch until Niagara is restarted.

### Steps to reproduce

1. Have a scrollable widget in the pop-up (e.g. gmail, calendar).
2. Scroll to the either end of the widget (there is vibration, this happens about 80% of the time).
3. The app/folder editing menu comes up.
4. If you exit (tap something else) just as the editing menu is about to start, all the pop-ups fail to launch until Niagara is restarted.

### Device name

ASUS ZenFone 8

### Android version

Android 12

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/44521972/183845937-1a8c897f-29f4-4627-b5c2-3a93fdf4c12a.mp4

https://user-images.githubusercontent.com/44521972/183845954-4bf7fcd6-d013-44c0-97ff-a0a968ebb68f.mp4

**Comment by Oddward** [comment] 2022-08-29 19:42
Seems like a duplicate of #1647 - please follow it there. We couldn't reproduce it and figured it may be a device issue, just a few other people have reported it so far. You can add your info to the linked issue to track it in one place

The first video looks very weird 🤔 is it related? Maybe a screen issue? If it's a different issue regarding Niagara please open another ticket

**Closed by Oddward** 2022-08-29 19:42 UTC
Labels: bug
