### ISSUE TITLE
Remove gesture bar

### ISSUE THREAD

**Issue by milesmcclane** [8bitPit/Niagara-Issues#2639] opened 2024-03-30 06:36 UTC
### Is your feature request related to a problem?

There is already the option to remove the menu bar at the top, it would be much cleaner if the bottom gesture bar could also be removed. 

### Describe the solution you'd like

I would like the option to remove this gesture bar. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-04-11 11:33
Hey there and thanks for your request,
I'll close this as a duplicate of #2591. The short answer is that it is system behavior and not something we can change.

**Closed** 2024-04-11 11:33 UTC
