### ISSUE TITLE
Calendar - meetings of today

### ISSUE THREAD

**Issue by JackerNils** [8bitPit/Niagara-Issues#580] opened 2018-11-17 20:57 UTC
Hi,

I really like the launcher, but I need to see the meetings of my day from my Google Calendar in my launcher. Like the Google Calendar Widget in the normal launcher.

I hope you can implement that!

**Comment by 8bitPit** [comment] 2018-11-17 22:20
Duplicate of #319

**Closed by 8bitPit** 2018-11-17 22:20 UTC
Labels: duplicate
