### ISSUE TITLE
[To Close]Blur wallpaper when displaying all app list

### ISSUE THREAD

**Issue by billouetaudrey** [8bitPit/Niagara-Issues#1472] opened 2021-01-17 12:48 UTC
Hi, I have a little idea/suggestion, Is it possible to blur wallpaper when display all app ? Thanks :)

It's perfect for better look of app name ;)

Thanks

**Comment by billouetaudrey** [comment] 2021-01-17 13:02
Sorry found here https://help.niagaralauncher.app/article/64-blur-wallpaper

**Comment by Rod911** [comment] 2021-01-17 13:55
Thanks for the request, as this was already requested and discussed in #14, I'm closing this ticket.

Duplicate of #14

**Closed** 2021-01-17 13:55 UTC
Labels: duplicate
