### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by dansmeah** [8bitPit/Niagara-Issues#1712] opened 2021-09-22 16:35 UTC
### Is your feature request related to a problem?

I feel that things like scrolling through the alphabet should give haptic feedback for each letter. 

### Describe the solution you'd like

I feel that things like scrolling through the alphabet should give haptic feedback for each letter.

**Comment by Rod911** [comment] 2021-09-22 19:53
Please see https://help.niagaralauncher.app/article/99-vibration-for-alphabet-scrolling

Duplicate of #200

**Closed** 2021-09-22 19:54 UTC
Labels: duplicate
