### ISSUE TITLE
List often unwillingly scrolls down when repositioning an app

### ISSUE THREAD

**Issue by mrd77** [8bitPit/Niagara-Issues#2605] opened 2024-02-25 00:12 UTC
### Describe the bug

When changing an App's position by dragging, the list can scroll down in an unexpected manner every time the app changes it's ranking on the list. I could reproduce this behaviour when changing the favourites, as well as when editing an app's pop-up. The list may need enough entries to overflow the screen and you may have to go up and down with the app a bit for this to happen

### Steps to reproduce

- Have enough favourite apps for the list to overflow
- Try to add a new favourite
- On the edit favourites screen, tap and hold an app to drag it around
- Drag the app up and down the list. This behaviour may not reproduce right away

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 7

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/32589874/a4169b70-7483-4787-84c1-3f09c15b51d7

**Comment by NiagaraSupport** [comment] 2024-02-28 12:45
Hi there, thanks for your report.
I will close this as a duplicate of #1660. It's a known issue, but It'll take some time to get fixed due to different priorities.

**Closed by NiagaraSupport** 2024-02-28 12:45 UTC
Labels: bug
