### ISSUE TITLE
Customize style for google search button

### ISSUE THREAD

**Issue by luisnbispo** [8bitPit/Niagara-Issues#1284] opened 2020-05-14 01:49 UTC
It would be nice if you could change the color, or choose from a few different types of buttons for that search button.

**Comment by 8bitPit** [comment] 2020-05-14 12:22
Thanks for your request @luisnbispo, it's already on our list: https://github.com/8bitPit/Niagara-Issues/issues/303

**Comment by Rod911** [comment] 2020-05-27 16:31
Duplicate of #303

**Closed by Rod911** 2020-05-27 16:31 UTC
