### ISSUE TITLE
Font sizing for home display

### ISSUE THREAD

**Issue by Jefficus** [8bitPit/Niagara-Issues#929] opened 2019-07-11 04:37 UTC
I can resize the app icons but that doesn't change vertical spacing, so it doesn't display more app choices on the screen. I'd love to be able to make the list items themselves smaller so that I can see a few more before having to scroll.

**Comment by 8bitPit** [comment] 2019-07-11 20:02
Hey @Jefficus, would you like to have something like this: https://github.com/8bitPit/Niagara-Issues/issues/304?

**Comment by Jefficus** [comment] 2019-07-11 20:14
Yes, I suppose that's another way of looking at the same issue.

**Comment by 8bitPit** [comment] 2019-07-22 16:53
All right, then I'll close this one :)

**Comment by 8bitPit** [comment] 2019-07-22 16:53
Duplicate of #304

**Closed by 8bitPit** 2019-07-22 16:53 UTC
Labels: duplicate, question
