### ISSUE TITLE
Hide icons

### ISSUE THREAD

**Issue by thiagomendesdev** [8bitPit/Niagara-Issues#2888] opened 2024-09-08 11:19 UTC
### Describe the solution you'd like

Please add an option to not show icons. It would be nice to make the home screen even cleaner and minimalist 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-09-11 13:11
Hey there, thanks for your suggestion.
I'll close this as duplicate of #2782, #140, and therein mentioned tickets.

**Closed** 2024-09-11 13:14 UTC
Labels: duplicate
