### ISSUE TITLE
Homepage of Niagara not respecting disabled apps that ran out Digital wellbeing timer

### ISSUE THREAD

**Issue by suhasasj010** [8bitPit/Niagara-Issues#1037] opened 2019-10-27 18:31 UTC
When an app's timer runs out(say, 30mins) then the app will be disabled and no notifications will go through the notification center. But the same is not true with Niagara homepage. It still shows notifications from disabled apps(please find the screenshot attached).

Please look into it.

 - Device: Poco F1
 - Android version: Android 9.0 Pie

![Screenshot_20191027-235853_Niagara_Launcher](https://user-images.githubusercontent.com/11756922/67639465-e7cb4a80-f915-11e9-9645-77eb1f236b1f.png)

**Comment by 8bitPit** [comment] 2019-11-11 15:40
Duplicate of #893

**Closed by 8bitPit** 2019-11-11 15:40 UTC
Labels: bug
