### ISSUE TITLE
Foldable - cover screen as replica of first column from main screen

### ISSUE THREAD

**Issue by NayanReddi** [8bitPit/Niagara-Issues#2428] opened 2023-11-13 08:46 UTC
### Describe the solution you'd like

Two column option is great when foldable is opened. But when it's closed having the first column as main screen would be great than clubbing both columns into one.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2023-11-16 09:28
Duplicate of #1707

#1707 is a more general request but the same issues arise as mentioned there.

**Closed by TFackler** 2023-11-16 09:28 UTC
