### ISSUE TITLE
Background blur

### ISSUE THREAD

**Issue by CV-fr** [8bitPit/Niagara-Issues#2283] opened 2023-05-19 06:26 UTC
### Is your feature request related to a problem?

Hey i love this launcher and i just purchased the lifetime pro version. I think it would be cool to add a background blur toggle while scrolling through the app menu (while holding the alphabets).
And the recents menu gesture has a little late response while on the home screen.
That's about it.
Thanks 🙏.

### Describe the solution you'd like

I guess it wouldn't be much of a problem to add a blur. (I have no idea about Android app development fr)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-05-20 19:34
> I think it would be cool to add a background blur toggle while scrolling through the app menu (while holding the alphabets).

Duplicate of #14 

> And the recents menu gesture has a little late response while on the home screen.
That's about it.

If you're using a Samsung device, The delay is from them, not us; they added it to all third-party launchers. We assume they added the delay because some launchers react to the "home button press" action (e.g., to open app search), which is easier for the user to trigger that way.
• [Recent Apps Screen & Gesture Navigation Issues](https://help.niagaralauncher.app/article/114-recent-apps-screen-issues)

**Closed** 2023-05-20 19:40 UTC
Labels: duplicate
