### ISSUE TITLE
horizontal favorite apps list

### ISSUE THREAD

**Issue by Francais04** [8bitPit/Niagara-Issues#940] opened 2019-07-25 18:11 UTC
It would be very cool , if developers add an option in which you will be able to turn vertical favorite apps list to horizontal, like dock bar.
Thanks, your user ))

**Comment by 8bitPit** [comment] 2019-08-02 20:03
Hey @Francais04, I'm sorry but I guess that design isn't suited for Niagara. The whole has to be rebuilt, things like notifications or the swipe menu wouldn't work in horizontal mode.

**Comment by 8bitPit** [comment] 2019-08-02 20:03
Duplicate of #155

**Closed** 2019-08-02 20:03 UTC
Labels: duplicate, infeasible
