### ISSUE TITLE
Widget not updating after changing wallpaper

### ISSUE THREAD

**Issue by MAgnEt1155** [8bitPit/Niagara-Issues#1823] opened 2022-01-12 01:55 UTC
### Describe the bug

hello dear Niagara. I ask you to pay attention to this problem, it appeared in version 1.5, the essence is that when you change the wallpaper, the launcher puts a copy of it on the widget, which does not change in any way. as an example in the video you can see that the cover of the track does not change and the clock also stops. I checked on other launchers and without them and everything works fine there. Please fix three updates already, I can not install any third-party widget.

### Steps to reproduce

1 put KWGT widget
2 change wallpaper
3 watch error

### Device name

Samsung Galaxy M31S

### Android version

Android 11

**Comment by MAgnEt1155** [comment] 2022-01-12 02:01
>

**Comment by Oddward** [comment] 2022-01-12 22:29
@MAgnEt1155 I don't see any video attached. And about the bug, it sounds like a relatively common issue with KWGT, especially on older builds, where it freezes until you interact with it or replace it. 

You can try some things to maybe fix it like enabling permanent notification in the KWGT settings or setting the update rate to be every second instead of the default

**Comment by MAgnEt1155** [comment] 2022-01-13 01:18
KWGT has nothing to do with all the settings in it that I need, I included. but the problem appeared after the update 1.5 on previous versions everything works fine

**Comment by MAgnEt1155** [comment] 2022-01-13 01:21
https://user-images.githubusercontent.com/85721943/149248805-9c4f1983-03ed-4817-8cb3-a63bdc76f194.mp4

**Comment by MAgnEt1155** [comment] 2022-01-13 01:35
https://user-images.githubusercontent.com/85721943/149249972-692189e4-4318-43e6-a500-082aa6af13be.mp4

**Comment by MAgnEt1155** [comment] 2022-01-15 05:22
> @MAgnEt1155 I don't see any video attached. And about the bug, it sounds like a relatively common issue with KWGT, especially on older builds, where it freezes until you interact with it or replace it. 
> 
> You can try some things to maybe fix it like enabling permanent notification in the KWGT settings or setting the update rate to be every second instead of the default

https://user-images.githubusercontent.com/85721943/149610131-fdd25f83-fbe2-47d7-969f-f719399ffaf9.mp4

**Comment by Maxr1998** [comment] 2022-02-07 22:47
Duplicate of #1274. Will hopefully be finally fixed in the next release.

**Closed** 2022-02-07 22:49 UTC
Labels: bug, duplicate
