### ISSUE TITLE
Themed icons not supported in android 13

### ISSUE THREAD

**Issue by markdid** [8bitPit/Niagara-Issues#2093] opened 2022-10-19 15:43 UTC
In android 13, there is a beta feature called themed icons that changes icons to be the same color matching your wallpaper. Does not apply when using the Niagara launcher.

**Comment by topsy-turvy99** [comment] 2022-11-11 18:20
https://github.com/8bitPit/Niagara-Issues/issues/1800#issuecomment-1087648593

Duplicate of #1800

**Closed** 2022-11-15 18:04 UTC
