### ISSUE TITLE
Keyboard appears on opening launcher

### ISSUE THREAD

**Issue by eduardo-svg** [8bitPit/Niagara-Issues#1115] opened 2019-12-29 18:49 UTC
Upon opening the launcher, whether from the lock screen or by hitting the home button from an app, G board immediately opens.

**To Reproduce**
1. Unlock the phone and/or press the home button
2. That's it!

 - Device: OnePlus 6
 - Android version: 10

**Comment by 8bitPit** [comment] 2019-12-29 20:02
Hi @eduardo-svg, thank you for your report. How often does this happen? Every time you unlock your phone? Can the bug also be reproduced with other third-party launchers like Nova Launcher?

**Comment by 8bitPit** [comment] 2020-01-13 13:52
Feel free to open the issue again. But please answer my questions beforehand.

**Comment by inthecircle** [comment] 2020-02-19 09:44
Hello, the exact same thing happens on my phone.

LG G7
Android 9

Scenario 1
Lock phone
Unlock - And the Google keyboard is open. Have to press back button to make it disappear.

Scenario 2
Open any app and then hit return. And when back in the home page, the Google keyboard stays open. Pressing back button makes it disappear.

**Comment by ParichayGupta** [comment] 2020-02-21 11:58
if you are using android studio 
then in the menifest file for the launcher activity try this code

<activity
    ...
    android:windowSoftInputMode="stateHidden|adjustResize"
    ...
>

**Comment by inthecircle** [comment] 2020-02-21 12:00
Actually the issue solved after the update you guys pushed the day after i posted my issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by inthecircle** [comment] 2020-02-21 19:59
Hey,

The issue came back, but only when i open Netflix and leave it in the background . After phone restart it goes away.

Sorry didn't open netflix for free days

Regards Ajay

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by profwyattb** [comment] 2020-02-22 15:12
This happens to me constantly! Very frustrating :triumph:

**Comment by 8bitPit** [comment] 2020-02-25 19:03
@inthecircle @profwyattb Does this also happen on other third party launchers?

**Comment by inthecircle** [comment] 2020-02-25 19:18
Haven't tried. Cause i can't find another Niagra type launcher.

But either way i close Netflix and restart my phone it goes away. It used to open often even in normal apps but you guys sent an update about a week ago after which it only happens when Netflix is opened and there after.
Anyway it isn't a deal breaker.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by profwyattb** [comment] 2020-02-25 19:45
Haven't tried but managed to fix it after going back to v15.2 from v16

**Comment by profwyattb** [comment] 2020-03-13 21:35
Back in v19

**Comment by 8bitPit** [comment] 2020-03-15 15:34
@profwyattb does it also appear in Nova Launcher or Lawnchair Launcher?

**Comment by profwyattb** [comment] 2020-03-15 15:44
No, it doesn't seem to. Going back to v18.1 seems to resolve the issue

**Comment by TFackler** [comment] 2020-03-24 17:18
Another user also said he is experiencing this issue.

After searching for an app and then going back to the home screen using the home button the keyboard stays opened.

**Comment by 8bitPit** [comment] 2020-05-02 10:56
I believe a new bug was introduced in one of the latest versions, I'm working on a fix. To temporarily prevent this from happening, open Niagara's search and close it again.

**Comment by 8bitPit** [comment] 2020-06-04 11:01
Does it still occur in v0.28+?

**Comment by profwyattb** [comment] 2020-06-04 11:16
I haven't had the issue for a long time so it seems to be fixed now 👍

**Comment by 8bitPit** [comment] 2020-06-04 11:17
Great :D I'll close this for now, but please let me know if the issue occurs again.

**Closed by 8bitPit** 2020-06-04 11:17 UTC
Labels: bug, question
