### ISSUE TITLE
Clock color based on wallpaper color

### ISSUE THREAD

**Issue by RenLeaf544** [8bitPit/Niagara-Issues#2747] opened 2024-06-15 20:02 UTC
### Is your feature request related to a problem?

   No

### Describe the solution you'd like

The built-in clock in Niagara has many looks for the pro version. Which is Awesome. 
But can you guys make it so it can change color according to wallpaper like the Niagara button?

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2024-06-24 21:29
Thanks for this suggestion.

It seems to be a duplicate of #2519, so please add your thoughts over there, or give it a thumbs up, so we can track which issues are popular :)

**Closed** 2024-06-24 21:29 UTC
Labels: duplicate
