### ISSUE TITLE
Left Handed Mode

### ISSUE THREAD

**Issue by jonathanschaaij** [8bitPit/Niagara-Issues#958] opened 2019-08-09 18:52 UTC
Currently when you use your right hand to go from favorites to the alphabetical apps list everything looks clean and elegant, however, when using the left hand, it shows the same. The icons and apps names on the left and the alphabet on the right, but that way the left hand blocks view of the apps, making it kinda annoying to quickly open an app. This is definitely just a small issue but one that might be important for left-handed users.

**Comment by 8bitPit** [comment] 2019-08-10 08:50
Thanks for the request @jonathanschaaij. You can already scroll on the left side, but it's a bit hidden right now, I think I should add a little info message explaining that. Furthermore, a mode especially made for lefties might be implemented, see: #12

**Comment by 8bitPit** [comment] 2019-08-10 08:51
Duplicate of #12

**Closed by 8bitPit** 2019-08-10 08:51 UTC
Labels: duplicate

**Comment by Rod911** [comment] 2019-08-10 09:05
I don't that was his issue @8bitPit .

**Comment by 8bitPit** [comment] 2019-08-10 09:13
Yeah it's not about the scrollbar, but I thought this tip could help anyways. #12 is also about flipping the whole layout though.
