### ISSUE TITLE
Option to change the opacity of pop up folder window

### ISSUE THREAD

**Issue by MrAwkward3301** [8bitPit/Niagara-Issues#2209] opened 2023-02-19 17:05 UTC
### Is your feature request related to a problem?

No option to opacity control of the pop up folder window.

### Describe the solution you'd like

Added option of opacity scale for the pop up folder's window to make it look more minimal and aesthetically pleasing.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-02-20 00:33
Duplicate of #2024

**Closed** 2023-02-20 00:34 UTC
