### ISSUE TITLE
Add Vibration to alphabet scroll

### ISSUE THREAD

**Issue by luisbettencourt** [8bitPit/Niagara-Issues#1750] opened 2021-11-20 13:50 UTC
### Is your feature request related to a problem?

When using the alphabet scroll to search through apps it can be confusing at first when the alphabet scroll doesn't open and you're scrolling instead through the favorite apps. 

### Describe the solution you'd like

Adding a subtle haptic feedback vibration to the alphabet list would make it obvious on what's being scrolled, with the added bonus of making it (in my opinion) more satisfying to scroll through (probably best to have an option to switch on/off).

**Comment by Maxr1998** [comment] 2021-11-20 16:00
I feel while this could be nice for some people, it wouldn't be a generally appreciated change, especially since haptic feedback is so inconsistent across different Android devices. Adding a toggle would be possible, but wouldn't match our [design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles).
Thus, this is probably not something we'll add, but I expect @8bitPit can tell you more about that.

**Comment by luisbettencourt** [comment] 2021-11-20 16:14
It could always be disabled by default, that would make it universal and independent (according to the design principles). As for making it simple, an added switch on the settings screen is a trade-off that might make sense and as for being impactful I don't think this feature would be turned on by the majority of users but it could still have significant enough adoption.

**Comment by Maxr1998** [comment] 2021-11-27 18:01
Actually, I just noticed this is a duplicate of #200. You can also read more reasons to why we don't plan to add this [in our knowledge base](https://help.niagaralauncher.app/article/99-vibration-for-alphabet-scrolling).

**Closed** 2021-11-27 18:02 UTC
Labels: duplicate
