### ISSUE TITLE
Apps sometimes not opening, showing blank background screen

### ISSUE THREAD

**Issue by Magicadi** [8bitPit/Niagara-Issues#2670] opened 2024-04-22 06:02 UTC
### Describe the bug

Since Android 14 a bug persists, where when opening any app, be it whatsapp, brave, chrome from the favorites, the app doesn't actually open. The background as well as the top android info bar is displayed. Simply going back to the homescreen and reopening the app resolves the issue.

### Steps to reproduce

1. Open any app on the homescreen favorites

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Nothing Phone 1 (2.5.3.A)

### Android version

Android 14

### Screenshots / Screen recordings

![Screenshot_20240422-075401](https://github.com/8bitPit/Niagara-Issues/assets/30390203/dccb712d-cfc5-4303-a945-01465c18d580)

**Comment by NiagaraSupport** [comment] 2024-05-15 11:03
Hey there, thank you for the report.
We're aware of this issue, and I'll bring it up again during our discussions to see if progress has been made. I will close this ticket as a duplicate of #2420 and the others mentioned.

**Closed by NiagaraSupport** 2024-05-15 11:03 UTC
Labels: bug
