### ISSUE TITLE
Blackplayer widget bugging out

### ISSUE THREAD

**Issue by djkato** [8bitPit/Niagara-Issues#821] opened 2019-04-04 15:38 UTC
The bug is widget disappearing for music, specifically blackplayer. 

1. Go home from the app
2. Touch the widget to open it again
3. Open the recent apps thingy
4. Tap away from it to get back on home 
3. Scroll down n back 

I expect it to not dissappear. 
Video of it happening. I managed to get it bug 50%of the time

https://drive.google.com/file/d/1IJmpAC-VGFe028iFI0JnrpjUT3HO9OtP/view?usp=drivesdk

 - Device: honor 10
 - OS: Android 9

**Comment by 8bitPit** [comment] 2019-04-04 15:43
Duplicate of #811

**Closed** 2019-04-04 15:43 UTC
Labels: duplicate
