### ISSUE TITLE
Context menu for niagara settings

### ISSUE THREAD

**Issue by iamt0bie** [8bitPit/Niagara-Issues#1837] opened 2022-01-25 00:26 UTC
For simplicity and consistency's sake, long-pressing "Niagara settings" at the bottom of the list should bring up a context menu, like all other apps and folders in the list 

Personally, I want this so I can change the icon and the name to fit the aesthetic of the rest of my launcher, but honestly, all the other options in the standard context menu could be helpful 

Notably, it's unintuitive to get to the app info for the launcher (open settings, go to app switcher, go back to niagara, tap the icon at the top, and then select app info)

I'm also sure some people would appreciate the ability to hide the settings from the list, especially since it's fairly redundant: you can access settings from every other context menu 

Also, I just feel like this would better fit the design principles. It feels really awkward when you notice that one item in the list doesn't work the same way as the rest of the list 

- It's simple: no added settings!
- It's impactful: helps anyone who uses an icon pack!
- It's universal: if every phone can handle folders (with context menus) that contain apps each with their own context menu, I'm sure they can handle one more context menu!
- It's independent: right now, nobody notices this missing context menu unless they're looking for it. If it's added, nobody will notice it, regardless of if they're looking for it or not!

Please consider adding this, I'd really appreciate it!

**Comment by Oddward** [comment] 2022-03-12 14:08
Funny enough, it seems like in the earlier days of Niagara the settings were only at the bottom of the list, but because they noticed that too many users never opened it or realized it's there they added a quicker way to access the settings. If someone just wants to open settings it might still be faster to zip to the bottom by tapping the alphabet list & open it.

As for customizing that list item at the bottom, I think it's very low priority since it's pretty out of sight and now its icon follows the accent colours, however, there's an issue for it already, track it [here](https://github.com/8bitPit/Niagara-Issues/issues/1595)

As for the context menu it seems redundant, you can get to the launcher's app info via **Niagara settings > Advanced > tap the App info button with the version number**

Should we close this?

**Comment by topsy-turvy99** [comment] 2022-04-10 02:05
> Funny enough, it seems like in the earlier days of Niagara the settings were only at the bottom of the list, but because they noticed that too many users never opened it or realized it's there they added a quicker way to access the settings. If someone just wants to open settings it might still be faster to zip to the bottom by tapping the alphabet list & open it.
> 
> As for customizing that list item at the bottom, I think it's very low priority since it's pretty out of sight and now its icon follows the accent colours, however, there's an issue for it already, track it [here](https://github.com/8bitPit/Niagara-Issues/issues/1595)
> 
> As for the context menu it seems redundant, you can get to the launcher's app info via **Niagara settings > Advanced > tap the App info button with the version number**
> 
> Should we close this?

i have also been planning to ask for something similar for a long time now not particularly for changing the Niagara setting icon but for accessing some quick setting via Niagara setting context menu to change wallpaper, icon pack, hide/show status bar, create a pop-up folder.

![Frame(16)](https://user-images.githubusercontent.com/96917972/162598084-2552940f-0928-480b-8059-2d97b9d30ad3.jpg)

**Comment by Oddward** [comment] 2022-04-10 15:05
The settings are intentionally kept very simple so all of that is easy to do in a couple of taps anyway, it still seems redundant to have specific shortcuts that you consider to be important & frequent. All those options are customization which is already grouped in the Look settings  

Folders can quickly be made in the **Edit favourites** screen at the bottom 

A lot of the items, shortcuts and data you like to request to have around the UI reduces its minimalism and was avoided by design, they're not just things nobody thought of. Thins that are vaguely "nice to have" usually go against the [design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles) 

Note: If you navigate to a page in Niagara's settings and then go home instead of back it stays open in your recent apps so you can get back to it, if you want you can probably pin it there 🤔

**Comment by topsy-turvy99** [comment] 2022-05-09 15:21
> The settings are intentionally kept very simple so all of that is easy to do in a couple of taps anyway, it still seems redundant to have specific shortcuts that you consider to be important & frequent. All those options are customization which is already grouped in the Look settings  
> 
> Folders can quickly be made in the **Edit favourites** screen at the bottom 
> ![Screenshot_2022-04-10-17-03-39-245_bitpit.launcher~2.jpg](https://user-images.githubusercontent.com/22635314/162626060-683a9cad-669d-4080-a4ef-51ea1f4425f6.jpg)
> 
> A lot of the items, shortcuts and data you like to request to have around the UI reduces its minimalism and was avoided by design, they're not just things nobody thought of. Things that are vaguely "nice to have" usually go against the [design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles) 
> 
> Note: If you navigate to a page in Niagara's settings and then go home instead of back it stays open in your recent apps so you can get back to it, if you want you can probably pin it there 🤔 
> ![Screenshot_2022-04-10-17-03-17-946_com.android.systemui~2.jpg](https://user-images.githubusercontent.com/22635314/162626109-c71b3cc1-ad09-48ca-9190-81b255c7e73d.jpg)

Sadly pinning option is not available in pixel launcher,

![Screenshot_20220509-202049_Niagara Launcher.png](https://user-images.githubusercontent.com/96917972/167442027-71a1cc83-4027-47a5-a135-5c409e72e658.png)

Got your point, I'm totally fine not adding the other features but can the wallpaper picker be added to Niagara widget access menu for quick access, like the other launcher, it's tiring every time to go to Niagara settings to access the wallpaper and styles

**Comment by Oddward** [comment] 2022-05-12 18:20
@topsy-turvy99 the Pixel launcher doesn't let you pin apps in the recent apps screen? On Samsung on the recent apps screen you would long-press on the app icon above the app preview, then tap "Keep open", you might have something similar.

---
Niagara's wallpaper uses the system level wallpaper, meaning from whatever wallpaper or gallery app you're using you can just apply the wallpaper without specifying Niagara. Have you tried this? What sources do you usually use to apply wallpapers? 

I normally only ever go to the Niagara settings to set a wallpaper if it's a live wallpaper coz it's sometimes easier. From a gallery I just use the *Use as* option, or from a wallpaper app I'd just *Apply*

**Comment by topsy-turvy99** [comment] 2022-05-12 18:29
Clicking on the wallpaper from Niagara setting opens up the wallpaper and styles from their i choose the source i.e photos the albums are presented in a neat listed manner, so yeah i always use the Niagara setting to set the wallpaper,

There's space in widget context menu, if the wallpaper shortcut was added above the Niagara setting that would be cool 🙂

**Comment by Oddward** [comment] 2022-05-12 19:25
My point was that you can apply a wallpaper from pretty much anywhere on your device and it works for Niagara, having a button for it in the context menu in front of every user to save a couple of taps seems very redundant. At best it could go in the Niagara widget options pop-up, if anywhere, but it's unlikely.

**Comment by topsy-turvy99** [comment] 2022-05-12 19:30
Yes, that is where i was exactly talking about, but yeah was just suggesting it, Implementing it or not is upto you guys

**Closed** 2022-06-03 19:08 UTC
Labels: awaiting-response
