### ISSUE TITLE
Option to remove popup which ask for location.

### ISSUE THREAD

**Issue by pradyw** [8bitPit/Niagara-Issues#743] opened 2019-02-06 09:43 UTC
If weather feature is on and location is off on device then it asks to turn on the location which is persistent on home screen and that is annoying.
If possible add on option to cancel the popup and ask for first time only. so that if location is on than display weather else not

**Comment by 8bitPit** [comment] 2019-02-10 21:48
Fixed in v.0.
Duplicate of #274

**Closed by 8bitPit** 2019-02-10 21:48 UTC
Labels: duplicate

**Comment by pradyw** [comment] 2019-02-11 04:41
![img-20190211-wa0000](https://user-images.githubusercontent.com/43058329/52546436-3b782100-2de5-11e9-8167-db5027347e55.jpg)
I meant this. 
V. 0.7.3

**Comment by Rod911** [comment] 2019-02-11 20:18
If you disable weather feature in settings, it doesn't ask you for location.

**Comment by pradyw** [comment] 2019-02-12 03:40
> If you disable weather feature in settings, it doesn't ask you for location.

I know that (but if i do that,it means  i am disabling the whole feature).
What i want is if i enable location then it should display weather. and this prompt should be dismissable if location is off.
