### ISSUE TITLE
Next alarm next to or below the time

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#1789] opened 2021-12-28 18:01 UTC
### Is your feature request related to a problem?

I ask, is it possible in the next Niagara Launcher update to show next or below the time the next alarm? Thank you

### Describe the solution you'd like

I ask, is it possible in the next Niagara Launcher update to show next or below the time the next alarm? Thank you

**Comment by SuyalAhd** [comment] 2022-01-04 15:14
![IMG_20220104_204231_967](https://user-images.githubusercontent.com/96917972/148080302-c3a467d7-ac7c-4031-888f-ca3f997578cf.jpg)
Maybe Something Like This 😊

**Comment by Livio78** [comment] 2022-01-04 18:38
That's right is what I had in mind, I hope there is not too much space between the next alarm and the date so as not to drop the favorites too low. Hope it will be introduced in the next update. I hope I was as clear as possible. Thanks in advance    Il martedì 4 gennaio 2022, 16:14:53 CET, SuyalAhd ***@***.***> ha scritto:  
 
 



Maybe Something Like This 😊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Maxr1998** [comment] 2022-01-28 12:41
Duplicate of #4.

**Closed by Maxr1998** 2022-01-28 12:41 UTC
