### ISSUE TITLE
Have a launcher section for apps with active notifications

### ISSUE THREAD

**Issue by incensesmoke** [8bitPit/Niagara-Issues#1217] opened 2020-03-16 09:46 UTC
I just started using this launcher and like it a lot. One thing that I'm perhaps missing is that I'd like for apps that have unread notification to appear at the top of the list. This makes sense to me as those are the apps that need "attention" when I check my phone. One way of doing this would be to have a section like the favorites section, but for apps that meet the notification criteria. In edit mode this could be placed at the top of the homescreen by the user if needed. Perhaps this is a feature that more users would be interested in?

**Comment by 8bitPit** [comment] 2020-03-17 17:35
Thank you for your kind words :) I think this is what you want, right? https://github.com/8bitPit/Niagara-Issues/issues/152

**Comment by incensesmoke** [comment] 2020-03-17 19:43
Absolutely, that's exactly it. Thanks for the quick reply and sorry for
duplicating :/

Keep up the great work!

**Comment by 8bitPit** [comment] 2020-03-17 20:53
Haha, no problem. Thanks @incensesmoke!

**Comment by 8bitPit** [comment] 2020-03-17 20:53
Duplicate of #152

**Closed by 8bitPit** 2020-03-17 20:53 UTC
Labels: question
