### ISSUE TITLE
Double-tap Lock

### ISSUE THREAD

**Issue by bluemonday91** [8bitPit/Niagara-Issues#776] opened 2019-02-28 11:26 UTC
**Is your feature request related to a problem? Please describe.**
When I double-tap to lock my phone as I usually would, it doesn't lock. 

**Describe the solution you'd like.**
Implementation of the gesture.

**Additional context.**
This launcher doesn't have some elementary gestures you'd find on any given launcher. It's a shame because it's a quality launcher, and having to recur to the lock/fingerprint button on the back of the phone compromises the whole UX.

**Comment by disacrol** [comment] 2019-02-28 12:00
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/63.

**Closed** 2019-02-28 22:51 UTC
Labels: duplicate
