### ISSUE TITLE
web search

### ISSUE THREAD

**Issue by kurokirasama** [8bitPit/Niagara-Issues#2065] opened 2022-09-22 14:08 UTC
### Is your feature request related to a problem?

nop

### Describe the solution you'd like

It would be nice that, natively, when pulling up the search bar, it would search in the web (like chrome) instead of the playstore.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Foxbat24N** [comment] 2022-09-22 16:20
One can do this with sesame integration. 
But if it happens then it will be good for those who don't own sesame.

**Comment by topsy-turvy99** [comment] 2022-09-22 19:52
> ### Is your feature request related to a problem?
> nop
> 
> ### Describe the solution you'd like
> It would be nice that, natively, when pulling up the search bar, it would search in the web (like chrome) instead of the playstore.
> 
> ### Feature Request Procedure
> * [x]  I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

Duplicate of #1501

**Closed** 2022-09-24 21:15 UTC
