### ISSUE TITLE
A few thoughtful suggestions #3

### ISSUE THREAD

**Issue by Shinra04** [8bitPit/Niagara-Issues#1522] opened 2021-02-27 13:18 UTC
Been a while, thought I'd create another thread, based on my usage. You've done some great stuff over the years, keep it up.

1. Notifications

Problem:  
Currently, you only see notifications on your favorite screen for the few 8-10 main apps. It feels lacking since there are a multitude of apps I'd like to see notifications of, without needing to swipe down notification tray every time. Having notifications within the folder of apps makes it more problematic though. 

Solution:
- Dedicate a toggled horizontal strip of space beside the G button as a notification tray. (REFERENCE* image off reddit since I was too lazy to create one myself: https://redd.it/lebp9g)
- Here, notifications of any app will actively show up as the status bar notification icon of said app (can be placed in colour changing button like the G button)
- Tapping icon creates a pop up above notification icon, like when you swipe on a notification in the launcher; you can drag tap across the icons to seamlessly switch between notifications.
- QoL: 
   i) swiping up on notification of app opens respective app; meaning, you can view and open a notification without having to lift your finger from the screen even once.
   ii) swiping left/right on G button opens/closes the notification tray. (downside: requires G button to be enabled)

What it achieves:
- Immediately know which app the notification is from, and ability to (more) easily view said notification.
- Makes it more convenient to hide status bar
- Sticks to design language of the launcher

2. Wallpapers

Problem:
i) Placing wallpaper to align perfectly with position of app icons on favorite screen is a cumbersome trail and error process.

ii) It sucks when you have a light themed wallpaper and you look at your screen in the dark. Having a Day wallpaper and a Night wallpaper would solve that. The process of setting up a wallpaper, as mentioned above, leads to it being difficult to switch between wallpapers with ease. 

Solution:
i) When setting up a wallpaper, show a preview of how it will look with your current home screen, before you confirm its placement.

ii) Having multiple wallpapers to cycle through would be a godsend(more so if it automatically changes based on time of day)

What it achieves:
- Your wallpapers no longer hurt your eyes
- Easier to switch it up
- Automatic cycles (set it and forget it)

3. QoL suggestions
i) Ability to reduce left padding on app icons, for more flexibility with wallpapers
ii) Blur screen when opening pop ups (can be toggled on/off)
iii) Swipe between 2 home screens (like Work and Play screens)
iv) Place music player widget beside G button (if the notification tray idea isn't implemented)

**Comment by Maxr1998** [comment] 2021-11-20 17:40
Thanks for all the suggestions! Gonna go through them one by one.

**1** This is most a duplicate of #152, you can follow the updates and discussion there. The proposed UI changes seem to be quite specific and complicated, I think they would confuse most users more than they'd help.

**2 i)** Wallpaper placement should now be exactly like in the preview, if not, check out the wallpaper offset toggle in the looks section of the settings.

**2 ii)** Likely not something we'll support in the launcher, but there should be third-party apps that change your wallpaper depending on the time of day. Actually, I'm pretty sure you can even do that through KLWP with some research.

**3** Are mostly changes that are either infeasible (blurring isn't properly supported by Android still and would use too many resources if done in software, see #1674) or (in our opinion) unnecessary customization options that don't match [Niagara's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles).

Since all points should be resolved by this, I'll close this issue.

**Closed by Maxr1998** 2021-11-20 17:40 UTC
