### ISSUE TITLE
Scrollable widgets, (like widget stacks on iOS 14)

### ISSUE THREAD

**Issue by 1chrome** [8bitPit/Niagara-Issues#1423] opened 2020-11-28 09:01 UTC
I always use the TickTick todays tasks widget, but then when I don't want to see it, I prefer seeing my OnePlus clock widget. This keeps the hokeacreen clutter free and functional on demand.

If the widgets had the ability to 'scroll' like a carousel (like pages in a conventional launcher), I feel the problem with mulitple widgets might be solved (since they can be scrolled through).

Screenshots attached to illustrate the scenario better. Of thr widgets seen were in a carousel which I can scroll through, it's incredibly useful for someone who uses multiple widgets but at the same time aligns with Niagara's design principles of simplicity.

![Screenshot_20201128-142906](https://user-images.githubusercontent.com/26594470/100498145-39cc4880-3186-11eb-85f6-b5393962107a.jpg)
![Screenshot_20201128-142933](https://user-images.githubusercontent.com/26594470/100498147-3c2ea280-3186-11eb-97b1-781a853f4dde.jpg)

**Comment by Martin5001** [comment] 2020-11-28 14:07
#1330

**Comment by 8bitPit** [comment] 2020-12-07 09:28
Duplicate of #1330

**Closed by 8bitPit** 2020-12-07 09:28 UTC
