### ISSUE TITLE
Home screen refreshes with Swipe Up / Home gesture

### ISSUE THREAD

**Issue by Yipcanjo** [8bitPit/Niagara-Issues#1096] opened 2019-12-17 02:22 UTC
I'm using the full gesture navigation (including no bottom bar) on my OnePlus 7 Pro. If I'm in an app and swipe up (from the bottom) to get back to the home screen, Niagara Launcher is blank for a moment and appears to refresh/re-launch itself. If I'm in an app and swipe from the side (to go back to home), the home screen is visible immediately.  It's almost as-if the Niagara Launcher is crashing and re-launching when swiping up from the bottom for the Home gesture.

(screen recorder .zip attached)

 - Device: OnePlus 7 Pro
 - Android version: Android 10, Dec Update
 - Niagara: version 0.10.3

[19-12-16-16-00-37.zip](https://github.com/8bitPit/Niagara-Issues/files/3971130/19-12-16-16-00-37.zip)

**Comment by Montell2099** [comment] 2019-12-17 14:51
When I go to Launcher Settings -> Advanced -> Restart launcher, the apps fade in and slide down slightly from below where the clock is located. Your apps doesn't seem to do this, are you sure it's not some kind of transition animation caused by your phone? I'm just guessing.

If you activate the new weather "widget", does it slide in from the left every time when you swipe up from an app to go home?

What screen recording software are you using by the way?

**Comment by Yipcanjo** [comment] 2019-12-17 19:21
That screen recording feature is built-in to the OnePlus, actually. Pretty damned handy.

Good comments about the animation(s). It may be exactly that. I bumped back to the OnePlus stock launcher this morning to test again, and for sure the behavior is different between going Home via a swipe-up and going Home via a back gesture.  The swipe-up Home gesture appears to want to shrink the app down to a square and disappear onto the Home screen, whereas the Back gesture is basic and very fast.

By the way, my "restart launcher" behavior is the same as yours.

**Comment by 8bitPit** [comment] 2019-12-19 17:06
Hi @Yipcanjo, I believe this is because gestures on third party launchers are handled differently than on the preinstalled launcher. That's because the preinstalled launcher has the permission to provide the recents screen itself, therefore it can support smoother animations. I think you should be able to replicate the same fade animations on other third-party launchers, like Nova or Lawnchair.

**Comment by Yipcanjo** [comment] 2019-12-19 19:02
You are absolutely correct. I tested another third-party launcher and the result was identical.

Thank you for clearing that up for me. Sorry for the fire drill....

**Comment by 8bitPit** [comment] 2019-12-19 19:15
Haha, no problem :) I'll close this issue then if you don't mind.

**Closed by 8bitPit** 2019-12-19 19:15 UTC
Labels: bug
