### ISSUE TITLE
Users should be able to choose if App List shows app at the Top, Middle, or Bottom of the screen. 

### ISSUE THREAD

**Issue by sid32** [8bitPit/Niagara-Issues#1426] opened 2020-12-02 15:46 UTC
My finger usually ends up in the middle of the screen, so I would like the Letter List of apps to appear in the middle of the screen. But I know that some people like them at the top and bottom as well.

**Comment by 8bitPit** [comment] 2020-12-08 20:29
Thanks for your suggestion @sid32. To better plan ahead and give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that are unlikely to be implemented in the next year (2021). This is one of those, unfortunately: https://github.com/8bitPit/Niagara-Issues/issues/869

**Comment by 8bitPit** [comment] 2020-12-08 20:29
Duplicate of #869

**Closed by 8bitPit** 2020-12-08 20:29 UTC
