### ISSUE TITLE
Can't change margins without an active widget

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1068] opened 2019-12-01 21:32 UTC
Without any active widget you cannot change the margins by tapping & holding any more — only by scrolling to the bottom of the edit mode and choosing "move entire list". But that only affects the top-margin, not the margin between weather data and the app list.

Also, the weather prediction for the last displayed hour is cut off by a tiny bit:
![Screenshot_20191201-222333](https://user-images.githubusercontent.com/43126233/69920581-12b33c00-148a-11ea-866e-a6ab9e7b80e3.png)

**Comment by 8bitPit** [comment] 2019-12-01 21:50
> But that only affects the top-margin, not the margin between weather data and the app list.

I believe this is a duplicate of: https://github.com/8bitPit/Niagara-Issues/issues/951

> Also, the weather prediction for the last displayed hour is cut off by a tiny bit

This is not intended, but I don't know if it's better without it. The way that it is cutoff gives you a hint that you can scroll horizontally. Google Play also does that, for example.

**Comment by Montell2099** [comment] 2019-12-01 21:54
> This is not intended, but I don't know if it's better without it. The way that it is cutoff gives you a hint that you can scroll horizontally. Google Play also does that, for example.

I actually didn't realize it was scrollable by the cut-off, just randomly played around and found out. Some kind of small fade-out might be an idea.

**Comment by 8bitPit** [comment] 2019-12-01 22:01
Thanks for the idea, will also try that!

**Closed** 2019-12-02 08:13 UTC
Labels: bug
