### ISSUE TITLE
Allow movement of alphabet/list to the left

### ISSUE THREAD

**Issue by StarrKiss** [8bitPit/Niagara-Issues#1013] opened 2019-10-04 18:34 UTC
Currently it is on the right, which is annoying when using the phone with one hand. It would be really convenient if it would be possible to move the list to the left.

**Comment by Martin5001** [comment] 2019-10-04 18:54
This would make sense as Niagara's Play store description says you can scroll using both left and right hand. (Which is indeed true even at this time, but it is not so obvious that you can scroll on the area without the alphabet too.)

**Comment by 8bitPit** [comment] 2019-10-06 20:00
Duplicate of #12

**Closed by 8bitPit** 2019-10-06 20:00 UTC
Labels: duplicate
