### ISSUE TITLE
First touch after returning from app not working

### ISSUE THREAD

**Issue by henriquearthur** [8bitPit/Niagara-Issues#1871] opened 2022-03-06 14:34 UTC
### Describe the bug

When I open an app and then return to Niagara the first touch on the screen does not work. If I open app A then return to Niagara using gestures when I try to open app B does not work. If I click again then it works.

It doesn't have to be a different app, it can be the same or a click on the widget or try to open search. No action works on first touch. It does not happen with stock launcher.

### Steps to reproduce

1. Go to Niagara home screen
2. Open any app
3. Return to Niagara
4. Try to open another app or touch the widget or floating button. Doesn't work on first touch.

### Device name

Samsung Galaxy S21

### Android version

Android 12

**Comment by Oddward** [comment] 2022-03-22 13:38
Did this problem only start from a specific version of Niagara? Or suddenly without updating the app? Have you tried reinstalling or installing a different version to see if the problem exists then?

**Comment by Oddward** [comment] 2022-03-22 18:33
If I remember correctly, when Google first came out with a smooth app-closing animation for gesture navigation on the Pixel it had a bug on Niagara/3rd party launchers where if a user touched the screen before the animation was complete it would cause the app's icon to permanently freeze on the screen until they restarted Niagara. Since Niagara couldn't do anything about the animation API's bug I believe they added a short delay for registering touches to prevent that animation freezing, although it shouldn't be as long as 2 seconds I think. 

The animation would eventually become available to other OEMs, if they wanted to support it, and I believe Samsung has it now and that might be why there's a short delay before you can interact with Niagara. It was the only workaround for a weird annoying bug. 

I'll get confirmation if this is the case & update here

**Comment by Oddward** [comment] 2022-03-25 13:26
Can you check if your issue is reproducible on other 3rd party launchers (e.g. Nova, Microsoft)?

**Comment by henriquearthur** [comment] 2022-03-25 21:35
@Oddward yes, I can reproduce on Nova

**Comment by Maxr1998** [comment] 2022-04-08 16:10
Thanks for the reply. This is indeed a known issue with the system navigation gestures, and unfortunately not something we can fix. The issue you're reporting is likely related to [these](https://issuetracker.google.com/issues/194427611) [two](https://issuetracker.google.com/issues/202864574) issues that we reported to Google. We hope this will be fixed in an upcoming Android version. For now, there is nothing you could do, really, except switch from navigation gestures to three-button navigation, unfortunately.

**Closed** 2022-04-08 20:38 UTC
Labels: bug, blocked

**Comment by Oddward** [comment] 2022-04-17 22:48
p.s. @henriquearthur if your device has two options for gesture navigation between _Swipe from bottom_ and _Swipe from sides and bottom_ and it's set to the latter, try setting it to the 1st one, this seems to have improved this experience for a user with a similar issue. 

### Swipe gestures settings:
- [x] Swipe from bottom   _< use this_
- [ ] Swipe from sides and bottom

**Comment by Octavio-M** [comment] 2023-06-27 01:16
Hi. This is happening again since the last update 1.9.9. I don't use gestures tho.

**Comment by Amorphous404** [comment] 2023-07-07 08:52
> Hi. This is happening again since the last update (1.9.9). I don't use gestures tho.

Are you referring to the app launches or the home button to Niagara search?
