### ISSUE TITLE
Swipe action text wrapping (reminder)

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1025] opened 2019-10-20 16:38 UTC
I noticed that you made some polishing (rubber effect, app list animation – this one looks quite nice btw.), and I don't want to submit duplicates but I think a little reminder might be good at this point...

Could you please change the contacts names shortcuts shown on swipe to use the longer text, same as on phone app, so it wouldn't wrap with "..." when there is actually enough space for the full text to fit in?

Thank you and I hope I am not too annoying with this :)

**Comment by Montell2099** [comment] 2019-10-20 17:48
I agree, there's more than enough space to display the full contact names as shown in this screenshot below:

![Screenshot_20191020-194612](https://user-images.githubusercontent.com/43126233/67163707-8f72d680-f372-11e9-9d41-d80edf7f26fa.png)

**Comment by 8bitPit** [comment] 2019-10-21 10:11
Technically this is a "bug" caused by Google's contacts app. Names should be ellipsized by the launcher, not by the app itself. However, I could fix it, but I'm not sure if some shortcut names would unnecessary long afterwards, I have to test that.

**Comment by 8bitPit** [comment] 2019-11-11 14:12
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/983

**Closed by 8bitPit** 2019-11-11 14:12 UTC
