### ISSUE TITLE
Number of favourites seems limited in 0.10.4

### ISSUE THREAD

**Issue by folkg** [8bitPit/Niagara-Issues#1095] opened 2019-12-17 00:14 UTC
Since 0.10.4, the number of favourites showing up on my homescreen has slowly reduced from 8 to 4. I haven't been using the apps any less, in fact I've been trying to get some apps to show up in the favourites again by opening them a bunch of times, but it is not working. This seems like a new bug to me as it is new, strange behaviour.

**Comment by 8bitPit** [comment] 2019-12-19 15:00
That's weird, I still have eight suggestions and didn't touch the usage algorithm.

**Comment by folkg** [comment] 2019-12-19 16:20
It could be totally unrelated to the version 0.10.4 then, it may have been coincidence, but the behaviour I'm is still the same. I've been using it for a while and the number of displayed favourites has now comes to 5, but lower than the 8 I'm used to. I'm not sure if that is normal behaviour.

**Comment by OEssHRERLr770rGGLOH0** [comment] 2020-02-02 19:54
I'm experiencing something similar I think where the list will gradually increase in number with usage but at one point some will start disappearing. 

So for example, my list is stuck with 6 icons right now but used to be longer. 

Just to be clear on behavior: once the list is automatically generated (is it 8 apps total?), it should not shrink down even if some apps on the list are getting used less. These should be replaced by apps that are getting use more frequently, correct? Thanks!

**Comment by 8bitPit** [comment] 2020-02-02 19:59
@OEssHRERLr770rGGLOH0 this happens because apps need to surpass a certain threshold. That's why apps that are used too infrequently don't show up at all.

**Comment by OEssHRERLr770rGGLOH0** [comment] 2020-02-02 20:14
> @OEssHRERLr770rGGLOH0 this happens because apps need to surpass a certain threshold. That's why apps that are used too infrequently don't show up at all.

I see. I suppose I don't use my phone enough. ;) Would you then consider tweaking this behavior for people like me who may not use the phone enough to fill the list? Thanks!

**Comment by 8bitPit** [comment] 2020-02-02 20:27
@OEssHRERLr770rGGLOH0 I think you may like this then: https://github.com/8bitPit/Niagara-Issues/issues/454

**Comment by 8bitPit** [comment] 2020-03-01 18:11
After some testing, I couldn't find any errors in the algorithm. It works fine on my side. No one else has reported this either, so I'm closing this. But feel free to open it again in case it's not working as intended.

**Closed by 8bitPit** 2020-03-01 18:11 UTC
Labels: bug

**Comment by OEssHRERLr770rGGLOH0** [comment] 2020-05-17 17:50
Why has this been closed? Is there any plan to tweak the algorithm so that people who aren't constantly using their phones still have the app list filled with at least a certain number of apps? Thanks!

**Comment by 8bitPit** [comment] 2020-06-01 18:11
@OEssHRERLr770rGGLOH0 that's under consideration: https://github.com/8bitPit/Niagara-Issues/issues/454

**Comment by OEssHRERLr770rGGLOH0** [comment] 2020-06-03 02:50
> @OEssHRERLr770rGGLOH0 that's under consideration: #454

Oops, must have missed it, sorry. Thank you!!

**Comment by 8bitPit** [comment] 2020-06-03 12:40
no problem :)
