### ISSUE TITLE
Notifications preview not working on Motorola g84

### ISSUE THREAD

**Issue by hardenheavy** [8bitPit/Niagara-Issues#2885] opened 2024-09-06 08:40 UTC
### Describe the bug

Notifications preview isn't working. Works for a bit and stopped. Nothing fixes it. All permissions are allowed. I even reinstalled Niagara from scratch. 

### Steps to reproduce

Any notification... Outlook, WhatsApp etc. 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Motorola g84 5G

### Android version

Android 14

**Comment by contact-maximux** [comment] 2024-09-06 15:40
Is there any notification app installed? motorola notification app?

**Comment by hardenheavy** [comment] 2024-09-06 16:21
> Is there any notification app installed? motorola notification app?

Nothing except what's stock on the phone. 

![Screenshot_20240906-182054](https://github.com/user-attachments/assets/75cbf529-cc14-4a66-9742-fbf27c8f19ea)

**Comment by contact-maximux** [comment] 2024-09-07 05:07
I can not test, but If you getting notification dots in other launcher, you must get in niagra also, Else its BUG

**Comment by hardenheavy** [comment] 2024-09-07 05:15
> I can not test, but If you getting notification dots in other launcher, you must get in niagra also, Else its BUG

Even that's inconsistent. For example, at thw moment I have dots on google apps (gmail, google etc) but none on Outlook, WhatsApp, Discord etc.

As for Niagara preview, it worked properlynfor half a day after I started using this phone then it stopped and no matter what I do it's not working now.

**Comment by contact-maximux** [comment] 2024-09-09 13:47
mystery :)

**Comment by NiagaraSupport** [comment] 2024-09-11 13:26
Hey there, thanks for the report. I'll close this as a presumed duplicate of #2347 and address it to the rest of the team again.

**Closed by NiagaraSupport** 2024-09-11 13:26 UTC
Labels: bug
