### ISSUE TITLE
[Feature Request] Show today's high/low temp in the Agenda view

### ISSUE THREAD

**Issue by Nxt3** [8bitPit/Niagara-Issues#1739] opened 2021-10-27 03:15 UTC
Would be nice to be able to view the current day's high/low at a glance in the Agenda view. 🙏

![Screenshot_20211026-230905~2.png](https://user-images.githubusercontent.com/2940826/138994021-d486730d-8487-4dee-a8b1-efcafa74056a.png)

**Comment by Maxr1998** [comment] 2021-11-05 11:35
I've talked about this with Peter again, according to him, only showing high/low (and not the weather condition) would look even weirder, and people might report that the icon is missing. Thus, we don't show the average data for "today" at all.

I'll mark this as "won't fix" and close it for now since it is intended behavior, if we change our minds we'll update this issue.

**Closed** 2021-11-05 11:35 UTC
Labels: wontfix
