### ISSUE TITLE
Cannot Change Order of favourites because of scrolling 

### ISSUE THREAD

**Issue by knuthie** [8bitPit/Niagara-Issues#2168] opened 2023-01-02 16:48 UTC
### Describe the bug

First: I have added a kwgt Widget.
Second: trying to modify the favourites Order.
Thus when modifying the favourites, the top section Always Shows a list of multiple kwgt Options ( 4*2,2*2, etc)
Then when trying to Change the Order of the App. Favourites , suddenly the list Starts to scroll in such a Speed that it is Impossible to really place a favourites at the desired place.

### Steps to reproduce

See above

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 4a 5g

### Android version

Android 13

**Comment by Amorphous404** [comment] 2023-01-02 17:32
Duplicate of #1660

**Closed** 2023-01-02 17:32 UTC
Labels: bug, duplicate
