### ISSUE TITLE
Option to disable side bottom to top swipe

### ISSUE THREAD

**Issue by bdOtopsy63** [8bitPit/Niagara-Issues#2301] opened 2023-06-08 21:25 UTC
### Is your feature request related to a problem?

Please add an option to disable left or right side swipe from top to bottom and inverse at user choice (for exemple I would like to disable left side swipe to move in apps to have another gesture) 😊
In advance thanks a lot and by the way what a beautiful launcher (owner of pro here 🤘🏼)

### Describe the solution you'd like

Two toggles in menu to disable swipe left or swipe right at user choice please 🙏🏼 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-06-13 17:35
Hi, @bdOtopsy63, thank you for your suggestion. The alphabet scroller is an integral part of the launcher, designed with one-handed usage in mind. It allows users to access the app list easily and also benefits left-handed users without requiring an additional toggle in the settings.

We have already had extensive discussions regarding this feature, and our consensus is that adding an option to deactivate it would make Niagara less intuitive. Furthermore, we do not believe an option to disable the scroller will have a [significant impact](https://help.niagaralauncher.app/article/8-niagaras-design-principles).

If you would like to engage in further discussion, we encourage you to participate in the existing issue.
- See: #865

Thank you for your understanding.

**Comment by Amorphous404** [comment] 2023-06-13 17:36
- Duplicate of #865

**Closed** 2023-06-13 17:36 UTC
