### ISSUE TITLE
Minimalist primary screen

### ISSUE THREAD

**Issue by franciscoD96** [8bitPit/Niagara-Issues#697] opened 2019-01-07 17:19 UTC
how about a minimalist primary screen with no favorites nor most used apps, just the top block, future widgets, and the ability to get to the apps from the slider? that would be nice :)

**Comment by 8bitPit** [comment] 2019-01-08 10:13
Widgets below the clock can be added in the future. Then you would only have to remove your favorites and enable the "limit most used apps" toggle.

**Comment by franciscoD96** [comment] 2019-01-08 11:48
i tried it, but it always shows exactly 2 apps, plus the favorites I would add.
perfect would be to disable the most used apps :)

**Comment by 8bitPit** [comment] 2019-01-08 21:17
If they still show up, you can hide them manually by long pressing them and tapping "Stop suggesting". Hope that helps.

**Comment by 8bitPit** [comment] 2019-03-06 16:40
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/224

**Closed by 8bitPit** 2019-03-06 16:40 UTC
