### ISSUE TITLE
Show full moon date in calendar popup

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1580] opened 2021-04-28 16:44 UTC
I think it would be useful to show when there will be a full moon, similarly to how sunset/sunrise is shown. (I'd understand if you decide to not add this feature, but if there's data available for this you could use, I think it would be worth adding this.)

**Comment by Just-SKY** [comment] 2021-04-29 01:25
I like the idea, it'd be a very nice touch and kind of usefull for many people; also I think isn't intrusive at all. For example,  I love gardening,  and always have to search when the full is un order to prune them. 
It also add more funtionality and attractiveness  without disturbing the weather widget.

**Comment by 8bitPit** [comment] 2021-05-14 10:30
While OpenWeather would provide the current moon phase, I see this more as a gimmicky and less functional feature and wouldn't close this issue for now because of its low priority.

**Closed** 2021-07-12 15:10 UTC

**Comment by Oddward** [comment] 2021-07-15 11:21
> While OpenWeather would provide the current moon phase, I see this more as a gimmicky and less functional feature and wouldn't close this issue for now because of its low priority.

Actually, in a lot of cultures which use a lunar calendar this would be a fantastic feature. Many cultural and religious holidays & events rely on the moon phase, and usually there are groups who watch the moon phase to report the new month of the lunar calendar for e.g. 🤔

It may be low priority still coz the dates of the full/new moon for e.g. sometimes need to be confirmed on that day anyway and are announced as their Gregorian counterpart, but it might still be useful

If it did show it could exist in the event list
