### ISSUE TITLE
Niagara Media Player Navigation Slider

### ISSUE THREAD

**Issue by GrayGames** [8bitPit/Niagara-Issues#1343] opened 2020-08-05 04:33 UTC
Would it be possible to add a bar beneath the Niagara media player so we can skip ahead in videos and songs within the home screen? This would be super helpful to have just as an option in settings!

**Comment by 8bitPit** [comment] 2020-08-05 16:36
Hi @GrayGames, I believe this is a duplicate of https://github.com/8bitPit/Niagara-Issues/issues/973

**Comment by 8bitPit** [comment] 2020-08-05 16:37
Duplicate of #973

**Closed by 8bitPit** 2020-08-05 16:37 UTC
Labels: duplicate
