### ISSUE TITLE
[Request] Next alarm at a glance

### ISSUE THREAD

**Issue by TranQuan123** [8bitPit/Niagara-Issues#2058] opened 2022-09-17 14:58 UTC
I want to request a feature that the next alarm will show at a glance, so i don't have to open the clock to see the alarm anymore

**Comment by bastschonet** [comment] 2022-09-20 00:05
+1

**Comment by tjsuominen** [comment] 2022-09-20 11:55
+1

**Comment by topsy-turvy99** [comment] 2022-09-22 21:35
Duplicate of #4

**Closed** 2022-09-24 21:09 UTC
