### ISSUE TITLE
Swipe down for notifications drawer wobbles apps

### ISSUE THREAD

**Issue by awnumar** [8bitPit/Niagara-Issues#1225] opened 2020-03-20 18:11 UTC
Swiping down for the notifications drawer causes the apps on the home screen to go down with your finger and bounce back before the notification drawer comes down. This makes the experience feel sluggish.

**Comment by 8bitPit** [comment] 2020-03-20 19:10
Hi, I believe this is a duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1022

**Closed by 8bitPit** 2020-03-20 19:10 UTC
Labels: duplicate
