### ISSUE TITLE
Icon customization

### ISSUE THREAD

**Issue by josh1244** [8bitPit/Niagara-Issues#1029] opened 2019-10-23 01:01 UTC
I really like how this laumcher is super simple and customizable at the same time. I like how you can choose any Icon from any icon pack. I think it would be great if you could also choose from .png files that you out in a specific folder to use as icons. I want this because custom icons would be cool and I have some icons from and iOS anemone theme and want to use it with this launch but Android refuses to let me make an icon pack and install it. So adding PNG from a folder would be great! Thanks for the great launcher!

**Comment by 8bitPit** [comment] 2019-10-23 12:55
Thanks for your kind words :)
I believe your request is similar to #581, right?

**Comment by 8bitPit** [comment] 2019-10-23 15:10
Great, I'll close this issue then and leave the other one open.

**Comment by 8bitPit** [comment] 2019-10-23 15:10
Duplicate of #581

**Closed by 8bitPit** 2019-10-23 15:10 UTC
