### ISSUE TITLE
Status bar and navigation bar

### ISSUE THREAD

**Issue by nagarajtg** [8bitPit/Niagara-Issues#2191] opened 2023-02-02 19:11 UTC
### Is your feature request related to a problem?

It would be wonderful to add an extra feature to immediately hide status bar and navigation bar when we go to homescreen, there is already have an option to hide status bar with fading out but having given time will be awesome to, just an extra option!

### Describe the solution you'd like

Adding an toogle button to hide navigation bar, and with extra option for timing of fade out or immediate turn off when go to homescreen

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by nagarajtg** [comment] 2023-02-02 19:12
This is not a problem overcome, just an additional option to implement on the launcher

**Comment by Amorphous404** [comment] 2023-02-03 01:49
Sorry, we intentionally added the fade animation to the status bar after many users requested it and don't have plans to change this behaviour or add an option around the same 
See: [Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)

About the option to hide the navigation bar, we think that's something, a system should provide natively in the system settings.

Also duplicate of
https://github.com/8bitPit/Niagara-Issues/issues/43

**Closed** 2023-02-03 01:49 UTC
