### ISSUE TITLE
[Feature Request] An option to hide apps' icons

### ISSUE THREAD

**Issue by hassandayem** [8bitPit/Niagara-Issues#1337] opened 2020-08-01 10:19 UTC
It would be great to add such a feature, this can make it more clean and particularly for those who love to focus on launcher's typography.

**Comment by Chaupeter** [comment] 2020-08-03 07:32
I made this request quite some time ago and there I second this request.

**Comment by Rod911** [comment] 2020-08-27 21:03
You can leave your suggestions and requests in the linked ticket.
Duplicate of #140

**Closed by Rod911** 2020-08-27 21:03 UTC
Labels: duplicate
