### ISSUE TITLE
App bar activation too high

### ISSUE THREAD

**Issue by spookymyo** [8bitPit/Niagara-Issues#1548] opened 2021-03-20 22:50 UTC
I think the app bar on the right and left sides is activated too far up. I use kwgt to make a custom widget that I put in place of the clock. The widget has touch points on the far right and left that can't be pressed because the app bar is in the way. Could you maybe add a setting to change the activation zone of the app bar?

**Comment by Martin5001** [comment] 2021-03-21 10:03
Or maybe rather than adding a toggle, it should be changed automatically if a custom widget is added.

**Comment by 8bitPit** [comment] 2021-03-26 12:15
Hi @spookymyo, I'm sorry but we're not planning to add a workaround for that.  The alphabet takes precedence over the widget to keep your app list easily accessible, disregarding the widget's size and position. If the widget has clickable buttons on its edges, I recommend disabling the "fill screen" mode.

**Comment by 8bitPit** [comment] 2021-03-26 12:15
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1525

**Closed by 8bitPit** 2021-03-26 12:15 UTC
