### ISSUE TITLE
Notifications stop working after launcher restart

### ISSUE THREAD

**Issue by Rapahannock** [8bitPit/Niagara-Issues#588] opened 2018-11-20 00:52 UTC
There appears to be a bug in the resetting of the launcher. After resetting the launcher, notification icons and the media widget no longer appear. You'd have to either restart the device, or (more ideally) go into settings then disallow and re-allow Niagara access to notifications. If the launcher is slow to launch when pressing the home button after doing the above, you'd have to clear all or the offending notification. 

I only noticed this today, after having to reset the app. Which is rare. 

Asus Zenfone AR - Not rooted

**Comment by maracuja-juice** [comment] 2018-11-20 10:42
Re-Allowing access to the notifications didn't help for me (One Plus 3T)

**Comment by berdzena** [comment] 2018-11-20 12:06
Try to restart launcher

**Comment by 8bitPit** [comment] 2018-11-20 20:56
Yeah, I've got a lot of reports that notifications are not showing up after updating/restarting the launcher (media player is using the notification listener as well). Not that easy to fix, because I cannot reproduce it on my phone (Essential phone), I will try my best next week though.

**Comment by Rod911** [comment] 2018-12-14 17:53
It seems that devices not running stock android have problems with notifications. Can anyone confirm?

**Comment by 8bitPit** [comment] 2019-02-15 19:52
Almost all devices are using Huaweis/Xiaomis EMUI/MIUI  which run into that problem. It seems that they kill background processes like the notification listener service aggressively. One user on Telegram (Sean) linked me this site:  https://dontkillmyapp.com

**Comment by disacrol** [comment] 2019-03-01 20:23
It's a bummer Nokia is right there on top, being all in with Android One devices... Isn't there anything Niagara can do about this? Some workaround top make sure that listener is not killed.

**Comment by 8bitPit** [comment] 2019-03-05 12:51
@disacrol I don't know. Maybe other launcher devs know to deal with this.

**Comment by 8bitPit** [comment] 2019-05-03 13:06
Niagara will show a warning if notifications stopped showing up. Here's more info (from the 0.7.8 update log):

As you may have noticed, 0.7.8a’s workaround for notifications didn’t really help, it even made them not showing up on unaffected devices. That’s why I removed it and tried something else instead. 
Looking at open issues online, it seems that every other Launcher has to deal with the same - more than four years old - issue which some still hasn’t been fixed by various phone manufacturers ;(
If notifications broke only in 0.7.8a for you, they might not work again either on 0.7,8a3 because of the reversal until you revoke and re-grant notification access. At least Niagara will now inform you if the third workaround is not working as well and gives you suggestions how to fix it locally. 

I'm afraid I can't do more, I'll close the issue for now.

**Closed by 8bitPit** 2019-05-03 13:06 UTC
Labels: bug

**Comment by swooned** [comment] 2020-04-24 20:58
I've noticed that my notifications for Messenger and WeChat are not showing in the top left corner when they happen. I can't figure out why but it could be something that is affecting those apps specifically. It works for a bit and then it stops. Interestingly this is been happening when I've been updating Niagara launcher..

**Comment by 8bitPit** [comment] 2020-04-25 21:50
So, the icons don't show up in Android's status bar at the top? This is not caused by Niagara Launcher then. Maybe this guide helps: https://niagaralauncher.helpscoutdocs.com/article/31-notifications-not-showing

**Comment by swooned** [comment] 2020-04-25 21:58
Thanks, man.With gratitude,Frederick Malouf@ S W O O N D R O N E SP O   B o x   7 4 3 4B o n d i   B e a c h   N S W   2 0 2 6A U S T R A L I A+ 6 1   4 0 3   9 9 3   6 9 9How would I define myself? That’s like asking the definition of infinity …..
-------- Original message --------From: Peter Huber <notifications@github.com> Date: 26/4/20  07:50  (GMT+10:00) To: 8bitPit/Niagara-Issues <Niagara-Issues@noreply.github.com> Cc: swooned <swooned@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [8bitPit/Niagara-Issues] Notifications stop working after launcher restart (#588) 
So, the icons don't show up in Android's status bar at the top? This is not caused by Niagara Launcher then. Maybe this guide helps: https://niagaralauncher.helpscoutdocs.com/article/31-notifications-not-showing

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/8bitPit/Niagara-Issues/issues/588#issuecomment-619445426",
"url": "https://github.com/8bitPit/Niagara-Issues/issues/588#issuecomment-619445426",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
