### ISSUE TITLE
Steps & calendar

### ISSUE THREAD

**Issue by Wtreck** [8bitPit/Niagara-Issues#1189] opened 2020-02-18 19:33 UTC
It would be very cool if you could display **upcoming calendar events** and **appointments** as well as the **steps** on the start screen, as appropriate widgets destroy the minimalist design.
#543 #ux #ui

**Comment by Wtreck** [comment] 2020-02-19 12:30
#543 #ux #ui

**Comment by 8bitPit** [comment] 2020-02-25 19:01
I'm happy to tell you that this is likely to be implemented: https://github.com/8bitPit/Niagara-Issues/issues/55

**Comment by 8bitPit** [comment] 2020-02-25 19:01
Duplicate of #55

**Closed by 8bitPit** 2020-02-25 19:01 UTC
