### ISSUE TITLE
Continual alpahetic list when scrolling via side bar? 

### ISSUE THREAD

**Issue by ascended1** [8bitPit/Niagara-Issues#1065] opened 2019-11-27 00:02 UTC
Option to see your  app list when you scroll using the side bar. As it is now you only see the apps of the corresponding letter. 

I know it would be way less "clean", but it would speed up things a lot. But that's why I want it as an option.

**Comment by 8bitPit** [comment] 2019-11-29 19:01
Hey again. Unfortunately, this feature has a very low priority. That's why [the corresponding issue](https://github.com/8bitPit/Niagara-Issues/issues/26) is currently closed at least until 2021. Sorry.

**Comment by 8bitPit** [comment] 2019-11-29 19:01
Duplicate of #26

**Closed by 8bitPit** 2019-11-29 19:01 UTC
Labels: duplicate
