### ISSUE TITLE
Lag when returning to the home screen

### ISSUE THREAD

**Issue by magnitomania** [8bitPit/Niagara-Issues#2675] opened 2024-05-04 08:38 UTC
### Describe the bug

When returning to the home screen, the icons/homeapp take too long to load. This is happening on Oneplus Open, haven't noticed this on my previous foldable (Samsung Z Fold 4). Also sometimes it does not load at all after unlocking the phone, unless I use back or home button explicitly (couldn't catch this one on recording)

### Steps to reproduce

1. Go to any app.
2. Return to home screen

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Other 3rd-party launcher(s) tested

Microsoft Launcher

### Device name

Oneplus Open

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/25350180/3301f9ae-37c3-4582-8658-de734d76ad78

**Comment by jwalkingjon** [comment] 2024-05-11 18:15
Same exact issue here - back gesture works fine but going home lags for 1-2 seconds

**Comment by NiagaraSupport** [comment] 2024-05-15 11:10
Hey there, thanks for the report.
I'll close this as a duplicate of #2658.

**Closed by NiagaraSupport** 2024-05-15 11:10 UTC
Labels: bug

**Comment by juanchodrd** [comment] 2025-04-27 15:06
Will this bug ever be fixed? The same thing is happening to me on the OnePlus 12.
