### ISSUE TITLE
Quick lock gesture permissions removed

### ISSUE THREAD

**Issue by rakshitsm** [8bitPit/Niagara-Issues#2169] opened 2023-01-05 03:21 UTC
### Describe the bug

Every day accessibility permissions getting removed from my phone for niagara launcher and everytime I need to give permissions again. So making quick lock gesture stop work everyday. 

I do restart my phone everyday

Phone model: iqoo Neo 6

### Steps to reproduce

1. Go to quick lock gesture and click
2. It wil ask for permissions in accessibility service.
3. Repeats everyday

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Iqoo Neo 6

### Android version

Android 13

### Screenshots / Screen recordings

![Screenshot_20230105_083337](https://user-images.githubusercontent.com/53271422/210694371-dcc4037a-0881-4734-b01a-45d8160436bc.jpg)

**Comment by Amorphous404** [comment] 2023-01-17 10:56
Hey, Unfortunately some roms like FuntouchOS seem to aggressively kill the apps in background or remove app permissions to save battery, however you fix the issue by granting the required permission by following this guide:

https://dontkillmyapp.com/

**Comment by Amorphous404** [comment] 2023-01-17 13:04
Duplicate of #2099

**Closed** 2023-01-17 13:05 UTC
Labels: bug, duplicate
