### ISSUE TITLE
Features For Unthemed Icons!

### ISSUE THREAD

**Issue by Hexoline** [8bitPit/Niagara-Issues#1955] opened 2022-05-08 17:02 UTC
Hi , as a Developer of Icon Pack , some of my users have missing features thats available in other Launcher like Nova Launcher about the Icon Masking , Icon Shade and Force Icon Shape , these 3 features for the unthemed icons are very good to have inside the Niagara launcher , not activated by default , but by users would be very good. Thanks!

_Originally posted by @Hexoline in https://github.com/8bitPit/Niagara-Issues/issues/1820#issuecomment-1120452184_

**Comment by Oddward** [comment] 2022-05-12 18:12
Could this request be related to issue #1800 ? It seems there are plans to improve icon support with Android 13 opening up Material You icon APIs later. Atm there's limited support for dynamic icons like the Pix Material You icons

**Comment by topsy-turvy99** [comment] 2022-05-12 18:17
> Could this request be related to issue #1800 ? It seems there are plans to improve icon support with Android 13 opening up Material You icon APIs later. Atm there's limited support for dynamic icons like the Pix Material You icons

Nope, not dynamic icons, adaptive means force reshaping of icons, and an option to turn of icon making etc

![Screenshot_20220512-234738_Nova7.png](https://user-images.githubusercontent.com/96917972/168142183-a98d9993-9099-4227-ae51-e3598621041b.png)

**Comment by topsy-turvy99** [comment] 2022-05-12 19:43
> there was already a response in the issue OP linked, I think you could keep the discussion in that issue if you have a case to make and request reopening it, there are a lot of separate issue just for icon theming already. Seems like the amount of request would end up with half the appearance settings being for icons 😅 

I bet someone will even reopen it 😅, you guys are too fast at closing the issue

Nova launcher screenshot was just for clarification since you related it to dynamic icons, 

There a quite lot of space for adding two toggles, these are a must two option any launcher should have,

1) auto making on/off
2) force reshape  on/off


![Screenshot_20220513-010836_Niagara Launcher.png](https://user-images.githubusercontent.com/96917972/168155700-9e9e8938-ed57-4d4f-9a71-cb247175b83d.png)

**Comment by topsy-turvy99** [comment] 2022-05-22 13:57
@Oddward

Since we are discussing about the icons, I'm not opening a separate ticket, idk if this a bug, but Niagara make use of one random icon mask for all the non supported icons instead of making use of all the others like the other launcher.


From This It Only Uses The Last Row 3rd Icon
![Screenshot_20220522-191832_MicoPacks.png](https://user-images.githubusercontent.com/96917972/169698499-1d243d73-61cb-4707-a9d7-d76ec6f21c23.png)
----------------------------------------------------------
Here From Second Row 1st Icon
![Screenshot_20220522-191915_MicoPacks.png](https://user-images.githubusercontent.com/96917972/169698509-4c8e0d20-c344-497c-b57a-a8b5a0858334.png)

**Comment by Oddward** [comment] 2022-05-26 11:01
@topsy-turvy99 hmm ya this seems like a recent issue, I used to use RedlineX on an older device and it had dynamic theming, now tried it again after a while on a new one and I only see one mask being applied for unthemed icons instead of a variety of them. Since this is a bug rather than part of the request for theming features it could have its own issue

**Comment by topsy-turvy99** [comment] 2022-05-26 11:29
Okay, i wasn't sure if it was a bug, now it confirmed, should i open a separate ticket?

**Comment by TFackler** [comment] 2022-06-03 16:32
@topsy-turvy99 
Next time please do open a new issue when you notice something not originally mentioned by OP ;)

This is a known issue and has already been fixed. The fix will be included in the next major update 👍

**Comment by TFackler** [comment] 2022-06-03 16:37
@Hexoline sadly I do not quite understand what features you would like us to add. 

Icon masking using the Icon pack's masks automatically happens and use different masks (if applicable) starting with the next major update.

Could you clarify what you are talking about when referring to "forcing icon shape" and "icon shade"? Are you talking about adding a background to app icons not supported by the current icon pack?

**Comment by Hexoline** [comment] 2022-06-03 18:20
**"forcing icon shape"**
I mean for icons that are shapeless to have the same background shape as the icons included in the icon packs like circle , squircle , we as developers include the background shape for unthemed icons and for the adaptive icon packs will be awesome to have also a force to have all the same shape of the background.

**Comment by 8bitPit** [comment] 2022-06-04 05:59
Sorry, this ticket was closed by accident, I'll reopen it

**Comment by 8bitPit** [comment] 2022-06-04 06:16
well

**Closed** 2022-07-16 15:10 UTC
Labels: awaiting-response, wontfix
