### ISSUE TITLE
Web search using text to search

### ISSUE THREAD

**Issue by GeekLiberty** [8bitPit/Niagara-Issues#1183] opened 2020-02-14 20:30 UTC
**Is your feature request related to a problem? Please describe.**

I feel like the functionality of Niagara's text based search menu is limited. I'd like to use it for more than opening apps. 

**Describe the solution you'd like**
A choice of search engine Google, Bing, DuckDuckGo, etc, with populating search results. Pressing enter on the keyboard would open the first result in your default browser. 

I also think Sesame integration for deeper capabilities would be nice. Of course make it optional, not mandatory. 

One more idea is take advantage of accessibility privileges to search for system settings. 

![Screenshot_20200214-123005](https://user-images.githubusercontent.com/60677023/74565282-c2deff80-4f25-11ea-9274-07e5139e5d93.jpg)

**Comment by Martin5001** [comment] 2020-02-15 12:08
> One more idea is take advantage of accessibility privileges to search for system settings.

I like this one.

**Comment by 8bitPit** [comment] 2020-02-16 12:45
I believe integrating Sesame into Niagara Launcher would be the easiest & best solution 😁 #88

**Comment by 8bitPit** [comment] 2020-03-01 18:06
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/58

**Closed by 8bitPit** 2020-03-01 18:06 UTC
Labels: duplicate
