### ISSUE TITLE
thumb reach issue

### ISSUE THREAD

**Issue by HubbyG** [8bitPit/Niagara-Issues#1265] opened 2020-04-26 13:06 UTC
**Is your feature request related to a problem? Please describe.**
In attempting one handed use, two hands are almost always required: my thumb cannot span through the full launcher alphabet.  Even when letter is reachable by my thumb, often the first apps are too high up the screen to be reached with thumb without further scrolling.

**Describe the solution you'd like**
A means to calibrate (or select some other predefined) full height of the alphabet swipe to minimise extra dexterity required to launch apps for people with smaller thumb reach on large phones.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment] 2020-04-26 19:49
Thanks for your request. It sounds like it's duplicate of #334, could that be?

**Comment by HubbyG** [comment] 2020-04-26 20:02
Thank you for getting back and yes, pretty much along the same lines...

Only additionally when releasing the indexed list of apps starting with that letter are also placed proportionally within shorter thumb reach, please.

Apologies for in part duplicating.

**Comment by 8bitPit** [comment] 2020-05-02 10:05
No problem :)

**Comment by 8bitPit** [comment] 2020-05-02 10:06
@HubbyG if you'd like to, you can comment your additional idea in  #334

**Closed by 8bitPit** 2020-05-02 10:06 UTC
Labels: duplicate
