### ISSUE TITLE
Blur background under home screen favorites'notification text

### ISSUE THREAD

**Issue by dps85** [8bitPit/Niagara-Issues#2288] opened 2023-05-22 18:26 UTC
### Is your feature request related to a problem?

For most wallpapers - especially photos of people, it's hard to read the text regardless of selecting white or black text. E.g. when I get a text message, the notification preview is difficult to read because of my wallpaper

### Describe the solution you'd like

One way to allow for better readability would be to create a background under the text when notifications are on screen. One simple way would be to create a rectangle with some opacity/blur. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-05-27 06:32
Hi @dps85, thank you for your suggestion. To ensure better visibility, it is generally recommended to avoid using wallpapers that may cause readability issues. Alternatively, you can use apps like [Muzei](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei), which allow you to dim/blur the wallpaper for improved readability. Unfortunately, adding blur behind the text is not currently possible due to technical limitations. However, there is an existing issue addressing the addition of a transparent background (See #717). While it's uncertain if the development team has deemed it [impactful](https://help.niagaralauncher.app/article/8-niagaras-design-principles) enough to consider, I will close this issue as duplicate and reopen the older one. Please feel free to follow up and provide your feedback there. Thank you for your understanding and cooperation.

Tip: You can swipe right on the app/previews and easily read the them in the pop-ups.

#Duplicate of #717

**Closed** 2023-05-27 06:33 UTC
