### ISSUE TITLE
Screen time on Niagara widget 

### ISSUE THREAD

**Issue by Tareq4322** [8bitPit/Niagara-Issues#2452] opened 2023-11-23 13:47 UTC
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

The Niagara widget provides a lot of helpful information at a glance, including the date, schedule, weather, and battery percentage. I think displaying the screen time on the Niagara widget would be a great feature. And clicking on the screen time option would open "Your "Agenda" with much more detailed information about screen time, similar to the default Android widget.
I hope you guys will consider my Idea and love the anycon update!!

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-10-05 12:42
Hey there, I just stumbled over this ticket and I'll close this as a duplicate of #1811.

**Closed by NiagaraSupport** 2024-10-05 12:42 UTC
