### ISSUE TITLE
Time spent on app

### ISSUE THREAD

**Issue by Isitsmd** [8bitPit/Niagara-Issues#1550] opened 2021-03-21 16:47 UTC
**Something to notify me or advise me**
I bought it just today as I only found about this suitable minimalist approach of apps. As I use my phone for studying it is frustrating when [I waste time unnecessarily in the web]

**Well I would like time spent on the app to be displayed by its side to make me self aware or some other suitable productive methods**

**Comment by 8bitPit** [comment] 2021-03-23 15:21
Thank you very much for your request and your support @Isitsmd. Adding an app usage indicator is on our list, but we can't guarantee that it will be added: https://github.com/8bitPit/Niagara-Issues/issues/1260.

**Comment by 8bitPit** [comment] 2021-03-23 15:21
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1260

**Closed by 8bitPit** 2021-03-23 15:21 UTC
