### ISSUE TITLE
Icon animation glitch when closing application

### ISSUE THREAD

**Issue by bretonjustin** [8bitPit/Niagara-Issues#2174] opened 2023-01-13 17:31 UTC
### Describe the bug

The app icon animation glitches when closing an app (short blink / appear-disapear of the icon). It occurs for every app. It occurs with other icon packs also. It occurs in favorite apps and in the full app list.

### Steps to reproduce

1. Go to home screen
2. Open any apps
3. Close the app by swiping up
4. The small animation of the icon will glitch

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Oxygen OS

### Device name

OnePlus 7T

### Android version

Android 12

### Screenshots / Screen recordings

Watch several times, sometimes the fps of the computer will hide the glitch. Also see screenshot of when the glitch occurred.

https://user-images.githubusercontent.com/27016103/212381445-4c826d2b-0f85-493c-a720-9aaf0f79856c.mp4

![image](https://user-images.githubusercontent.com/27016103/212382054-a64fc748-3156-48e4-881d-da30d5314bdb.png)

**Comment by Amorphous404** [comment] 2023-01-17 12:01
Thanks for reporting, App closing animation is from a submodule of your preinstalled launcher; OnePlus launcher in your case. The same artifacts should also be reproducible with other third-party launchers then, e.g Nova Launcher or Microsoft Launcher. Can you please check and report back, meanwhile I'll ask the devs if it's a known issue since there are already quite similar known apps closing animation bugs.

**Comment by bretonjustin** [comment] 2023-01-17 14:46
> Thanks for reporting, App closing animation is from a submodule of your preinstalled launcher; OnePlus launcher in your case. The same artifacts should also be reproducible with other third-party launchers then, e.g Nova Launcher or Microsoft Launcher. Can you please check and report back, meanwhile I'll ask the devs if it's a known issue since there are already quite similar known app closing animation bugs.

I just tested with Microsoft Launcher and Nova Launcher and I cannot reproduce the bug. I also don't have the issue with the default OnePlus Launcher.

**Comment by Amorphous404** [comment] 2023-01-17 16:24
Thanks for checking it, Do the third party launchers that you tested with also support the app closing/fallback animation on your device. To my understanding this animation bug is likely caused by the system as gesture navigation on third party launchers is controlled/depends on your stock Launcher, with the native stock launcher i.e OxygenOS Launcher in your case you won't face such issues.

For more information you can refer to this: article:https://help.niagaralauncher.app/article/7-gesture-navigation

Also i can't reproduce the blink animation bug on my device which runs on OxygenOS 13 which runs on Android 13 and also doesn't yet support this new app closing.

However since you mentioned you can't reproduce the issue on other third party launchers, I have forwarded the issue to the developers to look into it.

**Comment by Amorphous404** [comment] 2023-01-17 17:04
Just confirmed it from the devs, unfortunately that's caused by the system launcher, OnePlus needs to add the fix for it (which they partially fixed it in Android 13, but removed closing animation 💀)

A similar bug was reported by a user with OxygenOS 11 where the closing the app showed some visual artifact around the app instead #1614

**Closed** 2023-01-17 17:04 UTC
Labels: bug, blocked
