### ISSUE TITLE
Double tapping to lock issue

### ISSUE THREAD

**Issue by itsjillard** [8bitPit/Niagara-Issues#2227] opened 2023-03-22 06:14 UTC
### Describe the bug

Whenever I lock the screen by double tapping the alphabet, and then unlock my phone, it goes to the app drawer instead of home screen. I think it's because by double tapping alphabet to lock screen, moments before it locks, the app drawer is opened (because by default, tapping alphabet opens app drawer). Therefore, it opens the last thing opened, which is the app drawer instead of opening home screen.

### Steps to reproduce

1. Lock by double tapping alphabet
2. Unlock again

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Oneplus 7 Pro

### Android version

Android 10

**Comment by Amorphous404** [comment] 2023-03-22 06:49
If you lock your phone via double tapping the alphabet scroller and unlock the phone immediately (< 3 seconds), Niagara Launcher returns you to the last position (app list) instead of the main home screen. This is intentional and saves you time if you accidentally locked the phone.

More info here;
[Pressing home doesn't show favorites](https://help.niagaralauncher.app/article/86-pressing-home-doesnt-show-favorites)

**Comment by Amorphous404** [comment] 2023-03-22 06:54
Duplicate of #1989

**Closed** 2023-03-22 06:55 UTC
Labels: bug
