### ISSUE TITLE
Dark Sky Leaving Android (Apple Acquisition)

### ISSUE THREAD

**Issue by jacob-swenson** [8bitPit/Niagara-Issues#1333] opened 2020-07-07 00:14 UTC
Apple has acquired Dark Sky and it will no longer be available on Android beginning August 1st. This will probably break the weather features in Niagara.

Sources
https://www.theverge.com/2020/7/1/21310801/dark-sky-android-app-delay-shutdown-august-1st
https://blog.darksky.net/dark-sky-has-a-new-home/

**Comment by Rod911** [comment] 2020-07-07 17:20
Duplicate of #1239 
See [Article](https://niagaralauncher.helpscoutdocs.com/article/9-dark-sky-api-shutting-down)

**Closed by Rod911** 2020-07-07 17:20 UTC
Labels: duplicate
