### ISSUE TITLE
Want a dedicated page for widgets

### ISSUE THREAD

**Issue by Lightmarey** [8bitPit/Niagara-Issues#1793] opened 2021-12-30 11:29 UTC
### Is your feature request related to a problem?

For me, just one custom widget display is far from enough. I always have the need to show ToDos and tasker shortcuts and other kind of widgets on the screen, hence I thought a negative screen (like the card page in Microsoft launcher or the Today View in iPadOS) which contains more widgets is a good idea.

### Describe the solution you'd like

Want a optional setting to turn on a new page, which could be switched to by swiping left on the home page. This page could contain more than one ( infinity is much greater) widget and the lay out is just as the one in home page. (Just like the feature in Microsoft launcher or in iPadOS).

**Comment by TFackler** [comment] 2021-12-30 15:52
Thank you for your feedback. A widget page has already been requested multiple times, but we don't feel like that is the right way to go about including multiple widgets in Niagara.

Please see the following comment on a widget page (from #117) :
> I am not really a fan of widget pages. The only thing widgets have in common there is, well, they’re all widgets. So why should they be grouped together? Showing a weather widget below the clock and accessing your calendar agenda via a swipe / by tapping on a button makes more sense to me. Also, widgets often tend to use much ram. The concept of a widget list would kind of endorse user to cluster the page full of widgets. A swipe menu shows only a single widget at once, so not every widget has to be loaded into ram when you want to access one.
> That’s why I’m planning to add the following integration:
> You can place a single widget below the clock or replace it for showing weather and / or time, or an at a glance widget.
> More widgets can be accessed by swiping right on an app.
> Another idea would be that you can customize the google search button at the bottom right, so it can also launch a widget, e.g. your calendar.

Refer to the following issue for our take on including multiple widget in Niagara:
Widgets in swipe actions #1165

Duplicate of #1059

**Closed** 2021-12-30 15:57 UTC
