### ISSUE TITLE
Show status bar longer

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1371] opened 2020-09-25 14:54 UTC
When using the pro version & having the status bar hidden, it would be pleasant to have the status bar show up for just a _few_ more seconds, before it disappears again, when doing a tiny swipe down.

I have a hard time taking in all the info during the quick appearance of the status bar, but maybe it's just me.

**Comment by 8bitPit** [comment] 2020-10-15 13:01
Agreed, either showing it longer or keeping the status bar visible if you don't let go with your fingers could be helpful.

**Comment by Montell2099** [comment] 2020-10-17 12:47
That would definitely be a nice adjustment to this function, great idea.

**Comment by luxcalor** [comment] 2021-01-11 13:49
> keeping the status bar visible if you don't let go with your fingers could be helpful.
 
Came here to suggest this. Would be really helpful.

**Comment by topsy-turvy99** [comment] 2022-10-04 05:07
Now the status bar is visible for 5 sec with a light swipe down gesture, not sure which version pushed the changes, so ig the issue is fixed now 👍

**Closed** 2022-12-15 13:43 UTC
Labels: low priority

**Comment by Amorphous404** [comment] 2023-03-23 14:18
@8bitPit
