### ISSUE TITLE
Notification count instead of full text

### ISSUE THREAD

**Issue by the-eric-swanson** [8bitPit/Niagara-Issues#1074] opened 2019-12-08 19:42 UTC
**Is your feature request related to a problem? Please describe.**
No problem, just a feature request.

**Describe the solution you'd like**
Rather than have the full text of the notification—which often gets messy for longer notifications such as text messages or emails—could we have an option to just have an icon with a count for notifications? I think this would look much cleaner and also address people's privacy concerns about having the full text of notifications on display.

**Comment by 8bitPit** [comment] 2019-12-09 16:59
Hi, I believe this is a duplicate of: #217

**Comment by 8bitPit** [comment] 2019-12-09 16:59
Duplicate of #217

**Closed by 8bitPit** 2019-12-09 16:59 UTC
Labels: duplicate
