### ISSUE TITLE
Widgets are blank

### ISSUE THREAD

**Issue by flamendless** [8bitPit/Niagara-Issues#962] opened 2019-08-11 04:13 UTC
Widgets are blank. Tested on Huawei GR5 2017

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 8bitPit** [comment] 2019-08-14 19:06
Thanks for the report. Which widgets have you tried out? Is every one of them blank?

**Comment by 8bitPit** [comment] 2019-08-21 16:03
I think this is a duplicate of: https://github.com/8bitPit/Niagara-Issues/issues/952

**Comment by flamendless** [comment] 2019-08-22 03:13
@8bitPit yes, all widgets are blank

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 8bitPit** [comment] 2019-08-22 09:41
Thanks for the reply @flamendless. I'll close this issue but keep #952 open.

**Closed by 8bitPit** 2019-08-22 09:41 UTC
Labels: bug, duplicate, question

**Comment by 8bitPit** [comment] 2019-09-20 07:44
Does the issue still happen on your device?
