### ISSUE TITLE
Option to auto hide apps in folders

### ISSUE THREAD

**Issue by luke-tsai** [8bitPit/Niagara-Issues#1846] opened 2022-02-02 01:19 UTC
If an app is added to a folder, hide it from the main list.

**Comment by Oddward** [comment] 2022-03-12 13:53
Seems like a duplicate of [issue 1604](https://github.com/8bitPit/Niagara-Issues/issues/1604) - I'll close this one, you can follow up on the older issue

**Closed by Oddward** 2022-03-12 13:53 UTC
