### ISSUE TITLE
To do list implementation 

### ISSUE THREAD

**Issue by Scar3Scr3W** [8bitPit/Niagara-Issues#2250] opened 2023-04-20 11:16 UTC
### Is your feature request related to a problem?

It's pretty cumbersome to have to open another app every time to create, view and delete rapid tasks. 

### Describe the solution you'd like

I'd suggest to implement an easy and not to complicated "to do list", like for example by swiping up on the niagara button on the bottom right and showing rapidly a text field in which to input something that is to be remembered, and when pressing enter that something to be viewed somewhere, like for example in the notifications. I think it would be a really useful addition, which wouldn't impair anyone's experience of the launcher if they didn't use it but would really be helpful for remembering little things that have to be done through the day. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-04-20 12:46
Hi @Scar3Scr3W, Thank you for your suggestion; we don't plan to add a native to-do list. However, we are considering integrating Todoist, which should be helpful in your case.

• See: #1285

Additionally, one of our users shared a tutorial on how to create something similar:
You can bind a pop-up folder to Niagara button action -> Add the [Stuff widget](https://play.google.com/store/apps/details?id=com.stuff.todo) inside the popup to achieve the same.

• See: https://github.com/8bitPit/Niagara-Issues/issues/2052#issuecomment-1242740038

Duplicate of #1285

**Closed** 2023-04-20 13:14 UTC
