### ISSUE TITLE
Folder/Swipe Actions on Clock and Calendar

### ISSUE THREAD

**Issue by ethangeorge4** [8bitPit/Niagara-Issues#1293] opened 2020-05-20 19:14 UTC
It would be great to have Folders/Swipe Actions on the clock, calendar, and weather. Example use: quickly start a timer, or add an event/reminder.

**Comment by Rod911** [comment] 2020-06-02 15:19
Thanks for the request, this has already been requested, unfortunately this feature will not be considered for development, at least in 2020. See linked issue.

Duplicate of #250

**Closed by Rod911** 2020-06-02 15:19 UTC
