### ISSUE TITLE
Option to hide icon packs from app list

### ISSUE THREAD

**Issue by slayer101234** [8bitPit/Niagara-Issues#1020] opened 2019-10-12 16:56 UTC
Option to hide icon packs from app list to make it less cluttered.

**Comment by 8bitPit** [comment] 2019-10-12 21:53
You can already hide them, but you have to do manually. If you want this to happen automatically, check out #667.

**Comment by 8bitPit** [comment] 2019-10-12 21:53
Duplicate of #667

**Closed by 8bitPit** 2019-10-12 21:53 UTC
Labels: duplicate
