### ISSUE TITLE
App search results，Search Chinese, return result incomplete

### ISSUE THREAD

**Issue by yzxzz** [8bitPit/Niagara-Issues#1364] opened 2020-09-15 06:05 UTC
**Describe the bug**
App search results，Search Chinese, return result incomplete

**To Reproduce**
1. Go to 'App search'，Enter Chinese to search
2. For example, the app name is "手机淘宝". When I search for "手机"or"手" at the top of the name, I can search it normally,
3. However, when searching for the text behind the first text, such as "机", "淘宝",  can't search this app

**Smartphone (please complete the following information):**
 - Device: [Redmi K20pro]
 - Android version: [Android 10]

**Screenshots**
<img width="694" alt="1" src="https://user-images.githubusercontent.com/40624194/93171897-7d551000-f75c-11ea-8c47-6a1fc5d2d470.png">
<img width="694" alt="2" src="https://user-images.githubusercontent.com/40624194/93171895-7cbc7980-f75c-11ea-9e8b-9d555083f03a.png">
<img width="694" alt="3" src="https://user-images.githubusercontent.com/40624194/93171887-79c18900-f75c-11ea-861c-d760dab06377.png">

**Comment by 8bitPit** [comment] 2020-09-16 08:09
Thanks for your detailed explanation. Yes, that's currently a bug with all non-Latin app names.

**Comment by 8bitPit** [comment] 2020-09-23 08:17
Duplicate of #1310

**Closed by 8bitPit** 2020-09-23 08:17 UTC
Labels: bug, good first issue
