### ISSUE TITLE
Advanced Music apps (multi-device support)

### ISSUE THREAD

**Issue by RokasAnisas** [8bitPit/Niagara-Issues#2270] opened 2023-05-07 18:26 UTC
### Is your feature request related to a problem?

I really like the Music Apps feature, which pulls up selected apps when a bluetooth audio device is connected. I would like to propose an improvement, leave the default behaviour as is, but add also the ability to show specific apps for specific audio devices.

Example scenario(my case):
1. My wireless earphones that i use the most, I like to listen music, audio books or have the specific app for those earphones ready.
2. Connected to car: having maps show up top woul be awesome, also some other travel prefered audio books / podcast apps
3. Another pair of overhead bluetooth headphones have a different configuration app
4. Bluetooth speaker: ...

### Describe the solution you'd like

Leave the default behaviour as is, but add also the ability to show specific apps for specific audio devices.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-05-07 18:41
Hi @RokasAnisas, Thank you for your suggestion. This feature has already been proposed in #1990

Duplicate of #1990

**Closed** 2023-05-07 18:42 UTC
