### ISSUE TITLE
Integrate search

### ISSUE THREAD

**Issue by prabhumns** [8bitPit/Niagara-Issues#760] opened 2019-02-14 07:50 UTC
You have your own search feature. Integrate it with sesame shortcuts or at least with google search i.e., if the app i am searching is not in app list it will show an option to search in google app or the search button on keyboard should redirect to google search. Finally we will use that not only for apps but for everything we want to search for.

**Comment by 8bitPit** [comment] 2019-02-15 10:48
Duplicate of #88 & https://github.com/8bitPit/Niagara-Issues/issues/336

**Closed by 8bitPit** 2019-02-15 10:48 UTC
Labels: duplicate
