### ISSUE TITLE
Hidden Apps shows up in recent installed

### ISSUE THREAD

**Issue by Octa56** [8bitPit/Niagara-Issues#1196] opened 2020-02-25 00:04 UTC
Describe the bug
If you install an app and hide it from the app list, it will appear when you click the Search button as a Recent Installed app.

To Reproduce
1- Install any app
2- Hide it
3- Click Search button

**Comment by Martin5001** [comment] 2020-02-25 18:18
I think this was intended. And I personally would keep it as it is anyways, but that's just my opinion.

**Comment by 8bitPit** [comment] 2020-02-25 18:41
Hi @Octa56, thanks for reporting. Can you please check out if this bug was fixed on the latest version (v0.17.0)? It's not available on Google Play yet, but you can download it from GitHub: https://github.com/8bitPit/Niagara-Issues/releases

**Comment by Octa56** [comment] 2020-02-25 19:42
@8bitPit Yes, its fixed. Thanks so much!

**Comment by 8bitPit** [comment] 2020-02-26 14:15
Great to hear, haha :)

**Closed by 8bitPit** 2020-02-26 14:15 UTC
Labels: question
