### ISSUE TITLE
Multiple shortcut bugs

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1106] opened 2019-12-23 12:27 UTC
**1**. When adding the "Driving Mode" shortcut from Google Maps, two shortcuts suddenly appear with only the name "Driving" that leads to the same destination (no pun intended) with two separate icons:
![Screenshot_20191223-125123](https://user-images.githubusercontent.com/43126233/71360552-92678e80-2590-11ea-92ff-ece5f293b501.png)

**2.** The contacts name bug is still present when right-swiping on Contacts (_the names gets shortened way too early_)  which has been brought to your attention before. This bug is present in the shortcuts menu for Contacts as well — however, it isn't present when adding shortcuts from either Messages or Phone:
![Screenshot_20191223-125246~2](https://user-images.githubusercontent.com/43126233/71360659-d490d000-2590-11ea-9c13-a132bd41f2e9.png)
![Screenshot_20191223-125314~2](https://user-images.githubusercontent.com/43126233/71360669-dd81a180-2590-11ea-9a37-5ef973f03825.png)

**3.** I added the "Subscriptions" shortcut for YouTube & renamed it to "YouTube subs". Then when I changed its icon, its name reverted to "Subscriptions".

Other than these bugs, shortcuts seems to work good & it's an exciting addition to the launcher! I wish you a merry Christmas @8bitPit and a happy new year, 2020 will be exciting for Niagara. 🎉

**Comment by 8bitPit** [comment] 2019-12-29 21:50
That's so nice of thanks 😁 Wish you happy Holidays, too! Moreover, thanks for your reports and taking the time to also screenshot everything!

I'll try to reproduce 1, fix 2 and am glad I can tell you that 3 has already been fixed with 0.11.3.

**Comment by Montell2099** [comment] 2019-12-30 11:56
@8bitPit Great to hear! Thanks for your work.

Another minor bug I'm experiencing is that when creating a Spotify playlist shortcut it starts auto-playing when tapping that shortcut.

**Comment by 8bitPit** [comment] 2020-01-11 09:36
> Another minor bug I'm experiencing is that when creating a Spotify playlist shortcut it starts auto-playing when tapping that shortcut.

@Montell2099 can you reproduce this issue on other third-party launchers?

**Comment by Montell2099** [comment] 2020-01-11 22:09
> @Montell2099 can you reproduce this issue on other third-party launchers?

Yeah, it occurred when I tried a Spotify playlist shortcut within Nova Launcher as well. However I can't really find a stable way of reproducing it.

The only reliant way is If I'm playing music from another playlist, then when I tap my playlist shortcut it starts playing from there instead. Might not be related to Niagara, I don't know. 😕

**Comment by 8bitPit** [comment] 2020-01-12 12:23
@Montell2099 I fear that this gets caused by Spotify then.

**Comment by Montell2099** [comment] 2020-01-12 12:39
> @Montell2099 I fear that this gets caused by Spotify then.

Most probably, fortunately it's not that big of a problem.

Regarding the main post of this thread, do you have any idea why just the names of contacts gets shortened (when right-swiping), while the names from messages & phone does not? Any progress? 🙂

**Comment by 8bitPit** [comment] 2020-05-02 15:27
@Montell2099 the duplicate shortcut bug will be fixed in v0.26. Can't say yet, when we will take care of the shortcut names (https://github.com/8bitPit/Niagara-Issues/issues/983).

**Comment by 8bitPit** [comment] 2020-05-04 14:28
****

**Closed by 8bitPit** 2020-05-04 14:28 UTC
Labels: bug, fixed soon
