### ISSUE TITLE
Icon Spacing option

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2255] opened 2023-04-21 10:36 UTC
### Is your feature request related to a problem?

There is a default spacing of icons on the homescreen this does mean if you want to show more apps / folders at any given time you can't adjust it. On the homescreen particularly where you have favourited apps and created folders it can mean you have to scroll. There may be users who want to do the opposite and have even fewer apps and folders on their home screen for a super clean and minimal look.

The app list also is impacted by this especially for users with a high number of apps.

Homescreen
![Screenshot_20230421_112813_Niagara Launcher](https://user-images.githubusercontent.com/81394097/233614979-bb14c513-3e7f-4ac8-b6dc-cd48d77997e0.jpg)

App List
![Screenshot_20230421_112837_Niagara Launcher](https://user-images.githubusercontent.com/81394097/233615003-c98aae19-4dff-495e-b1f9-6a71d5894122.jpg)

### Describe the solution you'd like

It would be helpful to have a slider to adjust icon spacing to either reduce the gap to fit in more apps or increase the gap for that more minimal look.

A, second slider for the app list woudl be helpful to reduce the distance from the default and fit in more apps. I'm not sure there is a benefit of increasing the space for the app list. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-04-21 19:40
Hi @Lorestan00, Thank you for your suggestion. I have reopened an existing issue that is relevant to your suggestion. Could you please forward the same to that particular issue?

Thanks,

Duplicate of #304

**Closed** 2023-04-21 19:41 UTC
