### ISSUE TITLE
Order of sorting apps by usage 

### ISSUE THREAD

**Issue by Devareddy1998** [8bitPit/Niagara-Issues#2543] opened 2024-01-07 16:10 UTC
### Is your feature request related to a problem?

Every time I unlock and try to reach for the most used app/folder it stays at the top of the list, which is hard to reach.
![Screenshot_2024-01-07-21-30-04-50_a4824db61f40c53807964ea8b14c92fe](https://github.com/8bitPit/Niagara-Issues/assets/36725943/89ae1a2f-06fb-4dd1-bb27-8e97d982ebdf)

### Describe the solution you'd like

It would be so much easier if reversible sort order was a feature, which makes the most used app stay at the bottom always and least used ones move to the top.
I know I can customise the most used apps list to my preferences but sometimes I stop using some apps and sometimes I install new apps that I use frequently, which makes the constantly most used app go a bit high.
Like siri app suggestions on iPhone which change continuously based on usage it recommends the most frequently used apps on the suggestions widget.
I thought we could have that feature which constantly updates the most used (6-8) apps in bottom to top sorting for easy reachability as well.
That's all I would like to add.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by maceip** [comment] 2024-01-08 14:58
I was just about to submit a feature request for this.

When sorting by usage, the favorites list should put most used apps at the bottom as it's closer to my thumb.

At the very least can we get a toggle for this? If your product was open source I would just submit a pull request as it's very simple.

Here's my setup, sorted by usage. I wish the Gmail icon was at the bottom:

![Screenshot_20240108-105739](https://github.com/8bitPit/Niagara-Issues/assets/804368/99852d0f-3e01-41a7-b147-87f4d0c0bd20)

**Comment by Devareddy1998** [comment] 2024-01-08 15:03
Same feeling everytime I unlock, I wish I had the most used app at the bottom
And also the list should update based on usage like the least used ones from the previously most used apps should no longer be in the favourites thereby only allowing 6-8 apps on the main screen with descending order of usage based sorting.
We wish this gets noticed by the devs.

**Comment by NiagaraSupport** [comment] 2024-01-19 12:47
Hi there, thank you for your suggestions.
We did it in descending order because, depending on the position and length of the favorites, the bottom of the list can be cut off, and we didn't want that for the most used options.
However, this feature is requested reasonably often, so I'll bring it up with the team. I'll close this one, as it is a duplicate of #2522.

**Closed by NiagaraSupport** 2024-01-19 12:47 UTC
