### ISSUE TITLE
Removing navbar from homescreen

### ISSUE THREAD

**Issue by iroQuai** [8bitPit/Niagara-Issues#1088] opened 2019-12-13 07:17 UTC
Hi! I've used Niagara for almost a year now and updated to pro recently because of the wonderful extra features. Especially removing the notification bar makes everything look even slicker! (Especially on an oled screen with a black background)

Yesterday I updated my s8 with the latest security update (November). Since then, the navigation bar keeps showing on the home screen! This wasn't the case before the update. 

Anyone has an idea how to remove this again? Thanks in advance!

**Comment by Montell2099** [comment] 2019-12-15 15:08
> updated to pro recently because of the wonderful extra features. Especially removing the **notification bar**

> Yesterday I updated my s8 with the latest security update (November). Since then, the **navigation bar** keeps showing on the home screen

Niagara Pro is only able to hide the notification bar as of now, not the navigation bar. Am I misinterpreting you or could you be more specific?

**Comment by 8bitPit** [comment] 2019-12-16 18:30
Thanks a lot for your support @iroQuai. I'm not certain, but isn't there a Samsung feature that hides the bar and lets you use navigation gestures?

**Comment by 8bitPit** [comment] 2019-12-16 18:30
Also I believe this is a duplicate of: https://github.com/8bitPit/Niagara-Issues/issues/43

**Comment by 8bitPit** [comment] 2019-12-29 08:57
Feel free to open the issue again in case my previous reply didn't help.

**Closed by 8bitPit** 2019-12-29 08:57 UTC
Labels: question
