### ISSUE TITLE
Import Export Settings 

### ISSUE THREAD

**Issue by mtz** [8bitPit/Niagara-Issues#1161] opened 2020-02-02 01:48 UTC
I would like to import and export the launcher settings to simple keep and set/reset quickly and stressless.

Thanks in advance. 
mtz

**Comment by Martin5001** [comment] 2020-02-02 14:02
I would like this feature too. There are also some APIs for that: https://developer.android.com/guide/topics/data/backup

**Comment by 8bitPit** [comment] 2020-02-02 19:54
Thank you both, it's under consideration: #222

**Comment by 8bitPit** [comment] 2020-02-02 19:54
Duplicate of #222

**Closed by 8bitPit** 2020-02-02 19:54 UTC
Labels: duplicate
