### ISSUE TITLE
Move the whole list to the top when media is playing

### ISSUE THREAD

**Issue by ayushpat123** [8bitPit/Niagara-Issues#1236] opened 2020-03-30 07:24 UTC
**Is your feature request related to a problem? Please describe.**
When media plays, then due to the extra media widget, few favourite apps flow out of the screen 

**Describe the solution you'd like**
A setting where we can move the entire list to a different position whenever media is playing. This is a very simple solution and won't effect other features. Makes the launcher more pleasing to look at when the apps are not flowing out of my screen

**Comment by 8bitPit** [comment] 2020-04-16 20:51
Thanks for your request, someone else is thinking the exact same ;)
https://github.com/8bitPit/Niagara-Issues/issues/243

**Comment by 8bitPit** [comment] 2020-04-16 20:51
Duplicate of #243

**Closed by 8bitPit** 2020-04-16 20:51 UTC
