### ISSUE TITLE
Wallpaper Transparency Bar

### ISSUE THREAD

**Issue by shadesrt** [8bitPit/Niagara-Issues#1215] opened 2020-03-15 12:58 UTC
First off, i love this app, and even if this feature doesnt get added, i would still continue using the app.
Now the problem is as follows, i like changing wallpapers a lot, so every now and then, i face this issue that i cannot see the app name/time/date because some portion of the wallpaper is similar in color/contrast with the said part of the ui. So in order to view it properly i have to either change the wallpaper or change the text color, but changing the text color doesnt help much because then some other wallpaper would be mismatching again. And changing the wallpaper defeats the purpose of using the previous wallpaper.
So the solution to this issue would be like introducing a wallpaper transparency bar, like the default is 100% and when at 0% the background would be pitch black. 
Also, you can add a toggle for this setting to be same for all future wallpapers, or to be resetted everytime a wallpaper is changed.

**Comment by 8bitPit** [comment] 2020-03-15 15:23
Thank you very much for your kind words and for your feedback @shadesrt :) Darkening the wallpaper would be possible once wallpaper tinting is supported: https://github.com/8bitPit/Niagara-Issues/issues/705

**Comment by 8bitPit** [comment] 2020-03-15 15:24
Duplicate of #705

**Closed by 8bitPit** 2020-03-15 15:24 UTC
