### ISSUE TITLE
Apps with notifications appearing in favourite list. 

### ISSUE THREAD

**Issue by maranfaran** [8bitPit/Niagara-Issues#1148] opened 2020-01-20 16:57 UTC
Would it be possible to get apps with notifications appear at the favourite list, just like you selected music app appears when connected to BT or cord?Would be a nice feature when the statusline is hidden.

**Comment by 8bitPit** [comment] 2020-01-21 10:05
Yup, would be possible: #152

**Comment by 8bitPit** [comment] 2020-01-21 10:05
Duplicate of #152

**Closed by 8bitPit** 2020-01-21 10:05 UTC
Labels: duplicate
