### ISSUE TITLE
Media playback bar cropping Pocket Casts' covers 

### ISSUE THREAD

**Issue by Sofoca** [8bitPit/Niagara-Issues#1246] opened 2020-04-10 08:49 UTC
**Describe the bug**
The covers of all podcasts played through Pocket Casts are cropped roughly 20% on all edges even though the already are square to begin with (so no need to crop I guess). 

**To Reproduce**
1. Download Pocket Casts
2. Play any podcast
3. Cover will appear cropped on media playback bar

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2
 - Android version: Android 10 (Security Patch Level March 2020)

**Screenshots**
![IMAGE 2020-04-10 10:47:52](https://user-images.githubusercontent.com/8494954/78977635-bb4c6900-7b18-11ea-8739-fbfa095370d6.jpg)
![IMAGE 2020-04-10 10:47:55](https://user-images.githubusercontent.com/8494954/78977636-bc7d9600-7b18-11ea-9619-7e12ea6ce13a.jpg)

Let me know if you need any more information.

**Comment by 8bitPit** [comment] 2020-04-18 20:46
Hi, can you please check if the artwork also gets cropped in Android's notification shade?

**Comment by Sofoca** [comment] 2020-04-19 07:57
Only a bit in the expanded one. Thanks for looking into this! 
![photo_2020-04-19 09 56 51](https://user-images.githubusercontent.com/8494954/79682640-22a69f00-8224-11ea-9ff2-b36147ba989a.jpeg)
![photo_2020-04-19 09 56 53](https://user-images.githubusercontent.com/8494954/79682642-263a2600-8224-11ea-8dbe-53662219613f.jpeg)
![photo_2020-04-19 09 56 54](https://user-images.githubusercontent.com/8494954/79682643-26d2bc80-8224-11ea-867f-1f3a342e8333.jpeg)

**Comment by 8bitPit** [comment] 2020-05-13 20:24
Thank you for the images @Sofoca!

**Comment by 8bitPit** [comment] 2021-03-23 18:26
@Sofoca does this still happen on your device? I tried to reproduce the issue, but it seems to be working fine on my phone:
![photo_2021-03-23_19-25-44](https://user-images.githubusercontent.com/9284845/112198613-9825a700-8c0d-11eb-9fd9-347b31996b41.jpg)

**Comment by Sofoca** [comment] 2021-03-23 19:23
I’m on a different device now and it doesn’t on the new one.

**Comment by 8bitPit** [comment] 2021-03-25 11:52
I see, thanks for letting me know @Sofoca. I'll close this ticket then. If you or anyone else experiences this bug again, please let me know :)

**Closed by 8bitPit** 2021-03-25 11:52 UTC
Labels: bug, question
