### ISSUE TITLE
Upcoming events next to the icon

### ISSUE THREAD

**Issue by augsemaugse** [8bitPit/Niagara-Issues#954] opened 2019-08-07 15:27 UTC
Great launcher. Thanks for all the work. 

Would it be possible to show the upcoming events as a notification next to the calendar icon like it's done for other apps like Telegram, WhatsApp, mail or so?

**Comment by Martin5001** [comment] 2019-08-08 13:02
#932 could be another option.

**Comment by 8bitPit** [comment] 2019-08-08 13:22
Thanks for the kind words @augsemaugse. As Martin pointed out, this feature has already been requested: #932 / #53

**Comment by 8bitPit** [comment] 2019-08-08 13:22
Duplicate of #55

**Closed by 8bitPit** 2019-08-08 13:22 UTC
Labels: duplicate
