### ISSUE TITLE
Unable to set Niagara launcher as a default launcher

### ISSUE THREAD

**Issue by lainovic** [8bitPit/Niagara-Issues#1994] opened 2022-07-13 15:30 UTC
### Describe the bug

Hi,

Niagara launcher is still unable to be set as a default launcher.

I recall that the fault lies somewhere in OneUI, but this has been going on for quite a while - will this ever get fixed?

### Steps to reproduce

1. Go to Home screen

### Device name

Samsung Note 20 Ultra

### Android version

Android 12

### Screenshots / Screen recordings

![image](https://user-images.githubusercontent.com/57601153/178772225-62902bc2-4d98-4aea-a768-e56be2b71a78.png)

**Comment by Rod911** [comment] 2022-08-01 17:59
> Please read [this help article](https://help.niagaralauncher.app/article/102-niagara-launcher-not-staying-as-default) and use the secret command if necessary (and the launcher is already your default).
Closing as duplicate of #1864

**Closed by Rod911** 2022-08-01 17:59 UTC
Labels: bug, duplicate

**Comment by lainovic** [comment] 2022-08-01 18:07
Hahaha, awesome, like a cheat code :laughing:  Thanks!
