### ISSUE TITLE
Keyboard doesn't automatically open consistently when pressing home button to activate search

### ISSUE THREAD

**Issue by calemccammon** [8bitPit/Niagara-Issues#1352] opened 2020-09-01 23:14 UTC
1. Settings > Features > Home to search Toggled ON
2. Press home to return to home screen
3. Press home to app search
4. Repeat: Observe that the keyboard doesn't automatically open 100% of the time (more like 50%).

Expected: Keyboard should open 100% because the search bar is in focus.

Samsung S10+ Android 10

**Comment by praveenchandranpk** [comment] 2020-09-11 17:39
Same issue here. And I think it would be nice to show the keyboard again if we swipe down on the search screen.

**Comment by andys8** [comment] 2020-09-27 14:07
Experiencing the same issue, too. It's happening on a regular basis, and can be reproduced.

![Screenshot_20200927-155828](https://user-images.githubusercontent.com/13085980/94366884-314e8780-00db-11eb-99df-e3c064cfa96a.jpg)


![20-09-27-15-59-41](https://user-images.githubusercontent.com/13085980/94366921-72df3280-00db-11eb-89c4-ee3ddc98a7f1.gif)

**Comment by 8bitPit** [comment] 2020-10-15 14:17
@andys8 you're using a Samsung device as well, right? It's hard to tell, but it might be caused by them (I couldn't it reproduce on my devices), but maybe there's a workaround.

**Comment by andys8** [comment] 2020-10-15 15:34
I'm not using a Samsung device. I'm using a OnePlus 8.

![Screenshot_20201015-173259](https://user-images.githubusercontent.com/13085980/96152204-947a4f80-0f0c-11eb-92b7-04f411f1efb4.jpg)

**Comment by Montell2099** [comment] 2020-10-17 13:03
Unfortunately I couldn't export my screen recording as a gif, to post here. But I'm experiencing the same bug on my Pixel 2 (non-XL) with Android 11 and SwiftKey keyboard.

It happens about 10 % of the time, hard to tell exactly.

**Comment by andys8** [comment] 2020-10-30 01:20
Any updates on this one? I could also live with disabling animations, if it helps.

**Comment by mrbekong** [comment] 2020-10-30 02:46
> Any updates on this one? I could also live with disabling animations, if it helps.
Try using gesture navigation and see if it persists. 

I'm on a oneplus 7 pro with gesture navigation and keyboard appears every time

**Comment by andys8** [comment] 2020-11-08 22:03
With the changes made to animations, it might be the case that this issue is solved. At least I can currently with v0.33.1 not easily reproduce the issue. Can somebody confirm?

**Comment by Montell2099** [comment] 2020-11-08 22:39
> With the changes made to animations, it might be the case that this issue is solved. At least I can currently with v0.33.1 not easily reproduce the issue. Can somebody confirm?

I'm on v0.33.1 as well & I can't reproduce the bug either. May have been solved indeed.

**Comment by 8bitPit** [comment] 2020-11-18 17:45
Great, thank you both for letting me know :D I'll close this ticket then, but you can reopen it once the issue reappears.

**Closed by 8bitPit** 2020-11-18 17:45 UTC
Labels: bug
