### ISSUE TITLE
Manually selected icon stays after icon pack uninstalled

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1447] opened 2020-12-16 17:35 UTC
If I pick icon manually for a specific app, it stays in place even after the icon pack is uninstalled. (This doesn't happen if the icon pack is applied globally for all apps via Settings or in the dashboard.)

Niagara 0.34.1
Android 9 Samsung Galaxy J7

**Comment by Just-SKY** [comment] 2020-12-17 03:45
For me it's and advantage, because the users can choose their personal icon packs and combine them. I personally use to combine different icon packs, and I believe that many people use to do the same thing.
I prefer if it stay the same.

**Comment by Martin5001** [comment] 2020-12-17 05:48
> For me it's and advantage, because the users can choose their personal icon packs and combine them. I personally use to combine different icon packs, and I believe that many people use to do the same thing.
> I prefer if it stay the same.

Yeah, I agree. I use it that way too. But it shouldn't stay when the pack is uninstalled from the phone I think.

**Comment by 8bitPit** [comment] 2020-12-22 07:11
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1322 (Btw @Martin5001, I just stole the title of your issue :P)

**Closed by 8bitPit** 2020-12-22 07:11 UTC
Labels: bug
