### ISSUE TITLE
Temperature unit offset

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1030] opened 2019-10-23 01:03 UTC
This happens to me a couple of times every month, and I have absolutely no idea what's triggering it. I hadn't used my phone for hours then—when I unlocked it to check a notification—the temperature unit was offset.

![Screenshot_20191023-025207](https://user-images.githubusercontent.com/43126233/67347104-6a808e00-f541-11e9-89a0-3b1edf54c115.png)

Resizing the At a glance-widget didn't help, but a simple restart of Niagara always does the trick. I'm using a Pixel 2, and this has kept happening even back when I was using the stable Play Store version of the launcher, not just Github releases.

**Comment by 8bitPit** [comment] 2019-10-23 13:00
This might be caused by the length of the text in the widget (in particular, the length of the day) and can be fixed by giving the widget more room. You can do that by enabling the experimental full-width feature: Go to Niagara's search and type in "/widget filled"

**Comment by Montell2099** [comment] 2019-10-23 14:07
Thanks! I'm using the experimental feature now, will keep an eye out on the future. I'm sceptical though if it simply has to do with the date/temp string length.

Are there any more exciting experimental features you'd care to share? I love to test things out, as you might've noticed by my Github activity. 🤛

**Comment by 8bitPit** [comment] 2019-10-23 14:51
Haha, you can also try out "/notifications", "/onboarding" and "/infotest", but they don't enable new features and are meant for debugging purposes.

**Closed** 2019-10-26 15:13 UTC
Labels: bug
