### ISSUE TITLE
Show notification on the homescreen

### ISSUE THREAD

**Issue by AnotherNora** [8bitPit/Niagara-Issues#2581] opened 2024-01-31 03:07 UTC
### Describe the solution you'd like

I believe that having notifications on the homescreen would be beneficial to niagara.

1.) For privacy, it means we would no longer need to have our notifications on our lockscreens. Our push notifications can be hidden behind a lock while still being quickly visible.

2.) It would mean that the first thing we would see when opening our phones and when closing apps are the things we've missed.

3.) Given the ease and convenience of searching for apps using the alphabet scroll thing, I find that I almost never use those to open the apps, instead using it only to monitor the notifications of a few important apps. 

4.) With notification summaries already on the homescreen, I believe that having the other notifications on it too would make it more cohesive as a notification center kind of deal.

If adding the options to show notifications on the homescreen is out of the picture, perhaps consider these options?

1.) suggest apps with notifications on the favorites. Something similar to the "Suggest Frequently used apps" feature. 
2.) an option to float apps already in the favorites section to the top if it has a notification. Something that functions similarly to the sort app by usage feature

Thank you for taking the time to read my suggestion! 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment] 2024-02-03 21:15
Thanks for the suggestion. This is a duplicate of this old issue:  https://github.com/8bitPit/Niagara-Issues/issues/152 - feel free to follow it there and thumbs up 
*(maybe discuss if an implementation of this would be a significantly useful addition compared to existing features like Notification Summary and folder categories with notifications)*

**Comment by NiagaraSupport** [comment] 2024-02-21 10:39
I'll close this as duplicate then. Also pop-up folders might help in managing apps with notifications somewhat.

**Closed by NiagaraSupport** 2024-02-21 10:39 UTC
Labels: duplicate
