### ISSUE TITLE
Add widgets

### ISSUE THREAD

**Issue by ItalianGideon** [8bitPit/Niagara-Issues#618] opened 2018-11-27 18:13 UTC
Nice launcher, I will suggest a side panel accessible with a swipe for widgets. A swipe enabled only in the home.
Use only one side for the scroll search. In settings implement the toggle for choose if you use left hand or not. Now you can use the other side to add the widgets panel

**Comment by 8bitPit** [comment] 2018-11-27 22:12
Duplicate of #59 / #117

**Closed by 8bitPit** 2018-11-27 22:12 UTC
Labels: duplicate
