### ISSUE TITLE
Option to move widget from upward to downward or between the apps.

### ISSUE THREAD

**Issue by Foxbat24N** [8bitPit/Niagara-Issues#1916] opened 2022-04-10 17:46 UTC
This option may be redundant but if east to implement then you can. 

And hoping that you were working on stack widget option...🤞

**Comment by Oddward** [comment] 2022-04-10 18:29
This is a duplicate of/similar to issue #1118, you can track it there but the request was decided against a while back. See [this help article](https://help.niagaralauncher.app/article/77-missing-customization-features#:~:text=Add%20toggle-,to,-move%20media%20widget) for more info. I'll close this one for now

**Closed by Oddward** 2022-04-10 18:29 UTC
