### ISSUE TITLE
Option to disable favorites and suggestions

### ISSUE THREAD

**Issue by kylemd** [8bitPit/Niagara-Issues#1190] opened 2020-02-19 10:00 UTC
**Describe the solution you'd like**
An option to disable favorites and suggestions on the home screen.

My partner wants a blank home screen - not that I agree, but it would be a nice, simple option.

**Comment by Montell2099** [comment] 2020-02-20 06:54
Isn't it possible to just not assign any favorites and tick the settings checkbox "limit most used apps"?

Otherwise he could assign only a few favorites and use a blank icon pack, resulting in just text shortcuts. That's the only possible solution to his minimalism available at the moment for this niche request.

**Comment by kylemd** [comment] 2020-02-20 23:11
> Isn't it possible to just not assign any favorites and tick the settings checkbox "limit most used apps"?

That is what I've done, and it appears to be working for now. However, it would still be nice to have a favourites page and a blank home page.

**Comment by 8bitPit** [comment] 2020-02-26 14:17
Hi, I believe this is a duplicate of: #224

**Comment by 8bitPit** [comment] 2020-02-26 14:17
Duplicate of #224

**Closed by 8bitPit** 2020-02-26 14:17 UTC
Labels: duplicate
