### ISSUE TITLE
Looking for a feature like any view for immediate notification 

### ISSUE THREAD

**Issue by sketcharsh** [8bitPit/Niagara-Issues#1847] opened 2022-02-02 09:38 UTC
I'm looking for a feature where I can see my notification from home screen (Not summary) like the one where I can see from favorite pop up but it's only visible for pop up so I'm suggesting if there's any view like notification summary view or popup notification view (Personally I like popup design, it's material) which can display instant notification and I can see from home screen.
Thanks

**Comment by TFackler** [comment] 2022-03-02 19:12
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/152
Please see https://help.niagaralauncher.app/article/35-notification-section

**Closed by TFackler** 2022-03-02 19:12 UTC
Labels: duplicate
