### ISSUE TITLE
Do not disturb icon, Flight mode icon near the time widget

### ISSUE THREAD

**Issue by praveenchandranpk** [8bitPit/Niagara-Issues#1360] opened 2020-09-11 15:41 UTC
It would be nice if we can have some icons like the above mentioned near the time widget. Sometimes I put my phone on do not disturb or flight mode and then forgets about it because the status bar is hidden. It would be very helpful if there's icon near the time widget for that.

**Comment by Rod911** [comment] 2020-09-14 20:01
Duplicate of #1226

**Closed by Rod911** 2020-09-14 20:01 UTC
Labels: duplicate
