### ISSUE TITLE
Notification dots not working after updating. 

### ISSUE THREAD

**Issue by mikey1975** [8bitPit/Niagara-Issues#168] opened 2018-09-10 08:49 UTC
After updating, my notification dots and messages previews stopped working.

**Comment by Montell2099** [comment] 2018-09-12 07:12
How do these notification dots look? I've used the launcher for a couple of days, but I have yet to see those dots even though it's activated in the settings.

**Comment by 8bitPit** [comment] 2018-09-12 09:14
@mikey1975 
Have you tried to restart your phone?

@Montell2099:

![screenshot3](https://user-images.githubusercontent.com/9284845/45414966-d4f7a700-b67c-11e8-9ef2-88509ad970ab.png)

**Comment by mikey1975** [comment] 2018-09-12 12:11
Have restarted my phone several times, at first no effect. Today noticed
notifications on the home screen have reappeared, but only for Google
Messages.
Also activated the weather option in settings, granted location permission,
but weather icon doesn't always shows. Tapping the foreseen space next to
the date does bring up the Google weather page.

**Comment by Montell2099** [comment] 2018-09-12 17:13
@8bitPit
I've also tried restarting my phone & toggling the option on and off. I've never seen these notification dots, I'm on a Pixel 2 with Pie.

**Comment by 8bitPit** [comment] 2018-09-15 16:01
@mikey1975, @Montell2099: did you grant the launcher notification access and enabled notification dots in Niagara AND in Androids settings? Furthermore Do not disturb restrictions could be turned on.

![image](https://user-images.githubusercontent.com/9284845/45550148-5f313e00-b82a-11e8-82d5-51abe2f6a1d7.png)
![image](https://user-images.githubusercontent.com/9284845/45550179-6f491d80-b82a-11e8-8d46-772922de164f.png)

**Comment by mikey1975** [comment] 2018-09-19 07:50
Yes, checked all settings, also cleaned app data, and started from the
beginning.
After a while, the app preview messages start showing, and occasionally the
weather icon shows up.

**Comment by 8bitPit** [comment] 2018-09-19 07:59
@mikey1975 Ok... What phone do you have?

**Comment by mikey1975** [comment] 2018-09-20 07:43
Oneplus 3T.

**Comment by 8bitPit** [comment] 2019-03-07 10:38
Duplicate of #588

**Closed by 8bitPit** 2019-03-07 10:38 UTC
Labels: bug
