### ISSUE TITLE
New options to align favorites view

### ISSUE THREAD

**Issue by JanJenicek** [8bitPit/Niagara-Issues#1970] opened 2022-06-02 11:44 UTC
### Is your feature request related to a problem?

I always struggle when the icons are scrolled below view as show below in middle.
Base setup: | Behavior not ok for me: | Expected:
:---------------:|:-------------------------------:|:-------------------:
<img src="https://user-images.githubusercontent.com/49712371/171618815-16a41158-74e2-4e79-a189-f99ebafc9199.png" width="270" height="570"> | <img src="https://user-images.githubusercontent.com/49712371/171618908-4ad333c8-c20e-489b-9a41-423a6abfea28.png" width="270" height="570"> | <img src="https://user-images.githubusercontent.com/49712371/171618935-24e75900-61e1-4b4a-b031-dad77b5bad6c.png" width="270" height="570">

### Describe the solution you'd like

Add option to select to which point the favorites should be aligned.
New button on "Move widget" view | button moves anchor point between red lines
:---------------------------------------------:|:--------------------------------------------------------------------------------:
<img src="https://user-images.githubusercontent.com/49712371/171621429-20c04b63-51a6-4fff-bc0c-e6b8003a45d5.png" width="270" height="570"> | <img src="https://user-images.githubusercontent.com/49712371/171621454-3995a447-dd65-42de-898f-7b2c9dd73f8a.png" width="270" height="570">

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Just-SKY** [comment] 2022-06-15 01:46
It would be great if the media widget goes up instead of pushing favorites down which is annoying. This is something I've been thinking for a while.

**Comment by Amorphous404** [comment] 2022-12-12 13:59
Fixed in v1.8.0 🎉

🎵 Media Widget · If you move the Niagara Launcher past its default position, the media widget begins to move the widget up instead of the favorites down. Currently, this is not supported if you replace Niagara’s clock with a widget.

https://medium.com/niagara-launcher/going-global-6bb58c2d6bb7#:~:text=%F0%9F%8E%B5-,Media%20Widget,-%C2%B7%20If%20you

**Closed** 2022-12-12 14:00 UTC
Labels: good issue

**Comment by Amorphous404** [comment] 2022-12-13 13:22
Just noticed it was a duplicate of #1669
