### ISSUE TITLE
Google button over Notification Popups

### ISSUE THREAD

**Issue by IdmFoundInHim** [8bitPit/Niagara-Issues#795] opened 2019-03-14 19:58 UTC
The Google button does not go behind the pop-up when swiping on an app. Because of this, it blocks some of the notification action buttons.

**Comment by 8bitPit** [comment] 2019-03-15 12:00
Have you updated to the latest Niagara version (0.7.5a4)? If not, does it always happen?

**Comment by IdmFoundInHim** [comment] 2019-03-16 16:28
I am on 0.7.5a4 and it does always happen.
Samsung Galaxy Note5 Verizon on Android 7 (Nougat) Build NRD90M.N930VVRS3CRH1

**Comment by 8bitPit** [comment] 2019-03-18 16:26
That’s strange it does work on my device (Essential phone, Pie:
![image](https://user-images.githubusercontent.com/9284845/54545934-f5dde380-49a2-11e9-9098-51ddbdf124e9.png)
Sorry for the inconvenience.

**Comment by disacrol** [comment] 2019-03-22 23:34
Maybe it happens only when swiping to check notifications?

**Comment by disacrol** [comment] 2019-04-02 05:14
@IdmFoundInHim Just checked, not reproducible for me at all either. Could you retest with the latest version?

**Comment by IdmFoundInHim** [comment] 2019-04-06 21:03
Still happening on 0.7.7

**Comment by IdmFoundInHim** [comment] 2019-05-13 01:30
![Screenshot_20190512-212900](https://user-images.githubusercontent.com/30935172/57590995-176bcf00-74fd-11e9-8ef6-439d67015ba7.png)
Sorry, I had issues the first time I tried to upload it and then forgot about it.

**Comment by 8bitPit** [comment] 2019-05-13 19:40
Thanks @IdmFoundInHim. Again, I'm very confused by this, because you seem to be the only one having this issue. Are there similar glitches occurring on other apps and do you use a custom ROM?

**Comment by IdmFoundInHim** [comment] 2019-05-15 12:00
No

**Comment by khamdany43** [comment] 2019-05-26 11:20
I have same issue before. i reset factory my phone, after reset the problem is fixed then i uninstall some bloatware and google music, photos, etc. Then the problem happened again.

**Comment by 8bitPit** [comment] 2019-09-01 20:55
Because this bug doesn't happen on most devices, I can't fix it easily (because it doesn't occur on my test devices) and because this only is a minor inconvenience, I won't fix this, sorry.

**Closed by 8bitPit** 2019-09-01 20:55 UTC
Labels: bug, question, wontfix

**Comment by disacrol** [comment] 2019-10-22 22:14
@8bitPit: Just one final regard: @IdmFoundInHim reported to be using Nougat (Samsung Note 5), and I noticed @khamdany43 may also be using Nougat (Wiko Harry) - see his other issue #883 (sorry @khamdany43, not stalking you, I swear) :-)

So maybe this is an issue with Android 7? Those two devices do not share much hardware specs (similar GPU could be the root cause but that seems not to be the case). Not that it makes it worth it to reopen this issue, since nougat is ramping down quite fast, but I thought I should share.

**Comment by khamdany43** [comment] 2019-10-23 02:15
After i update to 0.9.6 the problem is solved. I don't know what causes it but i'm using android nougat (7.0)

**Comment by disacrol** [comment] 2019-10-23 12:41
Good to know, not a problem anymore then!

**Comment by 8bitPit** [comment] 2019-10-23 12:53
Great then :)
