### ISSUE TITLE
feature require...

### ISSUE THREAD

**Issue by StageGuard** [8bitPit/Niagara-Issues#763] opened 2019-02-17 12:02 UTC
it doesnt support chinese pinyin sort... plz add this feature. in addition, it also has bugs on search chinese name app.(e.g : i search "相册"(gallery)) and the result appears. but it doesnt appears when i search "册" ).

**Comment by 8bitPit** [comment] 2019-02-18 09:56
Duplicate of #234

**Closed by 8bitPit** 2019-02-18 09:56 UTC
Labels: duplicate
