### ISSUE TITLE
Add a dock for multi tasking while in app

### ISSUE THREAD

**Issue by imkinger** [8bitPit/Niagara-Issues#2343] opened 2023-07-31 09:20 UTC
### Is your feature request related to a problem?

When using the niagra launcher on tablet like a tab s8
the dock from the Samsung launcher disappears (since it belongs to samsungs UI)
its one of the things that stopping me from using niagra on my tablet

### Describe the solution you'd like

Have your own dock option that resemebels samsungs one
or find a way that it would be a part of niagra launcher itself

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-07-31 10:11
Hi @imkinger, Thank you for reaching out to us!

>When using the niagra launcher on tablet like a tab s8
the dock from the Samsung launcher disappears (since it belongs to samsungs UI)

Unfortunately, this issue is from the Samsung side,  there's nothing much we can do to fix it. We suggest reaching out to Samsung and making your voice heard since they are the only ones who can do something about this matter.

For more detailed explanation on the issue, please refer to this article:
[Galaxy Taskbar Not working](https://help.niagaralauncher.app/article/135-galaxy-z-folds-taskbar-not-working)

> Have your own dock option that resemebels samsungs one

Apologies, we have no plans to create a custom Taskbar solution. Developing one would demand significant time and effort, and it won't be as functional as the system-level taskbar and cause other potential issues. Moreover, implementing it would necessitate using system-level permissions like "app usage" and "display over apps" which is discouraged by Google. You can find more information about this [here](https://www.xda-developers.com/android-q-system-alert-window-deprecate-bubbles/).

**Comment by Amorphous404** [comment] 2023-07-31 10:12
-Duplicate of #2025

**Comment by Amorphous404** [comment] 2023-07-31 10:12
- Duplicate of #2025

**Closed** 2023-08-01 01:12 UTC
