### ISSUE TITLE
Touch sensitive scale 

### ISSUE THREAD

**Issue by tng2903** [8bitPit/Niagara-Issues#1214] opened 2020-03-15 10:02 UTC
**Is your feature request related to a problem? Please describe.**
I'm using a device with 21:9 screen ratio, and it's taking a bit strain to the finger scrolling from the top to bottom of the list.
**Describe the solution you'd like**
I wish that there is a way to config the scroll's sensitive so that I can scroll the whole list with only 1/3 the current distance.

This can be control by a simple slider valued from 0.1 to 5 , so I hope this make it :dancer: 

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment] 2020-03-15 15:32
Hi @tng2903, thank you for request, I believe changing the height of the alphabet would solve your issue: https://github.com/8bitPit/Niagara-Issues/issues/334

**Comment by 8bitPit** [comment] 2020-03-15 17:29
Feel free to open the issue again in case my previous reply didn't help.

**Comment by 8bitPit** [comment] 2020-03-15 17:29
Duplicate of #334

**Closed by 8bitPit** 2020-03-15 17:29 UTC
