### ISSUE TITLE
Media controls never launch

### ISSUE THREAD

**Issue by JP-Doyon** [8bitPit/Niagara-Issues#1121] opened 2020-01-02 19:43 UTC
**Describe the bug**
Media player 'widget' appears correctly with SoundCloud but never appears with Spotify

**To Reproduce**
Play Spotify music...

**Smartphone (please complete the following information):**
 - Device: Galaxy s10e
 - Android version: Android 10

**Comment by disacrol** [comment] 2020-01-05 23:30
Exactly which Niagara version?

**Comment by 8bitPit** [comment] 2020-01-08 09:55
Hi @JP-Doyon, please provide further information here: https://github.com/8bitPit/Niagara-Issues/issues/485

**Comment by 8bitPit** [comment] 2020-01-08 09:55
Duplicate of #485

**Closed by 8bitPit** 2020-01-08 09:55 UTC
Labels: bug, duplicate
