### ISSUE TITLE
Quick Screen Lock

### ISSUE THREAD

**Issue by JohnCale47** [8bitPit/Niagara-Issues#867] opened 2019-05-08 14:37 UTC
**Is your feature request related to a problem? Please describe.**

As the launcher doesn't have a lock screen option it would be cool if you add a lock screen button at the bottom where the Google button is..

*Describe the solution you'd like**

Maybe replacing the Google button cause for me that button is useless ..

**Comment by 8bitPit** [comment] 2019-05-12 19:54
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/63

**Closed by 8bitPit** 2019-05-12 19:54 UTC
Labels: duplicate
