### ISSUE TITLE
I wonder if I should leave a space when I open the pop-up. 

### ISSUE THREAD

**Issue by HASH0000FFprint** [8bitPit/Niagara-Issues#2121] opened 2022-11-16 02:57 UTC
### Is your feature request related to a problem?

https://user-images.githubusercontent.com/74079450/202071805-f775e598-b17e-43fa-9629-f5a858a8685a.mp4

If you look at the video, when you open the pop-up, it moves to the left of the icon and opens. Is it really necessary to open it like this? Even if you show the alphabet like that, as you can see from the video, you can't operate it unless you touch it once. 

### Describe the solution you'd like

So why not make the popup open completely to the right of the icon even if you cover the alphabet so that there is something like consistency? 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment] 2022-12-13 13:17
Hey @HASH0000FFprint, thanks for asking. The margin is just for aesthetic purposes.

**Comment by 8bitPit** [comment] 2022-12-27 11:47
Because everything is working as intended, I'll close this issue. Btw, Happy Holidays!

**Closed by 8bitPit** 2022-12-27 11:47 UTC
