### ISSUE TITLE
Show apps with notifications at the top

### ISSUE THREAD

**Issue by Maccer1** [8bitPit/Niagara-Issues#724] opened 2019-01-27 15:05 UTC
I think it would be great to show apps with notifications in the main view (the favourites view) and hide those apps when the notification goes away.

If someone doesn't want an app to show up then the solution would be as simple as disabling notifications for that app from the option inside Android Settings.

**Comment by 8bitPit** [comment] 2019-01-28 19:13
Duplicate of #152

**Closed by 8bitPit** 2019-01-28 19:13 UTC
