### ISSUE TITLE
Widgets go blank after some time

### ISSUE THREAD

**Issue by Jivvy** [8bitPit/Niagara-Issues#1046] opened 2019-11-03 15:00 UTC
**Describe the bug**
After some amount of time, this will happen to widgets: 
![Screenshot_20191103-085623_Niagara Launcher](https://user-images.githubusercontent.com/24281896/68087072-d69fa380-fe17-11e9-9bd8-6452bc50af3a.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - Android version: Android 9 Pie

Tested with the following widgets:
https://play.google.com/store/apps/details?id=com.pies3nscy.clockwidget

**Comment by 8bitPit** [comment] 2019-11-06 08:24
Thanks for the report, I'll upload a patch pretty soon.

**Comment by 8bitPit** [comment] 2019-11-06 08:24
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/952

**Closed by 8bitPit** 2019-11-06 08:24 UTC
Labels: bug, duplicate
