### ISSUE TITLE
Non Latin alphabet sort problem..

### ISSUE THREAD

**Issue by jook1356** [8bitPit/Niagara-Issues#826] opened 2019-04-09 08:38 UTC
I wonder when will be fixed that non-Latin alphabet sort problem.. I waited too long :(

**Comment by 8bitPit** [comment] 2019-04-10 10:27
In the meantime, you could rename your apps, so the get categorized properly.

**Comment by 8bitPit** [comment] 2019-04-10 10:27
#234

**Comment by 8bitPit** [comment] 2019-04-10 10:28
Duplicate of #234

**Closed** 2019-04-10 10:28 UTC
Labels: duplicate
