### ISSUE TITLE
Profile run by wifi connection or other trigger 

### ISSUE THREAD

**Issue by orestesgaolin** [8bitPit/Niagara-Issues#2731] opened 2024-06-03 21:13 UTC
### Is your feature request related to a problem?

I've seen that work profiles are potentially coming later at some point due to being a popular feature request, but I would like to propose a way to automate changing of them woth external triggers like wifi connection change, geofencing, NFC tags or others. 

### Describe the solution you'd like

My specific use case would be related to apps that can only be used when connected to a certain wifi network e.g. Sonos, smart home, NAS client. I would like to hide them from my home screen when outside of the network, however I'd like to see them on main screen when at home. 

Provided that work profiles or similar feature would allow to define list of apps on the home screen, then I imagine they could be driven by certain conditions, wifi network being one of them. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2024-06-06 13:05
Thanks for suggesting this.

Dynamic favorites/profiles would be cool, but we are worried that it would add too much complexity to the launcher's heart, the favorites page.

Once we have decided on a way to support work profiles, we might add other profiles, like a smart folder, which changes depending on some trigger.

I will close this issue since it is a duplicate, but I will post a short summary there.
Duplicate of #1517

**Closed** 2024-06-06 13:05 UTC
Labels: duplicate
