### ISSUE TITLE
Give the option to set a numerical value for the number of most used apps. 

### ISSUE THREAD

**Issue by renevdvorst** [8bitPit/Niagara-Issues#909] opened 2019-06-11 11:38 UTC
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
As of now, there is only an option to limit the number of most used apps, or to not do that. Not only is this a bit vague, a numerical value would allow for more customization.

**Comment by Rod911** [comment] 2019-06-11 11:50
Duplicate of #454

**Closed** 2019-06-11 11:51 UTC
Labels: duplicate
