### ISSUE TITLE
View screentime under clock

### ISSUE THREAD

**Issue by StevenHoutenbos** [8bitPit/Niagara-Issues#2937] opened 2024-09-25 17:37 UTC
### Is your feature request related to a problem?

Recently i have been trying different launchers but in the end i've stuck to Niagara.
What i liked about some other "minimal" launchers is that they show your screentime under the clock.
I think this ticks all the boxes for a simple, impactful, universal and independent feature, and it might help people to keep their screentime down. 

### Describe the solution you'd like

Have the option to view your screen time under the clock, next to the date. (or somewhere else, wherever it looks best)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-10-04 17:16
Hey there, thanks for the suggestion.
Similar ideas have been suggested before, so I’ll close this as a duplicate of #1811. The short answer is that it’s probably coming at some point once we find the time and resources to implement it.

**Closed by NiagaraSupport** 2024-10-04 17:16 UTC
Labels: duplicate
