### ISSUE TITLE
Phone completely freezed in the main screen

### ISSUE THREAD

**Issue by yoancrul** [8bitPit/Niagara-Issues#859] opened 2019-05-03 11:53 UTC
U can't confirm if this is because of the launcher but it's the only beta app i'm currently using, i'm using a S8+ and the hole phone froze, i couldn't turn it off, and since i've been expiriencing a few issues with the launcher lately i'm pretty sure its the launchers fault

**Comment by 8bitPit** [comment] 2019-05-03 13:09
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/803

**Closed by 8bitPit** 2019-05-03 13:09 UTC
Labels: duplicate
