### ISSUE TITLE
Option to not add work apps to favorites

### ISSUE THREAD

**Issue by jjfahner** [8bitPit/Niagara-Issues#2592] opened 2024-02-09 07:19 UTC
### Describe the solution you'd like

The separation between work and personal apps is reasonably well enforced by Android, including suspending notifications outside work hours. 

I would love for Niagara to have an option to not promote work apps to the Favorites section so I can keep them out of sight, or alternatively, but more complicated, to hide them (from favorites/entirely) following the work hours schedule.

This would help people to disengage and maintain a healthy life/work balance.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-02-09 09:47
Hey there, thanks for your request.
This seems to be a duplicate of #2540 / #1517. To summarize the answers, It's not currently being worked on due to different priorities, but I'll tell the others that it's an often requested feature.

**Closed by NiagaraSupport** 2024-02-09 09:47 UTC
