### ISSUE TITLE
Calendars events not showing

### ISSUE THREAD

**Issue by damaras** [8bitPit/Niagara-Issues#2948] opened 2024-10-02 09:53 UTC
### Describe the bug

whenever I open the calendar widget I'm able to see only the events occurring for my default calendar, but not the others I have set up (my main one is outlook, but I also have a Gmail as well as another outlook for work). I've tried toggling on and off the filters in the widget settings and restarting both phone and launcher, but nothing changed 

### Steps to reproduce

Go to Niagara settings
click on features
click on Niagara widget
click on calendar
click on filter 
select the correct events to display

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

CMF phone 1 

### Android version

Android 14

### Screenshots / Screen recordings

![Screenshot_20241002-103654~2](https://github.com/user-attachments/assets/54a26577-ffd3-4b98-babf-0feed7f48a30)

**Comment by aFaithfulOne** [comment] 2024-10-03 12:00
Did you check the FAQ? I had the same issue, went into the Outlook app, activated the synchronization and then it worked.

**Comment by NiagaraSupport** [comment] 2024-10-04 16:32
> Did you check the FAQ? I had the same issue, went into the Outlook app, activated the synchronization and then it worked.

Are you referring to #2949? And if so did it fix the issue perhaps?

**Comment by aFaithfulOne** [comment] 2024-10-04 17:07
No, I am referring to this thread (events not showing in the widget). This FAQ (linked below) fixed it for me at least.

https://help.niagaralauncher.app/article/76-calendar-faq

The issue #2949 I posted myself still persists.

**Comment by NiagaraSupport** [comment] 2024-10-05 11:57
Alright, thanks for the clarification.

**Comment by NiagaraSupport** [comment] 2024-10-05 12:53
I'll close this as a duplicate of #2924 and reference it there. Please refer to that ticket for future updates.

**Closed by NiagaraSupport** 2024-10-05 12:53 UTC
Labels: bug
