### ISSUE TITLE
Choose Icon from Gallery

### ISSUE THREAD

**Issue by McFaul4** [8bitPit/Niagara-Issues#2163] opened 2022-12-26 15:04 UTC
I wanted to select a vector graphic for a single App. In some other launchers (Nova, Action) there is a "choose from gallery" button and I would love to see this in Niagara! And it would perfectly fit with the Icon Assistant.

**Comment by Amorphous404** [comment] 2022-12-26 15:12
Sorry for the sack of simplicity, we decided not to implement this feature.

![Screenshot_2022-12-26-20-40-05-11_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/96917972/209562420-7538b023-90fe-457d-8a20-8f3c93d0c6dd.jpg)
https://help.niagaralauncher.app/article/97-edit-app-icons-and-names

**Comment by Amorphous404** [comment] 2022-12-26 15:25
Duplicate of #581

**Closed** 2022-12-26 15:25 UTC
Labels: duplicate
