### ISSUE TITLE
More weather data

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#1783] opened 2021-12-23 23:34 UTC
### Is your feature request related to a problem?

Well the problem is weather conditions doesn't rely solely on the temperature and chance of precipitation alone... The wind plays a major role in a lot of places... 

### Describe the solution you'd like

Provide air data with pollution statistics in the agenda widget with an option to toggle it on and off for the users whom it would be irrelevant

**Comment by luxcalor** [comment] 2022-01-02 18:26
Wind data would be very heloful for where I live

**Comment by Maxr1998** [comment] 2022-04-08 15:52
Duplicate of #1755. We don't plan to implement this at the moment, please see our reasoning there.

**Closed** 2022-04-08 15:53 UTC
Labels: duplicate
