### ISSUE TITLE
Please offer a different, more "serious" alphabet scrolling animation

### ISSUE THREAD

**Issue by chareos** [8bitPit/Niagara-Issues#662] opened 2018-12-20 22:57 UTC
Please offer a different, more "serious" alphabet scrolling animation

The "wave" looks playful, but I'd rather suggest a more minimalist, discrete and serious scrolling.
Keep the bubble letter (neat!) just remove the wave animation. That would do.

**Comment by 8bitPit** [comment] 2018-12-23 12:15
Duplicate of #361

**Closed by 8bitPit** 2018-12-23 12:15 UTC
Labels: duplicate
