### ISSUE TITLE
To-do list 

### ISSUE THREAD

**Issue by ashmit1795** [8bitPit/Niagara-Issues#2329] opened 2023-07-11 17:34 UTC
### Describe the solution you'd like

I want You to add a To-do list button in "Your Agenda" section. The list don't require integration with the calendar (events). You add this button in best possible place without compromising the simplicity of the launcher. This feature will make the launcher more personalized. I am requesting you this feature because the calendar app doesn't allows to create a To-do list, as a result we only see today's pre-scheduled events in "Your Agenda" section.

Also, I request you a another feature - Allow to add custom text(50 characters) just below the clock widget of the home.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-07-12 18:13
Hi @ashmit1795, Thank you for you suggestions!

1) The team is currently exploring the option of incorporating a to-do list in Niagara. Please refer to issue #1285 for further details.

- Duplicate of #1285

2) I'm sorry, but there are no plans to add this option. However, you can achieve the same with the help of third-party widgets apps like [KWGT Kustom Widget Maker](https://play.google.com/store/apps/details?id=org.kustom.widget) or [Text Basic](https://play.google.com/store/apps/details?id=com.denizk0461.textbasic)

Demo:
![Text Widget.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/2bd4c120-5588-494d-b268-40d70ed95cbf)

Note: Kindly keep one request per ticket :)

**Comment by ashmit1795** [comment] 2023-07-12 18:19
Thank You for acknowledging the idea. Hope you will definitely add this feature in future..

**Closed** 2023-07-12 18:28 UTC
