### ISSUE TITLE
Notification not dismissing on swipe

### ISSUE THREAD

**Issue by rainaakshay** [8bitPit/Niagara-Issues#766] opened 2019-02-20 13:03 UTC
on expanding the notification box, it doesn't dismiss notifications on swipe. On poco f1 running android 9 miui 10

**Comment by 8bitPit** [comment] 2019-02-20 16:40
Thanks for the report, I noticed the bug as well, but unfortunately I couldn't fix it yet.

**Comment by prabhumns** [comment] 2019-03-01 06:45
I faced the same issue with same device. But i restarted my device once. It is fixed now. Try restarting ur device once.

**Comment by 8bitPit** [comment] 2019-03-05 12:56
I still couldn't figure out the root cause, sorry. Btw @prabhumns, restarting Niagara (you can do that in Niagara's settings > Advanced) should be enough.

**Comment by 8bitPit** [comment] 2019-04-16 20:23
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/428

**Closed by 8bitPit** 2019-04-16 20:23 UTC
Labels: bug

**Comment by nijoachacko** [comment] 2019-08-05 16:53
It sane as on my Xiaomi MiA1
