### ISSUE TITLE
Background tint even on home screen

### ISSUE THREAD

**Issue by Manu99it** [8bitPit/Niagara-Issues#2694] opened 2024-05-18 23:42 UTC
### Is your feature request related to a problem?

I'm always frustrated when I really like a wallpaper but can't really use it because it compromise readability.

### Describe the solution you'd like

Would be awesome a separate setting to use the same tint that there is when in the app list even on home screen

Es: I would on this screeen

![Screenshot_20240519-013045](https://github.com/8bitPit/Niagara-Issues/assets/19348772/1b171a40-5626-4383-8917-5599775db0aa)

The same tint there is when in app list. But with a separate setting
![Screenshot_20240519-013907](https://github.com/8bitPit/Niagara-Issues/assets/19348772/3313cfb5-dc74-4e6a-94bc-9b0ec7dcce47)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-05-22 14:34
Hey there, thanks for the suggestion.
I'll close this as a duplicate of #2342.

**Closed by NiagaraSupport** 2024-05-22 14:34 UTC

**Comment by Manu99it** [comment] 2024-05-22 15:29
@NiagaraSupport not to be rude, but I didn't request the same thing. I am not interested in a dim scale but in applying the same dim there is in app list also in the favourites screen
