### ISSUE TITLE
Quick note-taking feature

### ISSUE THREAD

**Issue by AuelY** [8bitPit/Niagara-Issues#2052] opened 2022-09-10 02:29 UTC
### Is your feature request related to a problem?

If I want to quickly write a note to remind myself of something later, I always have to open an app to see it. It would be easier and clearer to rather see or create it right on my home screen. I believe that won't affect the simplicity of the launcher either.

### Describe the solution you'd like

Another section (notes) inside the "Your agenda" area. Tapping a + button would open a writing field and finally creating a note with a hook button. Also an option to edit or delete for each created note.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Just-SKY** [comment] 2022-09-10 14:11
I created a similar ticket, but sadly this was their response. However, I still consider a would be a great features for Niagara launcher, and I hope they change their mind about this feature. 
#1776
However, if you still want a quick-note taking feature which would fit perfectly for niagara, you can use this https://play.google.com/store/apps/details?id=com.stuff.todo

Here is the way in which I implemented this widget. You can use its default sections, or you can create your own ones (groceries, school, etc.). 
However, for this purpose you  can delete all of them and create a single one (quick notes). You can adjust the size off it using niagara launcher; also, it also allows you to change **background  colors, fonts, etc.**  You can create backup at any time of your notes.

I hope this could help you. 

![Screenshot_2022-09-10-07-58-18-140_bitpit launcher](https://user-images.githubusercontent.com/72170242/189486768-247bec83-b7cb-4152-9e25-af4a17a4460a.jpg)

**Comment by Just-SKY** [comment] 2022-09-10 14:20
I created a similar ticket, but sadly this was their response #1776 . However, I still consider it would be a great features for Niagara launcher, and I hope they change their mind about this feature. 

However, if you still want a quick-note taking feature which would fit perfectly for niagara, you can use this https://play.google.com/store/apps/details?id=com.stuff.todo

Here is the way in which I implemented this widget. You can use its default sections, or you can create your own ones (groceries, school, etc.). 
However, for this purpose you  can delete all of them and create a single one (quick notes). You can adjust the size off it using niagara launcher; also, it also allows you to change **background  colors, fonts, etc.**  You can create backup at any time of your notes.

I hope this could help you. 
![Uploading Screenshot_2022-09-10-08-16-58-439_bitpit.launcher.jpg…]()

**Comment by Just-SKY** [comment] 2022-09-10 14:20
I created a similar ticket, but sadly this was their response #1776 . However, I still consider it would be a great features for Niagara launcher, and I hope they change their mind about this feature. 

However, if you still want a quick-note taking feature which would fit perfectly for niagara, you can use this https://play.google.com/store/apps/details?id=com.stuff.todo

Here is the way in which I implemented this widget. You can use its default sections, or you can create your own ones (groceries, school, etc.). 
However, for this purpose you  can delete all of them and create a single one (quick notes). You can adjust the size off it using niagara launcher; also, it also allows you to change **background  colors, fonts, etc.**  You can create backup at any time of your notes.

I hope this could help you. 

![Screenshot_2022-09-10-08-16-58-439_bitpit launcher](https://user-images.githubusercontent.com/72170242/189487576-82338c8c-f494-4335-a10b-3f962ef45f76.jpg)

**Comment by AndyL964** [comment] 2022-09-12 01:24
> I created a similar ticket, but sadly this was their response #1776 . However, I still consider it would be a great features for Niagara launcher, and I hope they change their mind about this feature.
> 
> However, if you still want a quick-note taking feature which would fit perfectly for niagara, you can use this https://play.google.com/store/apps/details?id=com.stuff.todo
> 
> Here is the way in which I implemented this widget. You can use its default sections, or you can create your own ones (groceries, school, etc.). However, for this purpose you can delete all of them and create a single one (quick notes). You can adjust the size off it using niagara launcher; also, it allows you to change **background colors, fonts, etc.** You can create backup at any time of your notes.
> 
> I hope this could help you.
> 
> ![Screenshot_2022-09-10-08-16-58-439_bitpit launcher](https://user-images.githubusercontent.com/72170242/189487576-82338c8c-f494-4335-a10b-3f962ef45f76.jpg)

You might like this too: https://play.google.com/store/apps/details?id=com.goyourfly.bigidea

It's a floating shortcut/widget note-taking app that can be accessed anywhere, anytime.

**Comment by Just-SKY** [comment] 2022-09-12 03:11
Looks great 😆! Sadly, it isnt offline.

**Comment by TFackler** [comment] 2022-11-19 10:53
As @Just-SKY mentioned, this issue is a duplicate of #1776 , thus please head there for more information.

Also thank you for posting your own solution, it's much appreciated 😃

**Closed by TFackler** 2022-11-19 10:53 UTC
Labels: duplicate
