### ISSUE TITLE
A little suggestion. Again.

### ISSUE THREAD

**Issue by Aweotranx** [8bitPit/Niagara-Issues#1007] opened 2019-09-24 22:42 UTC
Whereas my last comment was difficult to understand. So I will use the translator.

As a small recommendation, I wish you could place shortcuts in the applications menu. It would make it more dynamic.

**Comment by Martin5001** [comment] 2019-09-25 07:08
This is probably the same request as #62?

**Comment by 8bitPit** [comment] 2019-09-29 18:27
Yeah, I also believe this is a duplicate of #62.

**Closed by 8bitPit** 2019-09-29 18:27 UTC
Labels: duplicate
