### ISSUE TITLE
App icon of one app is bugged after exiting app

### ISSUE THREAD

**Issue by 0alfred0** [8bitPit/Niagara-Issues#1926] opened 2022-04-19 17:05 UTC
### Describe the bug

When opening and closing BBC news the icon is bugged and dragging along the home screen for a while. It is the only app I have experienced it so far. OnePlus 8 Pro new android 12 update installed today.

### Steps to reproduce

Open BBC news
Close app
Scroll

### Device name

OnePlus 8 pro

### Android version

Android 12

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/68697125/164057509-2f0837e9-5536-4c42-83e0-8a1f8a2dffaf.mp4

**Comment by Oddward** [comment] 2022-04-19 21:47
Is it consistently only with that app? This is generally a known issue that seems to be caused by the app closing animation's API, atm it's up to Google to fix. You should be able to avoid it by not trying to navigate before the closing animation is complete. 

More info here: https://help.niagaralauncher.app/article/7-gesture-navigation#:~:text=The%20app%20close-,animation,-left%20an%20icon

If it's the random rare instance it's another weird render bug that can't reliably be reproduced

**Comment by 0alfred0** [comment] 2022-04-20 05:23
Yes I have only experienced with this app. I can reproduce every time. No big deal for me I'll wait for a fix.

**Comment by 8bitPit** [comment] 2022-06-04 06:02
Sorry, this ticket was closed by accident, I'll reopen it

**Comment by 8bitPit** [comment] 2022-06-04 06:15
oof

**Comment by 0alfred0** [comment] 2022-12-13 11:46
Thanks for following up. It seems to be fixed. Thank you.On Dec 13, 2022 12:29, Peter Huber ***@***.***> wrote:
Hey @0alfred0, we tweaked the app close animation in v1.8. Does the issue still occur?

**Closed** 2022-12-13 17:38 UTC
Labels: bug, blocked

**Comment by 8bitPit** [comment] 2022-12-14 17:38
Awesome, thanks for letting us know @0alfred0 :)
