### ISSUE TITLE
Suggestion: To Introduce Stackable Widgets In Niagara Launcher 

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1879] opened 2022-03-21 18:09 UTC
### Describe the solution you'd like

https://user-images.githubusercontent.com/96917972/159335843-1edd2732-6251-4e25-afdd-4cc5f6de4c1e.mp4

Please, If You Could Find A Way To Add Stackable Widget In Niagara Launcher, That would be so cool 😎,

I Created A Mock Up, It Looks So Amazing On Niagara, It Works Flawlessly Even With Scroll Able And KWGT Widgets.

Looking Forward To It 🙂

**Comment by Oddward** [comment] 2022-03-23 12:08
Duplicate of [this issue](https://github.com/8bitPit/Niagara-Issues/issues/1330), and there are other duplicates already lol. This request doesn't fit the launcher's design as much as it seems. The goal isn't to incentivize adding more widgets.

**Closed** 2022-03-23 12:08 UTC

**Comment by TFackler** [comment] 2022-03-31 08:00
We will be thinking about this, please see #1330 for more information.

We will keep this issue closed, since it is still considered a duplicate.
