### ISSUE TITLE
Niagara widget: Show next alarm status

### ISSUE THREAD

**Issue by pratyakshm** [8bitPit/Niagara-Issues#1842] opened 2022-01-28 11:42 UTC
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I want to be able to see my next alarm's status in **Niagara widgets**. 
The alarm's position might be in one of the following places:
- A small font (size equal to the text size of other places such as weather, date, etc.)
- Next to date
- Next to battery percentage 
- Next to the current time display, but it might not look as good

I believe that if the alarm status is integrated into the Niagara widgets, users won't need to open their Clock app to see the alarm status anymore. It's good information at a glance.

**Comment by Maxr1998** [comment] 2022-01-28 12:41
Duplicate of #4.

**Closed** 2022-01-28 12:41 UTC
Labels: duplicate
