### ISSUE TITLE
Export and import settings

### ISSUE THREAD

**Issue by jackuars89** [8bitPit/Niagara-Issues#1936] opened 2022-04-24 11:07 UTC
I couldn't see an option on how to export settings and import them if required. It's a pain right now to reset the settings to how I wanted when the app was uninstalled.

**Comment by Oddward** [comment] 2022-04-25 04:39
Duplicate of #222 , and it's mentioned in the knowledge base article: [Backup settings](https://help.niagaralauncher.app/article/37-backup-settings)

Tl;dr: It currently already uses a Google auto backup solution, but it's a hit or miss, so a different method is planned.

**Closed by Oddward** 2022-04-25 04:39 UTC
