### ISSUE TITLE
Wrong Icons size Galaxy S8 resolution change

### ISSUE THREAD

**Issue by javiergmxd** [8bitPit/Niagara-Issues#772] opened 2019-02-26 23:06 UTC
The icon size is wrong when I change the screen resolution on galaxy s8 by power saving or manually in phone settings

**Comment by disacrol** [comment] 2019-02-27 09:17
You mean that icons should remain the same size?

**Comment by 8bitPit** [comment] 2019-02-28 23:32
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/297

**Closed by 8bitPit** 2019-02-28 23:32 UTC
Labels: duplicate
