### ISSUE TITLE
Launcher should return to default Favourites view after quick-locking

### ISSUE THREAD

**Issue by DetourToNirvana** [8bitPit/Niagara-Issues#2311] opened 2023-06-18 01:56 UTC
### Is your feature request related to a problem?

Hi, new Pro user here, and I love the simplicity of Niagra, and my top reason for using it is the speed of access to everything like search, widgets, calendar, weather and so much more.

One thing i enabled right away was the quick-lock. I noticed how Niagra actually scrolls down in the Apps List when i lock the screen using quick-lock. This makes logical sense, but when I unlock my screen the next time, I would prefer so much more to see my Favourites again, instead of ending up in a random point in my Apps List.

### Describe the solution you'd like

I see 2 possible solutions, both of which resolve my issue:

- When the screen is locked using the quick-lock, the next time I unlock my phone, Niagra should return to the default Favourites view, by default.
- An option to set my preference to not "Remember position in Apps List after locking screen"

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-06-21 01:31
If you lock your phone via double tapping the alphabet scroller and unlock the phone immediately (< 3 seconds), Niagara Launcher returns you to the last position (app list) instead of the main home screen. This is intentional and saves you time if you accidentally locked the phone.

More info here;
[Pressing home doesn't show favorites](https://help.niagaralauncher.app/article/86-pressing-home-doesnt-show-favorites)

- Duplicate of #1989

**Closed** 2023-06-21 01:33 UTC

**Comment by DetourToNirvana** [comment] 2023-08-20 06:46
Thanks for the response. I confirm that this works, and actually is a more reasonable way to do it. Thank you.
