### ISSUE TITLE
App lock

### ISSUE THREAD

**Issue by Sohaib-mujtaba** [8bitPit/Niagara-Issues#2305] opened 2023-06-16 01:12 UTC
### Is your feature request related to a problem?

The most of the phones have their own app lock feature but some phones like mine don't have  an integrated app lock feature!
And if the app lock provided, in many cases it is  not easily accessible for some users.
If we use a third party app lock, it may consume more battery and it is also not as reliable as Niagara launcher for security.
So, it would be great if you integrate the app lock feature in the launcher itself.

### Describe the solution you'd like

Please add an app lock feature to lock apps conveniently without the hassle of third-party apps. 
You can also add a fake app crash feature to disguise the app lock, please don't show the app which is locked by highlighting it with a lock symbol or anything like that because that app lock is for user privacy and not to exhibit app lock, if the App locked is highlighted it will be easily visible. 
So I request you to introduce just an app lock feature with a fake app crash message when clicked, in the launcher.
I hope this feature is as simple as 3 to 4 clicks and is necessary for many of us.
And it also doesn't add complexity if it’s not being used.
Thanks and I hope you will work on this universal problem in the next update. Great app 👍 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-06-16 15:58
Hi @Sohaib-mujtaba, Thanks for such a detailed request! Unfortunately, we do not plan to integrate the app-lock feature into our launcher because non-system launchers cannot hide and lock apps entirely (without root permissions); e.g., they still appear in Android's settings, and you can launch them with another launcher. A password lock option adds only a pseudo layer of security on third-party launchers.

For more info, please refer to this article: 
[Password-Protection for Apps](https://help.niagaralauncher.app/article/63-password-protected-hidden-apps)

- Duplicate of #332

**Closed** 2023-06-16 15:59 UTC

**Comment by Sohaib-mujtaba** [comment] 2023-06-16 17:54
Thanks for replying. I understand.
Keep up the great work 👍

**Comment by Sohaib-mujtaba** [comment] 2023-06-16 17:59
Thanks for your response.
