### ISSUE TITLE
Universal Search integration

### ISSUE THREAD

**Issue by luchrisatuwdotedu** [8bitPit/Niagara-Issues#683] opened 2018-12-31 15:22 UTC
Currently, a user has three ways to app search. Additionally, the Google button provides the internet search option. I think that universal search, such as Sesame shortcuts built into the button, could reduce redundant app search options and combine all the search options currently within the launcher. This could also be achieved by integrating a gesture that allows the home press to be replaced with an app opening so a user could just access sesame that way. I feel like a one stop shop style search is in line with the minimalistic goals of this launcher.

**Comment by 8bitPit** [comment] 2018-12-31 15:55
Duplicate of #58 / #88

**Closed by 8bitPit** 2018-12-31 15:55 UTC
Labels: duplicate
