### ISSUE TITLE
Remove "uninstall" option from apps that cannot be uninstalled

### ISSUE THREAD

**Issue by zroncarij** [8bitPit/Niagara-Issues#1266] opened 2020-04-26 23:21 UTC
Such as:

Stock phone
Stock calendar
Stock camera
Stock email
QuickMemo+

Moreover, if someone wants to disable the app add that option instead.

**Comment by Martin5001** [comment] 2020-04-27 07:27
Yes, the option to disable the app instead is a good idea.

**Comment by 8bitPit** [comment] 2020-05-02 10:06
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1053

**Closed by 8bitPit** 2020-05-02 10:06 UTC
Labels: duplicate
