### ISSUE TITLE
Bowser Page Add to Home

### ISSUE THREAD

**Issue by Kilo-Five** [8bitPit/Niagara-Issues#838] opened 2019-04-17 18:19 UTC
In most bowsers there is an option to add a webpage to home so it will appear as a shortcut in the app list. Niagara does not seem to accept these shortcuts though. 

It would be very nice to have as many employers use web based applications that need to be accessed frequently.

**Comment by 8bitPit** [comment] 2019-04-18 12:03
Yeah, I agree, that would be cool.

**Comment by 8bitPit** [comment] 2019-04-18 12:04
Duplicate of #62

**Closed by 8bitPit** 2019-04-18 12:04 UTC
Labels: duplicate
