### ISSUE TITLE
Hitting enter in search launches first item. 

### ISSUE THREAD

**Issue by prediscover** [8bitPit/Niagara-Issues#130] opened 2018-09-08 03:43 UTC
This makes it so you can just type a couple letters and hit enter to launch. Makes things even faster.

**Comment by pradyw** [comment] 2018-09-08 05:00
Duplicate of #114

**Comment by 8bitPit** [comment] 2018-09-08 08:35
Thank you @pradyw for linking

**Closed by 8bitPit** 2018-09-08 08:35 UTC
