### ISSUE TITLE
Home list suggestion

### ISSUE THREAD

**Issue by sawtdakhili** [8bitPit/Niagara-Issues#1344] opened 2020-08-22 13:35 UTC
Since the devices we use are getting larger, I usually move the Home List more toward the bottom of the screen to reach easily with my thumb. But when my music app widget is on, it pushes the last apps of the list off screen.

Can the 'move home live' option work from the bottom of the list instead of the top?

P.S Also if there was an option to put the time/date/weather at the bottom it'd be cool.

**Comment by 8bitPit** [comment] 2020-09-03 04:15
Thanks for the suggestion, but I think it's a duplicate of: https://github.com/8bitPit/Niagara-Issues/issues/243

**Comment by 8bitPit** [comment] 2020-09-03 04:15
Duplicate of #243

**Closed by 8bitPit** 2020-09-03 04:15 UTC

**Comment by sawtdakhili** [comment] 2020-09-03 08:35
That's not a duplicate. What I am suggesting here is a completely different approach to the problem and it ads more versatility ti the positionning of the launcher. It's based on the fact that our devices are getting bigger, so having the home apps starting at the bottom of the screen is much more reachable.

**Comment by 8bitPit** [comment] 2020-09-16 07:50
Sorry, I misread your post. For the sake of simplicity I think it's better to just provide one alignment option.
