### ISSUE TITLE
App scrollbar doesn't support Chinese pinyin

### ISSUE THREAD

**Issue by xinkunZ** [8bitPit/Niagara-Issues#744] opened 2019-02-06 13:40 UTC
All Chinese app names are labeled with '#'.
I think you should use pinyin4j to make Chinese app name to pinyin then sort them in abcd scrollbar

**Comment by 8bitPit** [comment] 2019-02-06 18:08
Thanks for the suggestion; the request is already on my list :) #234

**Comment by 8bitPit** [comment] 2019-02-06 18:08
Duplicate of #234

**Closed by 8bitPit** 2019-02-06 18:08 UTC
