### ISSUE TITLE
Dim Wallpaper 

### ISSUE THREAD

**Issue by ajaykhosh** [8bitPit/Niagara-Issues#2342] opened 2023-07-30 16:37 UTC
### Is your feature request related to a problem?

I want more dark dim or lite dim. I know Already default dim option, but not a adjustable options

### Describe the solution you'd like

Please create dim scale management button 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-07-30 20:23
Thank you for your feedback! Currently, we don't have plans to add a dim scaling option. However, if many users request this feature, we'll reconsider and update the issue accordingly. In the meantime, you can use an app like [Muzei](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei) to adjust the brightness to your preference.

Demo:
![IMG_20230731_015055.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/245eae7d-b900-4b41-af6d-cedc53332f74)

We comprehend the purpose of this feature, but we are highly cautious about the features we integrate into the launcher, as once they are incorporated, we cannot remove them. We appreciate your understanding. To learn more about our design guidelines, please refer to this article:
[Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)

**Comment by Amorphous404** [comment] 2023-07-30 20:24
- Duplicate of #2337

**Closed** 2023-07-30 20:24 UTC

**Comment by LostCursor** [comment] 2024-06-13 18:43
Hi, I'm writing here to also request this feature.

**Comment by jococo1221** [comment] 2024-09-02 03:08
Hello! The requests you closed as duplicates are not really duplicates. 2694 and 2471 at about being able to ALSO dim the main screen, as one can currently dim the app-list and search.

Currently the main screen is completely unreadable with most images, unless processed externally. Request 2694 illustrates that clearly, and I'm surprised it was just dismissed. It's such a basic and important feature. 

Yes, it would be "nice" having the capacity to control how much the image is dimmed, as this request describes....  but just having EXACTLY the same functionality you currently have for the app list would be a huge difference by itself.

![Screenshot_20240901-230703](https://github.com/user-attachments/assets/53d12eeb-41b5-49da-b38a-b9b9bff5e9d0)
