### ISSUE TITLE
Location & Schedule based Favorites & Widgets

### ISSUE THREAD

**Issue by Mngnt** [8bitPit/Niagara-Issues#2894] opened 2024-09-10 13:24 UTC
### Describe the solution you'd like

I love the simplicity of Niagara, but how I use my phone changes in the morning as I prepare for work, during the day while at work, and in the evening when I return from work (as a simple example).

Rather than customize my favorites (and widgets) to accommodate for all of these simultaneously, the ability to show/hide favorites & widgets based on location or a schedule would allow us to keep things even more simple.

It seems a bit of this "conditional display" functionality already exists in the "Music App" feature.

This could be implemented in many different ways, including something like a "profile" function which would save entire favorites & widget configs, or something like a per-item "show/hide filter".

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-09-11 12:46
Hey there, thanks for the suggestion.
I'll close this as a duplicate of #2540 (and therein mentioned tickets). Favorite profiles are a planned feature.

**Closed by NiagaraSupport** 2024-09-11 12:46 UTC
