### ISSUE TITLE
Search latency causes position jump

### ISSUE THREAD

**Issue by andys8** [8bitPit/Niagara-Issues#2158] opened 2022-12-17 12:22 UTC
### Describe the bug

Here is an example where the search and the combination of throttling and maybe web search lead to an item (the play store) jumping from second to first position. These kind of jumps lead to clicking the worth entry and maybe they can be solved by tweaking latencies and/or how the web search behaves (e.g. different delay or no suggestions at all).

### Steps to reproduce

1. Search "stor"
2. See the "play store" on second position and try to click
3. Be surprised how it jumps to first position

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

OnePlus 8

### Android version

Android 12

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/13085980/208241608-320092d8-44cc-4b0f-abf0-fb5c3bc4c094.mp4

**Comment by Amorphous404** [comment] 2022-12-17 14:58
I tested by disabling websearch too, the results are the same, this issue is kinda similar to #2154, but yeah we'll definitely get to see some improvements in coming updates.

**Comment by andys8** [comment] 2022-12-17 15:02
Correct, the latency seems to be similar without websearch.


https://user-images.githubusercontent.com/13085980/208248166-7613234c-eb10-46ca-ba8b-3df5a0031dae.mp4

**Comment by TFackler** [comment] 2023-01-03 15:43
Thanks for letting us know, we will be looking into this :)

**Comment by TFackler** [comment] 2024-01-11 14:32
With recent changes and improvements to the app search, the delay has been greatly reduced for app results. 
Thus, I am closing this issue.

Web search still has a delay by design, but we are working on improving it.

**Closed by TFackler** 2024-01-11 14:32 UTC
Labels: bug, planned
