### ISSUE TITLE
Sesame's Bug :- Integrate sesame API

### ISSUE THREAD

**Issue by PhantomO2** [8bitPit/Niagara-Issues#1394] opened 2020-10-26 17:11 UTC
"Fast Search that's designed to work in 1 or 2 taps. It matches the first letters of words. Typing "s" "B" will bring "Spotify: The Beatles" to the top. Since it learns from you, next time just "s" will do." 
So this is a feature of Sesame app. This feature is not working with the Niagara launcher search . Like, I have an app called "Manga Reader" and if I type "M R" or "MR" or "mr" in Niagara's search ( in search provided below apps list ) then it won't show me Manga Reader. Also if I type "M" and chose "Manga Reader" from the search . The next time, if I were to type "M" then it won't show me "Manga reader" as my first suggestion. The search results won't change based on the most used app but it works when I use the inbuilt search in Sesame's app.  Is it just me or someone else is facing same problem? I have Niagara v 0.32.4, lenovo K8+, android 8.0.0

**Comment by 8bitPit** [comment] 2020-11-02 11:21
Yes, fuzzy search is not yet supported by Niagara Launcher, but it's on our list: https://github.com/8bitPit/Niagara-Issues/issues/411

**Comment by 8bitPit** [comment] 2020-11-02 11:21
Duplicate of #411

**Closed by 8bitPit** 2020-11-02 11:21 UTC
Labels: bug, duplicate
