### ISSUE TITLE
Automatic backup

### ISSUE THREAD

**Issue by imparthvader** [8bitPit/Niagara-Issues#2313] opened 2023-06-20 19:24 UTC
### Is your feature request related to a problem?

Please add auto backup via the launcher not via Google services

### Describe the solution you'd like

A button that allows could backups to be enabled and the frequency of backups

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-06-21 01:27
Hi @imparthvader, Thanks for your suggestion! Please refer to #222

- Duplicate of #222

**Closed** 2023-06-21 01:27 UTC
