### ISSUE TITLE
privacy settings for homescreen notifications

### ISSUE THREAD

**Issue by tschorle** [8bitPit/Niagara-Issues#855] opened 2019-04-29 10:02 UTC
i'd like to have control over the privacy level for homescreen settings 

i'd prefer to show my homescreen:

Whatsapp
new message from [sender]

instead of

Whatsapp
[sender]: [message]

**Comment by 8bitPit** [comment] 2019-04-30 09:07
Duplicate of #827

**Closed by 8bitPit** 2019-04-30 09:07 UTC
Labels: duplicate
