### ISSUE TITLE
Auto Show Apps with notifications

### ISSUE THREAD

**Issue by asrpdm** [8bitPit/Niagara-Issues#2920] opened 2024-09-18 18:31 UTC
### Is your feature request related to a problem?

I really love that apps on starting screen show their related notifications next to them. It would be great if all apps with new notifications could be enabled to be automatically shown there as well. Thanks in advance. 

### Describe the solution you'd like

Any time a new notification appears the related app should appear on homescreen. If it's no favorite app it will disappear as soon as the notification is opened or rejected. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2024-09-19 07:16
Thanks for this suggestion.

This has been requested quite a while ago. I will mark this as a duplicate, please add your thoughts there :)

---

Duplicate of #152

**Closed by TFackler** 2024-09-19 07:16 UTC
Labels: duplicate
