### ISSUE TITLE
Double tap on home screen to sleep

### ISSUE THREAD

**Issue by js-d-coder** [8bitPit/Niagara-Issues#1180] opened 2020-02-14 05:54 UTC
**Is your feature request related to a problem? Please describe.**
No problem, just feature request as mentioned in title. The app can request to be Device Admin to put device to sleep.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.

**Comment by 8bitPit** [comment] 2020-02-16 12:29
Thanks for your request, but I believe this is a duplicate of: https://github.com/8bitPit/Niagara-Issues/issues/63

**Comment by 8bitPit** [comment] 2020-02-16 12:29
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/63

**Closed by 8bitPit** 2020-02-16 12:29 UTC
Labels: duplicate
