### ISSUE TITLE
Background paralax effect

### ISSUE THREAD

**Issue by rancor1223** [8bitPit/Niagara-Issues#834] opened 2019-04-14 13:41 UTC
Coming from Windows Phone, what initially drew me to Niagara launcher was it's vertical app list. Another feature WP has was a "paralax effect", which you could turn on. **Essentially, when scrolling, the background scrolled as well, but at much slower speed then the content in front of it.**

You can see it in action [here](https://youtu.be/eibI14NqWJk?t=40).

One slight negative is that it requires you to find pretty long wallpaper. Windows Phone requires image ratio of 2:1. 

I think it could be cool addition.

**Comment by 8bitPit** [comment] 2019-04-16 20:09
Hey, I posted your suggestion here: https://github.com/8bitPit/Niagara-Issues/issues/246

**Comment by 8bitPit** [comment] 2019-04-16 20:09
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/246

**Closed by 8bitPit** 2019-04-16 20:09 UTC
Labels: duplicate
