### ISSUE TITLE
Swipe action inside category

### ISSUE THREAD

**Issue by RWHurra** [8bitPit/Niagara-Issues#2334] opened 2023-07-14 11:28 UTC
### Is your feature request related to a problem?

I can't access swipe action menu/app shortcuts inside a category. 

### Describe the solution you'd like

I use the message app Signal as example below 👇

If I use the swipe action on Signal, I get a list with my most recent conversations. 

On my home screen I have a category called messaging where I have the messaging apps I use the most.

When I have opened the messaging category I would like to be able to use the swipe action on Signal, just like if I swiped on the app shortcut on the home screen/app list.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-07-16 15:02
Hi @RWHurra, Thank you for your request! To keep the launcher UI simple and easy to use, we intentionally kept the popup hierarchy to a single level. However, there's an open discussion about the same on #1925. You follow up on the issue for further updates.

Thanks,

**Comment by Amorphous404** [comment] 2023-07-16 15:02
- Duplicate of #1925

**Closed** 2023-07-16 15:06 UTC
