### ISSUE TITLE
Media player

### ISSUE THREAD

**Issue by 1080pixelz** [8bitPit/Niagara-Issues#1327] opened 2020-06-23 21:12 UTC
I would like to see a feature where the media player widget which pops up "whenever its needed" has an option of 3 to choose from.
Option 1 - Permanently disable media player widget.
Option 2 - Media player pops up whenever it detects media.
Option 3 - Show the media player at all times as a widget.
I think this feature should be implemented because the current situation in which the media player pops up when its needed, all my apps get shifted down and my screen doesn't look right. If i disable or enable it completely, my home screen would be set up that way and it would look much cleaner. Thank you dev(s), this is an amazing app and I'm looking forward to future updates.

**Comment by Rod911** [comment] 2020-06-24 18:45
Always hide music player #111
Always show music player #375
Decrease top padding if media player is visible #243

As of now, if you add a widget from the same app as the current playing app, the media player will not appear.

I'll close this ticket since the points you mentioned have already been mentioned. Feel free to reopen if you need to.
Duplicate of 111#

**Closed** 2020-06-24 18:45 UTC
Labels: duplicate
