### ISSUE TITLE
Unread Message Indicator

### ISSUE THREAD

**Issue by LeIVIat** [8bitPit/Niagara-Issues#1915] opened 2022-04-10 14:07 UTC
### Is your feature request related to a problem?

-

### Describe the solution you'd like

I would like to have an unread message indicator that isn't dismissed after I cleared my notification shade. 
The Microsoft Launcher has this functionality build in and that is the only thing I miss about this launcher. 

A simple notification dot with the number of unread messages inside would be lovely.

**Comment by Oddward** [comment] 2022-04-10 17:00
Niagara uses the notification dots feature to enable its notification previews, it's the same feature I believe except Niagara displays the notification content. If you're just trying to avoid having the previews on your app list you can disable **Notification dots** in your system settings (Android 8+ iirc) while keeping **Embedded notifications** on in Niagara settings, so the arrow to open the pop-up appears without the content previews. A numerical indicator isn't likely to be added

**Comment by Oddward** [comment] 2022-04-10 17:02
Just realized it's also a duplicate of #1701 and #1908 so I'll close this one.

**Closed by Oddward** 2022-04-10 17:02 UTC

**Comment by Amorphous404** [comment] 2023-01-23 16:57
Also a duplicate of #800
