### ISSUE TITLE
Ability to change search engine from Google. 

### ISSUE THREAD

**Issue by lcw731** [8bitPit/Niagara-Issues#1484] opened 2021-01-29 15:50 UTC
Would like ie to be able do change search from Google. Preferably search engine of my choosing, or at least able to change to duck duck go or start page.

**Comment by 8bitPit** [comment] 2021-01-30 14:23
Thanks for the request @lcw731, we're planning to add that: https://github.com/8bitPit/Niagara-Issues/issues/142

**Comment by 8bitPit** [comment] 2021-01-30 14:23
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/142

**Closed by 8bitPit** 2021-01-30 14:23 UTC
