### ISSUE TITLE
Custom Widget goes blank/requires daily restart of launcher

### ISSUE THREAD

**Issue by dmarcantonio** [8bitPit/Niagara-Issues#1671] opened 2021-07-20 13:55 UTC
**Describe the bug**
**Note: I'm on the Android 12 Beta**
Using At A Glance as a custom widget, it appears to be not-loaded every morning after the phone wakes up from bedtime mode. A "Restart Launcher" from the Niagara Advanced menu in Settings gets it working every time. 

**To Reproduce**
1. Take phone out of bedtime mode. 
2. Widget will be in an unloaded state. (translucent box) 
3. Restart Launcher to fix

**Smartphone (please complete the following information):**
 - Device: Pixel 4a 5G 
 - Android version: 12 (beta) 

**Screenshots**
I'll add one tomorrow morning 😅

**Comment by dmarcantonio** [comment] 2021-07-20 14:05
Similar to https://github.com/8bitPit/Niagara-Issues/issues/1609, it seems. Feel free to close as a duplicate, my bad!

**Comment by Montell2099** [comment] 2021-07-23 15:09
> Similar to #1609, it seems. Feel free to close as a duplicate. My bad!

You have the ability to close this issue by yourself! 😉

**Comment by 8bitPit** [comment] 2021-07-29 12:54
Let's keep it open because I believe this is caused by something else. This bug has something to do with the new caching system for pop-up widgets. We'll fix this with the next update; thanks for reporting!

**Comment by 8bitPit** [comment] 2021-08-30 17:42
Fixed in v.1.3.6

**Closed by 8bitPit** 2021-08-30 17:42 UTC
Labels: bug, in progress
