### ISSUE TITLE
It is not possible to interact with the elements on the right side of a widget

### ISSUE THREAD

**Issue by joatb** [8bitPit/Niagara-Issues#2127] opened 2022-11-26 12:02 UTC
### Describe the bug

It is not possible to interact with the elements on the right side of a widget because the menu is activated as shown in the screenshot

### Steps to reproduce

Try to interact with something in the widget on the far right

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung A50

### Android version

Android 11

### Screenshots / Screen recordings

![2](https://user-images.githubusercontent.com/32104295/204087806-6f28e551-1e7e-4327-80e8-20688c9301b9.jpeg)

https://user-images.githubusercontent.com/32104295/204087810-37b639bb-b0f8-4cc6-b2d3-ee65992d5133.mp4

**Comment by notepadnine** [comment] 2022-11-27 05:07
these kind of bug has been raised many times. Even suggestion to disable alphabet side gesture. But no way worked. 
It will be better if we can have a fixed position in right/left side to activate alphabet drawer rather than everywhere.
Best will be app only by search and disable this alphabet line

**Comment by joatb** [comment] 2022-11-27 12:43
It would be nice to have the option in the configuration to make the alphabet gesture have a maximum height or to detect at least the widgets and deactivate the gesture in that area.

**Comment by Amorphous404** [comment] 2022-12-07 03:29
> ### Describe the bug
> 
> It is not possible to interact with the elements on the right side of a widget because the menu is activated as shown in the screenshot
> 
> ### Steps to reproduce
> 
> Try to interact with something in the widget on the far right
> 
> ### Does the issue also occur with other 3rd-party launchers?
> 
> Not applicable
> 
> ### Other 3rd-party launcher(s) tested
> 
> _No response_
> 
> ### Device name
> 
> Samsung A50
> 
> ### Android version
> 
> Android 11
> 
> ### Screenshots / Screen recordings
> 
> ![2](https://user-images.githubusercontent.com/32104295/204087806-6f28e551-1e7e-4327-80e8-20688c9301b9.jpeg)
> 
> https://user-images.githubusercontent.com/32104295/204087810-37b639bb-b0f8-4cc6-b2d3-ee65992d5133.mp4
> 
> 

It was already on the note when you Enabled the fill screen option

![IMG_20221207_085702.jpg](https://user-images.githubusercontent.com/96917972/206081129-409fc563-0570-4c5a-aa29-77e8366338a0.jpg)

**Comment by Amorphous404** [comment] 2022-12-15 20:28
It seems it's a duplicate of #1714

**Closed** 2022-12-15 20:29 UTC
Labels: bug, duplicate
