### ISSUE TITLE
Perplexity as a search engine option

### ISSUE THREAD

**Issue by bpavuk** [8bitPit/Niagara-Issues#2902] opened 2024-09-11 19:27 UTC
### Is your feature request related to a problem?

I use Perplexity on a daily basis. It replaced Google everywhere but Niagara Launcher search. Perplexity has over 50 million MAU as of February 2024 and has an outstanding 4.5 rating at Google Play (4.7 in Ukraine). I'd like to get rid of any widgets on my screen, but to conveniently access Perplexity, I have to keep the widget pinned.

### Describe the solution you'd like

The solution I propose is to add Perplexity to search engines list here:
![Screenshot_20240911-222242_Niagara Launcher](https://github.com/user-attachments/assets/36b4035a-53ee-47bc-a654-98ad9dc7d679)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2024-09-18 15:28
Duplicate of #2711.

Feel free to add your vote there and thank you for informing us about perplexity :)

**Closed by TFackler** 2024-09-18 15:28 UTC
Labels: duplicate
