### ISSUE TITLE
Feature Request - Google Feed Integration

### ISSUE THREAD

**Issue by xxlostspiritxx** [8bitPit/Niagara-Issues#1332] opened 2020-07-06 17:01 UTC
**Is your feature request related to a problem? Please describe.**

Hate leaving the launcher to visit the Google Feed. Google Feed is something that is constantly opened and closed so it's annoying having to leave the app every time and tapping to renter it.

**Describe the solution you'd like**

Google Feed (swipe left) integration. Always running Google Feed integration that allows users to quickly enter and exit Google Feed without ever leaving Niagara, avoiding the use of the home button or back button in exchange for a swipe that returns user to Niagara's home page.

Please remember: a feature should be...

*Simple*  One toggle for ON/OFF & maybe swipe direction.

*Impactful*  Many of my friends have left Niagara and went back to stock experience because of the app lacking this feature.

*Universal*  Many phones already have it in their stock experience so it "generally" shouldn't interfere with anything.

*Independent* The swipe functionally "shouldn't" generally interfere with Niagara because travel is dictated vertically and this would be a horizontal.

Note:
I love Niagara and honestly couldn't imagine a world without it. I've gotten myself on Niagara Premium and a few friends as well. The lack of this feature is the main reason why we have the urge to stop using it. OnePlus is about to add Google Feed to their stock android launcher and that's a compelling enough reason for some (like us) to leave, but we really do want to stay. I hope that you may find time to add this feature and you agree it's importance to the community.

**Comment by Martin5001** [comment] 2020-07-06 17:41
I personally am used to Google feed coming from the left, but the swipe from left to right gesture is already used for notifications. Just adding this as a note.

**Comment by Rod911** [comment] 2020-07-06 17:51
From [#3](https://github.com/8bitPit/Niagara-Issues/issues/3#issuecomment-483818460)

> I thought about integrating Google Now and I decided not to implement it for now for the following reasons:
>
> - The swipe right gesture to open it wouldn’t fit for Niagara
> - Google doesn’t want other apps to use it, so you would have to make or take use of a second apk which is not very user friendly
> - The feed could have a negative impact to the app’s performance
> - It would cost a time to develop & test it (that applies to a lot of features, but should be kept in mind anyway)
> - The Google app has the same feed build in their Google app. Just adding the G-button to your homescreen and tapping it when you want to browse the feed is a much simpler and imo, more elegant solution.

Duplicate of #3

**Closed by Rod911** 2020-07-06 17:51 UTC
Labels: duplicate
