### ISSUE TITLE
A option to choose different icon pack for favourites and diff for list

### ISSUE THREAD

**Issue by MrRobot0707** [8bitPit/Niagara-Issues#1451] opened 2020-12-22 06:06 UTC
**it's just a additional feature which may be usefull for some **
It just make a homescreen more good . I mean if you wanna make your favorites look different than the other apps this will be helpful
*Simple* 
*Impactful*

**Comment by 8bitPit** [comment] 2020-12-22 06:33
Hi, @MrRobot0707 👋 To keep Niagara Launcher as simple as possible, I'm against adding an extra toggle for choosing different icons for your favorites. However, you may find hiding your favorites from Niagara's app list useful: #955

**Comment by 8bitPit** [comment] 2020-12-22 06:34
Duplicate of #955

**Closed by 8bitPit** 2020-12-22 06:34 UTC
Labels: duplicate
