### ISSUE TITLE
Work profile calendar widget displays incorrect calendar events

### ISSUE THREAD

**Issue by sgregson** [8bitPit/Niagara-Issues#1518] opened 2021-02-24 05:31 UTC
**Describe the bug**
The "work calendar schedule" widget displays personal calendar events and no content from the work profile (when used for the Niagra custom widget)

**To Reproduce**
1. Navigate to Niagra Settings  > features > Niagra widget > add custom widget > calendar
1. Select "work calendar schedule" (screenshot below) 
1. View Niagra home screen and note that the calendar events are those of my personal calendar (not the Enterprise-managed work profile)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - Android version: Android 11

**Screenshots**
These two widgets result in the same content : 
![screenshot of the two widgets with identical content](https://user-images.githubusercontent.com/1302515/108950714-a85d5d00-7634-11eb-9322-225d45ece9b1.png)

Demo of adding both, note that the calendar events are identical (couldn't capture work profile anonymously, but I guarantee the content is very different):

![demo gif](https://user-images.githubusercontent.com/1302515/108952386-5f5ad800-7637-11eb-80a4-31b15c2d4c64.gif)

**Comment by sgregson** [comment] 2021-02-24 05:35
I'm pretty sure this is distinct from the feature idea in #1400, which combines events into the main calendar

**Comment by 8bitPit** [comment] 2021-03-25 12:05
Interesting. Can you please check if the work profile Google Calendar Agenda widget displays your work profile events when using  Pixel Launcher?

**Comment by 8bitPit** [comment] 2021-05-13 09:16
I'm closing the issue, but please let me know if Pixel Launcher displays the events correctly while Niagara Launcher does not.

**Comment by lack** [comment] 2021-05-14 00:38
I can confirm both Pixel Launcher and Nova Launcher display the correct work calendar info when I create a calendar widget with my work profile.

Niagra sadly still does not.

In fact, in the widget chooser I can't even tell easily which "Calendar" is the work profile, since it's not designated with the little briefcase icon:

![Screenshot_20210513-203632.png](https://user-images.githubusercontent.com/56012/118203887-05de9a00-b42b-11eb-8339-d78ad3fbe0d4.png)

As a comparison, when looking through the apps list, the briefcase icon is there and designates which "Calendar" is the one from my work profile:

![Screenshot_20210513-203547.png](https://user-images.githubusercontent.com/56012/118203913-0d9e3e80-b42b-11eb-9fa4-6c1669189818.png)

**Comment by lack** [comment] 2021-05-14 00:58
In fact, using the new "pop ups" feature, it's even more confusing.

If I navigate down to the work-profile calendar app, and edit the popup there:

![Screenshot_20210513-204854.png](https://user-images.githubusercontent.com/56012/118205130-b057bc80-b42d-11eb-85f0-8d0049301fa2.png)

The widget selector seems to imply it knows it's the work profile:

![Screenshot_20210513-204902.png](https://user-images.githubusercontent.com/56012/118205175-c5cce680-b42d-11eb-92b8-1be2bd78b775.png)

But when I select "Work Calendar schedule", the resulting widget is actually my personal calendar, not my work one:

![Screenshot_20210513-205340.png](https://user-images.githubusercontent.com/56012/118205290-fad93900-b42d-11eb-936f-0e07d89565a8.png)

**Comment by 8bitPit** [comment] 2021-05-14 09:58
Thank you very much for all the additional details. I found the bug and roll out a fix with v1.2.1. Cheers!

**Comment by lack** [comment] 2021-05-15 00:03
But I'm already running 1.2.1!

**Comment by 8bitPit** [comment] 2021-05-15 17:12
oh sorry, @lack, I meant 1.2.2 😅

**Comment by lack** [comment] 2021-05-16 14:01
Whew 😅

Excited to try it out!

**Comment by lack** [comment] 2021-05-18 14:59
Just installed 1.2.2, and I can attest that my issue is completely solved!  I can now properly differentiate between non-work and work-profile apps in the widget selection list, and even better, when I select a work-profile widget the content in it is actually from my work calendar (or gmail, or etc).

Thanks so much for your time on this.

**Comment by 8bitPit** [comment] 2021-05-22 08:45
Great, thanks for the update @lack :D I'm closing this issue then.

**Closed by 8bitPit** 2021-05-22 08:45 UTC
Labels: bug
