### ISSUE TITLE
short Alphabet bar

### ISSUE THREAD

**Issue by pimozone** [8bitPit/Niagara-Issues#2476] opened 2023-12-08 06:37 UTC
### Is your feature request related to a problem?

no

### Describe the solution you'd like

I want to shorten the Alphabet bar since I have a problem with swiping Alphabet bar. It's too long for me to swipe at once.
Blessing for small hands

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Lorestan00** [comment] 2023-12-11 11:23
Agreed. The alphabet is too high up on the screen. On foldables the inside screen has it right to the top and the cover screen abit further down still too high. 

Needs to be an option to adjust the height

**Comment by NiagaraSupport** [comment] 2023-12-18 19:14
Thank you for your report. Currently, we don't have a way to shorten the alphabet bar without impacting its functionality. However, you can tap anywhere on the screen to initiate the swiping motion from that point, avoiding the need to go through the entire bar. Would that address your concern, or could you provide more details about your problem?

**Comment by NiagaraSupport** [comment] 2023-12-18 19:17
In Lorestan00's case, touching the empty screenspace below the alphabet itself should automatically snap it to your fingers position. Let me know if the issue persists.

**Comment by henningBunk** [comment] 2024-02-16 20:21
> Blessing for small hands

I got really big hands (size 12) and have a small phone but I think too that the alphabet could be shorter for better one hand operation without changing your phone grip.

**Comment by NiagaraSupport** [comment] 2024-02-28 10:10
I'll close this as a duplicate of #334 and tell the others that this seems to be a popular request.

**Closed by NiagaraSupport** 2024-02-28 10:10 UTC
