### ISSUE TITLE
More efficiency with a Alarm Symbol 

### ISSUE THREAD

**Issue by JubeiAshura** [8bitPit/Niagara-Issues#2107] opened 2022-11-04 02:59 UTC
### Is your feature request related to a problem?

Hi, I found an old thread that has been deactivated so I submit a  new Feature Request. 
I absolutely love how simple and easy your launcher is, but there is one issue that keeps bugging me.
Please add a little indicator to the clock that shows, that an Alarm is set. That's all I'm asking for.

It would really help to see on your Startscreen whether an Alarm is set or not, instead of having to click on the clock to make sure that you actually set one. On my Google Pixel 4XL with Android 13 I only see an Alarmsymbol on the Lockscreen or two hours before the Alarm actually goes off in the top left of the Statusbar, which I disabled with your launcher anyways.

Thanks for consideration. Please keep up the good work.

### Describe the solution you'd like

Simple Alarmclock-Symbol next to the clock if an Alarm is set

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment] 2022-11-11 18:17
Duplicate of #4

**Comment by JubeiAshura** [comment] 2022-11-12 04:39
It may be a duplicate, however I don't know about you guys but my phone Android 13 does not show an Alarm Icon in notification Pane.

**Comment by notepadnine** [comment] 2022-11-13 18:02
And what about users who use pro feature of STATUS BAR HIDE

**Comment by Amorphous404** [comment] 2022-12-11 11:37
> It may be a duplicate, however I don't know about you guys but my phone Android 13 does not show an Alarm Icon in notification Pane.

Same case for some users who commented on the same thread, also you mentioned the previous ticket is closed which is not the case.

It's better to comment on the same related ticket that already exists than to create a duplicate ticket for the same to keep the repository clean :)

**Closed** 2022-12-12 12:38 UTC
Labels: duplicate
