### ISSUE TITLE
Optionally hide app icons altogether

### ISSUE THREAD

**Issue by ricardosalta** [8bitPit/Niagara-Issues#2103] opened 2022-10-31 13:40 UTC
### Is your feature request related to a problem?

Shiny icons support the compulsive opening of apps 

### Describe the solution you'd like

Option to hide icons altogether 

For example this launcher does it https://www.minimalistphone.com/

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment] 2022-11-11 18:13
https://github.com/8bitPit/Niagara-Issues/issues/140#issuecomment-753679560

Duplicate of #140

**Closed** 2022-11-15 07:01 UTC
Labels: duplicate
