### ISSUE TITLE
Duplicate text/element glitch when returning to Niagara

### ISSUE THREAD

**Issue by rohan1269** [8bitPit/Niagara-Issues#1690] opened 2021-08-19 09:14 UTC
https://user-images.githubusercontent.com/80900420/130042442-48ba0b0c-6d90-4ac3-9e40-88695ed59d2c.mp4
I updated Niagara launcher recently and this is happening when I unlock my phone

**Comment by Maxr1998** [comment] 2021-09-26 19:18
The duplicated texts definitely shouldn't happen. I also had that already, but a launcher restart fixed it. I'll investigate.

**Comment by Maxr1998** [comment] 2022-02-07 22:52
Duplicate of #1804. Merging into the newer issue since there are more details collected there.

**Closed** 2022-02-07 22:52 UTC
Labels: bug, duplicate
