### ISSUE TITLE
Return to the favorites list with Home gesture (or Home button)

### ISSUE THREAD

**Issue by MichaelJuskowicz** [8bitPit/Niagara-Issues#2006] opened 2022-07-25 23:34 UTC
### Is your feature request related to a problem?

When I have the Agenda bottom sheet open I will often try to use the Home gesture (swiping up from the bottom of the screen) to close the Agenda and view the Home screen. This is the same for the bottom sheet that opens for other interactions in the launcher like after long-pressing a favorite.

Closing the bottom sheet is the behavior I would expect, but because using the Home gesture is just switching to the launcher it does an animation and returns to the same bottom sheet.

Here is [a post on Reddit](https://www.reddit.com/r/NiagaraLauncher/comments/w33dgr/close_popup_when_returning_to_home_screen/)  where another two users have a similar experience.

### Describe the solution you'd like

Using the Home gesture or pressing the home button should close any overlay or modal the launcher has open and return the user to the favorites list if they are elsewhere in the launcher like in the app list.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by johnw42** [comment] 2022-07-26 16:06
I was just about to request this exact feature! I'll add one little twist/generalization: the home button/gesture should generally do more or less the same thing the back button/gesture does when the launcher is open: close an open pop-up, return to the the top of the favorites view, etc.

I've noticed the back gesture doesn't always do _exactly_ what I want; I just discovered that it toggles between the favorites view and the last used position in the full app list. I assume that's intentional behavior. IMHO the home gesture shouldn't have that toggle behavior and should always go to the top of the favorites list, but OTOH if the home gesture just did the same thing as the back button it wouldn't bother me enough that I'd ask to change it.

**Comment by topsy-turvy99** [comment] 2022-07-27 13:43
> ### Is your feature request related to a problem?
> 
> When I have the Agenda bottom sheet open I will often try to use the Home gesture (swiping up from the bottom of the screen) to close the Agenda and view the Home screen. This is the same for the bottom sheet that opens for other interactions in the launcher like after long-pressing a favorite.
> 
> Closing the bottom sheet is the behavior I would expect, but because using the Home gesture is just switching to the launcher it does an animation and returns to the same bottom sheet.
> 
> Here is [a post on Reddit](https://www.reddit.com/r/NiagaraLauncher/comments/w33dgr/close_popup_when_returning_to_home_screen/)  where another two users have a similar experience.
> 
> ### Describe the solution you'd like
> 
> Using the Home gesture or pressing the home button should close any overlay or modal the launcher has open and return the user to the favorites list if they are elsewhere in the launcher like in the app list.
> 
> ### Feature Request Procedure
> 
> - [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

This is an intended behaviour if you quickly return to home after opening an app, just in case you accidentally opened up an app, if you stay in the app for 4-5 sec, it will take you back to your favorites screen

**Comment by MichaelJuskowicz** [comment] 2022-07-28 12:23
> This is an intended behaviour if you quickly return to home i.e swipe up gesture or if you minimize the app with back gesture after opening an app, just in case you accidentally opened up an app, if you stay in the app for 4-5 sec, it will take you back to your favorites screen

I'm not sure we're describing the same thing though.

In the case you're describing it makes a lot of sense; swiping home or pressing the Home button, or using the back gesture or back button inside of an app, should have the behavior you mention. It's actually a very thoughtful and elegant solution.

What I'm describing is swiping home or using the Home button while in the launcher itself. In this case the user is definitely not trying to remain in the same spot, or have the same menus or overlays open. In the current state using the swipe home or home button does absolutely nothing.

**Comment by topsy-turvy99** [comment] 2022-07-28 16:50
> > This is an intended behaviour if you quickly return to home i.e swipe up gesture or if you minimize the app with back gesture after opening an app, just in case you accidentally opened up an app, if you stay in the app for 4-5 sec, it will take you back to your favorites screen
> 
> I'm not sure we're describing the same thing though.
> 
> In the case you're describing it makes a lot of sense; swiping home or pressing the Home button, or using the back gesture or back button is inside of an app, should have the behavior you mention. It's actually a very thoughtful and elegant solution.
> 
> What I'm describing is swiping home or using the Home button while in the launcher itself. In this case the user is definitely not trying to remain in the same spot, or have the same menus or overlays open. In the current state using the swipe home or home button does absolutely nothing.
> 

Can you please share a screen recording of what's not working (does nothing),

For me when I'm on the Launcher itself, the swipe up gestures or when button navigation is turned on home button performs as back back button, when agenda panel or any popup is open,

When I'm on favorites screen, home button acts as a search shortcut and swipe up opens up the recents menu

**Comment by MichaelJuskowicz** [comment] 2022-07-30 20:38
> Can you please share a screen recording of what's not working (does nothing),
> 
> For me when I'm on the Launcher itself, the swipe up gestures or when button navigation is turned on home button performs back, when agenda panel or any popup is open,
> 
> When I'm on favorites screen, home button acts as a niagarasearch shortcut and swipe up (gesture navigation) opens up the recents menu

Sure. [https://streamable.com/jfsozx](https://streamable.com/jfsozx)

In the recording I open a pop-up and then use the swipe-up Home navigation gesture a couple of times, then I use the back gesture to close the pop-up and go into the app list where I use the swipe-up Home navigation gesture a few times before going back to the favorites list using the back gesture.

**Comment by topsy-turvy99** [comment] 2022-07-31 20:33
> > Can you please share a screen recording of what's not working (does nothing),
> > 
> > For me when I'm on the Launcher itself, the swipe up gestures or when button navigation is turned on home button performs back, when agenda panel or any popup is open,
> > 
> > When I'm on favorites screen, home button acts as a niagarasearch shortcut and swipe up (gesture navigation) opens up the recents menu
> 
> Sure. [https://streamable.com/jfsozx](https://streamable.com/jfsozx)
> 
> In the recording I open a pop-up and then use the swipe-up Home navigation gesture a couple of times, then I use the back gesture to close the pop-up and go into the app list where I use the swipe-up Home navigation gesture a few times before going back to the favorites list using the back gesture.
> 

The video link isn't working on my end, from what you have mentioned, it looks like you're having Gesture computability issue,

Which Phone/Rom are you using?

**Comment by johnw42** [comment] 2022-07-31 21:35
I'm seeing the same behavior MichaelJuskowicz described on my Pixel 6 Pro with the stock Android 12 ROM.

**Comment by MichaelJuskowicz** [comment] 2022-07-31 23:37
> The video link isn't working on my end, from what you have mentioned, it looks like you're having Gesture computability issue,
> Which Phone/Rom are you using?

Pixel 6 Pro. Not using a custom ROM.

**Comment by Msouza91** [comment] 2022-08-21 13:39
This is a problem for me too, I use Samsung Pay and when I'm oh the Niagara settings, search or full app list and try to use the swipe up gesture expecting to go to favourites screen I end up opening the payment shortcut, it is like for the underlying structure the app didn't change from the home screen.

https://user-images.githubusercontent.com/19522556/185793557-22355da1-903b-43d3-9153-33f205da911e.mp4

Stock Samsung (One UI 4.1) ROM A12 - S22 Ultra

**Comment by Oddward** [comment] 2022-08-29 21:04
Is this regarding the brief bug that came with the early version of the current beta? Exiting pop-ups and sheets with screen edge gesture wasn't working but it was since fixed. If that's the case we can close this for now - [Github beta releases](https://github.com/8bitPit/Niagara-Issues/releases)

**Comment by Msouza91** [comment] 2022-08-30 10:13
Not sure if my reports are in line with the original issue, should I make it a separate one? My problem is more related to an interaction with the Samsung Pay shortcut.

**Comment by Oddward** [comment] 2022-08-30 13:56
@Msouza91 ya it seems like a separate issue and should probably get a diff ticket, although they've yet to confirm if my guess is right about the report (not sure about the timeline)

**Closed** 2022-09-08 21:11 UTC
Labels: awaiting-response
