### ISSUE TITLE
App Usage Timer Feature

### ISSUE THREAD

**Issue by tudorjnu** [8bitPit/Niagara-Issues#2493] opened 2023-12-18 09:40 UTC
### Is your feature request related to a problem?

I propose adding a timer feature in the launcher to help users manage their time on social media apps, which often encourage endless scrolling. This feature would provide the following functionalities:

1. **App Selection:** Allow users to specify which apps the timer should apply to. Alternatively, some apps can be pre-set as "blocked" by default.

2. **Time Selection Prompt:** When a user opens an app, they should be prompted to select a usage duration. The options would include predefined times (3, 5, 10 minutes) and a 'custom' field for entering a specific amount.

3. **Automatic Exit:** The app automatically closes once the selected time elapses.

I believe this feature will significantly enhance user experience by promoting mindful app usage.

### Describe the solution you'd like

Stated in the issue.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2024-01-29 16:37
Duplicate of #2407 
But this is more detailed, thus I will also link it in the referenced issue

**Closed by TFackler** 2024-01-29 16:37 UTC
