### ISSUE TITLE
Sugestion: Make the apps list organizable

### ISSUE THREAD

**Issue by ITrivinho** [8bitPit/Niagara-Issues#2204] opened 2023-02-12 15:06 UTC
Add the option to organize the apps list with folders.
i.e. when the user enables this option, the apps that were added to a folder, wont appear on the list anymore, only inside the folder.
This allows the user to have an prettier and shorter apps lists.
(the One UI already has it and I love this, it would be great to see in Niagara)

**Comment by Amorphous404** [comment] 2023-02-12 15:12
Seems like a duplicate of #1604 - I'll close this one, Could you please follow up on the older issue.

Duplicate of #1604

**Closed by Amorphous404** 2023-02-12 15:12 UTC
