### ISSUE TITLE
Follow device theme setting doesn't work

### ISSUE THREAD

**Issue by Kuladeep1996** [8bitPit/Niagara-Issues#1951] opened 2022-05-03 15:22 UTC
Bug 1:
If we use quick lock gesture to lock and unlock again immediately, it'll open all apps section instead of home screen

Bug 2:
After clearing all apps from recent menu it automatically opens search 

Bug 3:
I'm using auto dark mode in my phone and i have chosen "use device theme" in niagara settings. But niagara wont change automatically based on system.. i have restart launcher each time to change niagara theme

**Comment by Oddward** [comment] 2022-05-04 14:54
Hey. Please keep issues focused on one topic so they can more easily be tracked & handled. 

1. This is intentional behaviour, it remembers your navigated position for a few seconds in case you accidentally left the launcher: see the [help article](https://help.niagaralauncher.app/article/86-pressing-home-doesnt-show-favorites)

3. Can you provide info about your system/device? This seems to be device-specific

**Comment by Kuladeep1996** [comment] 2022-05-05 04:34
Device : Realme 7
OS : Android 11

**Comment by timm0e** [comment] 2022-05-06 13:49
Regarding Bug 2: There's already a similar issue: #1907

Are you using Sesame as well?

**Comment by Kuladeep1996** [comment] 2022-05-06 13:59
No I'm not using Sesame

**Comment by topsy-turvy99** [comment] 2022-05-11 09:38
> Thanks for your answer :ok_hand: 
> 
> It seems to us that Bug 2 and 3 are caused by Realme's Android ROM, and we have no control over it :disappointed: 
> 
> As a workaround to Bug 2, you could disable "Swipe up to search" under Settings > Features > Advanced

About the bug 3, I'll just like to add, I'm on lineage os Android 12.1, it sometimes don't change the light/dark even when it's manually changed, same with monet colors too, restarting the launcher fixes it, not a big deal, just thought will share it 🙂

**Comment by Amorphous404** [comment] 2022-12-15 05:53
> About the bug 3, I'll like to add, I'm on Lineage OS Android 12.1, occasionally Niagara doesn't follow the system the light/dark theme when I switch manually, same with monet colors too, restarting the launcher fixes it, not a big deal, just thought will share it 🙂

Update: I can still reproduce this bug on my new device which runs on **OxygenOS 13 (Android 13)

**Comment by TKurumi237** [comment] 2023-04-08 17:36
On my vivo iQOO neo5 SE phone's Android 12, my Niagara Launcher cannot follow the system's dark mode unless I manually restart it. I once upgraded to Android 13, and this issue disappeared, but when I returned to Android 12, it reappeared.

**Comment by 8bitPit** [comment] 2023-11-20 19:10
We slightly reworked our theming system; does the issue still appear in [v1.10](https://github.com/8bitPit/Niagara-Issues/releases)?

**Comment by BuriedIris** [comment] 2023-11-21 06:23
Sorry, I am using Android 13 now. This problem was only encountered on Android 12 before. The new color system is very satisfying, but the built-in Material icons' colors are different from those elsewhere. It should be gray based on my wallpaper, but the built-in icon is purple. In addition, the Chinese search in this version is broken. I must enter the complete name to search, so I am hesitating whether to roll back the version.

**Comment by 8bitPit** [comment] 2023-11-21 08:37
I see, thanks a lot for reporting both issues @BuriedIris. 

Niagara Launcher's auto theme color option does intentionally not always conform to the system's Material You color, it is also based on the most dominant wallpaper colors, see [this article](https://help.niagaralauncher.app/article/133-color-system). Nevertheless, this might be a bug since you stated the color does not even conform to the wallpaper color. Could you share a screenshot showing the issue?
Regarding search: I'm sorry to hear that. Can you give an example of a search term that does not find an app even though it should?

**Comment by BuriedIris** [comment] 2023-11-21 09:07
I see. Color doesn't seem to be an issue now, although the material icons and Niagara button etc. are inconsistently colored. Both colors are included in the wallpaper.
What's more serious is search. In English, I can search for "album" by "al", but in Chinese, I want to search for "中国大学MOOC" and I enter "中国" but I don't get the results I want, even if I enter "中国大学MOO" still doesn't work. But it was possible in previous versions. My system language is English and the system is Android 13.
-------- Original Message --------

**Comment by 8bitPit** [comment] 2023-11-21 09:25
Thanks a lot for the example, we'll investigate both issues.
CC @TFackler

**Comment by BuriedIris** [comment] 2023-11-21 09:43
Another suggestion is to make the built-in material icon follow the system dark mode.
Many thanks to the development team.
-------- Original Message --------

**Comment by Kuladeep1996** [comment] 2023-11-23 14:45
@8bitPit  using 1.10.2 version haven't faced this issue so far

**Comment by 8bitPit** [comment] 2023-11-24 14:48
Hey @BuriedIris, happy to tell you that both the color and the search issues should be fixed with v1.10.3: https://github.com/8bitPit/Niagara-Issues/releases. Regarding the Material pack following dark mode: depending on the popularity it gets, we might add another variation with dynamic theming.
Also, thanks for letting me know @Kuladeep1996.

**Closed** 2023-12-11 10:19 UTC
Labels: bug
