### ISSUE TITLE
Calender Icon

### ISSUE THREAD

**Issue by deepanshujbans** [8bitPit/Niagara-Issues#922] opened 2019-06-28 11:11 UTC
As today is 28 June  so the CALENDER APP icon should show current date but it is showing 6 only.
As today date is 28 so the calander app should show date 28. I am not talking about inside the calander app i am talking about calender app icon it is showing date 6 wether it is 7, 8 or 9.

Please look into the matter seriously.

**Comment by Rod911** [comment] 2019-06-28 16:33
Duplicate of #533

**Closed** 2019-06-28 16:33 UTC
Labels: duplicate
