### ISSUE TITLE
Ability to have only App names in the list, instead of icons and App name.

### ISSUE THREAD

**Issue by krishnapsn** [8bitPit/Niagara-Issues#1402] opened 2020-11-05 10:18 UTC
It would be great if we could have only app names to give the launcher a more minimal look. At least in the favourites screen.

**Comment by UsamaKarim** [comment] 2020-11-06 04:13
Just like Before Launcher?

I used that launcher for some days but I can't regret the beauty of Niagara Launcher. But still, we can test this feature, definitely

**Comment by Rod911** [comment] 2020-11-06 09:27
Duplicate of #140

**Closed by Rod911** 2020-11-06 09:27 UTC
Labels: duplicate
