### ISSUE TITLE
Integrate Google Tasks in calendar widget

### ISSUE THREAD

**Issue by troelsbakandersen** [8bitPit/Niagara-Issues#2300] opened 2023-06-08 11:42 UTC
### Is your feature request related to a problem?

I suggest that Google Tasks are integrated to the calendar widget, so I get the full overview of my day, when using the Niagara widget to browse my schedule. 

There is an option to filter calendars shown in the widget, and I'm missing an option to add Google Tasks. Basically I would like to get the same overview of my day as the Google Calendar Agenda view. 

### Describe the solution you'd like

I suggest that you add a toggle swith to Niagara settings > Features > Niagara widget > Calendard popup. The toggle switch could be named "Show tasks". If selected then my tasks from Google Tasks are shown in the agenda in my calendar widget alongside my calendar events. 

The tasks should be sorted by due date and time, just as they are in the Google Calendar Agenda. Repetitive tasks should be supported. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by bedantadey17** [comment] 2023-06-10 17:20
I totally agree. This will be very useful, because the default Google Tasks widget doesn't look very good if used in place of the custom widget.

**Comment by Amorphous404** [comment] 2023-06-11 18:46
Hi @troelsbakandersen, unfortunately, Google doesn't share certain types of events with other apps via the calendar API, including Reminders and Tasks.

For more info, please refer to this article:
[Niagara's Calendar Widget](https://help.niagaralauncher.app/article/76-calendar-faq)

However, the team is planning to integrate Todoist, which offers a comprehensive API; please refer to this issue #1285.

• Duplicate of #1347

**Closed** 2023-06-11 18:46 UTC
