### ISSUE TITLE
Two columns

### ISSUE THREAD

**Issue by jamesspratt** [8bitPit/Niagara-Issues#2603] opened 2024-02-22 20:52 UTC
### Is your feature request related to a problem?

A simple feature but would make for better UX. Not a problem as it is, 

### Describe the solution you'd like

Simply two columns instead of the current one. Would just mean you could fit more favourites within main visible screen so less scrolling. Neater in my opinion.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2024-02-23 13:10
Hi there,

Sadly, we do not plan on supporting this since, on most devices, the names of apps would need to be truncated to show two columns of apps on the home screen. This becomes an even bigger problem once you factor in notification previews. In addition to that we believe in a philosophy to have few apps on your home screen and use the search / all-apps list / pop-ups for apps you use somewhat frequently.

Also a duplicate of the very old #329

**Closed by TFackler** 2024-02-23 13:10 UTC
Labels: duplicate

**Comment by NiagaraSupport** [comment] 2024-02-28 10:32
To add to that, if scrolling is your main gripe with the current design, be sure to check out [pop-up folders](https://help.niagaralauncher.app/article/115-pop-ups#:~:text=App%20Pop%2Dups-,Pop%2Dup%20Folders,-To%20add%20one) if you haven't already.

**Comment by jamesspratt** [comment] 2024-02-28 10:37
Thanks yes, already do. My issue is not taking advantage of that space on the lower right quadrant of the screen.
![Screenshot_20240228_103527_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/142899/01de68b3-2f8f-4ae6-bb3d-7bf418e553e6)

**Comment by NiagaraSupport** [comment] 2024-02-28 12:12
I see. I'm afraid it won't change any time soon due to the points of conflict TFackler pointed out. Sorry about that, and thanks for understanding.
