### ISSUE TITLE
A section for apps with Notifications to be at the top/end of the Applications list

### ISSUE THREAD

**Issue by aravindps** [8bitPit/Niagara-Issues#1657] opened 2021-07-07 05:14 UTC
**Is your feature request related to a problem? Please describe.**
It is very hard to find an app which has a notification in app list. Also there is not marker on the alphabet also for me to know there is a notification.

**Describe the solution you'd like**
A separate section to have all the apps with notifications on the top or at the buttom like close to Niagara Settings.
So we can quickly peep and move on.

**Comment by Rod911** [comment] 2021-07-07 10:15
Duplicate of #152

**Closed** 2021-07-07 10:15 UTC
Labels: duplicate
