### ISSUE TITLE
Weather widget

### ISSUE THREAD

**Issue by spottech** [8bitPit/Niagara-Issues#2647] opened 2024-04-04 14:29 UTC
### Is your feature request related to a problem?

Hello,
It's possible to add option for open an app or Google weather?
And chose weather proviseur?
Thanks

### Describe the solution you'd like

Hello,
It's possible to add option for open an app or Google weather?
And chose weather proviseur?
Thanks

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-04-11 13:15
Hey there, thanks for the request.
I'll close this as a duplicate of #1510 / #407. Perhaps the answers there and the [linked article ](https://help.niagaralauncher.app/article/105-weather-widget) help here.

**Closed by NiagaraSupport** 2024-04-11 13:15 UTC
