### ISSUE TITLE
Install missing apps enhancement/problem

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1198] opened 2020-02-26 21:09 UTC
My uninstalled app is no longer in the apps list but remains in favourites. I think it should be like this instead:
If you factory reset your phone or uninstall Niagara and _then_ remove some app, it should remember that app to reinstall it when you install Niagara back.
But when you first uninstall an app and then reset/uninstall Niagara, the previously removed app should not be suggested to reinstall when you add Niagara back.

**Comment by 8bitPit** [comment] 2020-02-27 08:46
Agree completely Martin. That's also how it should be. When you uninstall an app while Niagara is running as your default launcher, apps will be removed from every category (e.g. favorites). 
Your issue might be caused by having an older backup. As far as I know, Google backs up the app once a day (usually at night). This means when you uninstall a favorite and then uninstall Niagara, then reinstall Niagara, your backup from yesterday will be used. On this snapshot, Niagara has the app you uninstalled marked as a favorite but also notices that it was uninstalled. That's why it will keep the app but gray it out.

**Comment by 8bitPit** [comment] 2020-03-15 17:31
Hope my previous reply helped to clarify how Niagara handles uninstalled apps and why it does that. If not, please leave a comment.

**Closed by 8bitPit** 2020-03-15 17:31 UTC
