### ISSUE TITLE
Dynamic app suggestions

### ISSUE THREAD

**Issue by Sba12** [8bitPit/Niagara-Issues#1782] opened 2021-12-22 18:10 UTC
### Is your feature request related to a problem?

So here me out, Niagara wants to keep our home page as **clean and neat** as possible but at the same time we always use so **many apps** throughout the day.

In the **morning** commuting to work I need: music, trains app, work email and a book.
In the **evening** while I'm relaxing I need: podcast, YouTube and socials.

### Describe the solution you'd like

**Dynamic app suggestions** - in the home page apps come and go depending on what I need at that moment. 

Letting the user choose the sets of apps they need might be easier for you but maybe not so simple for us, automatic selection of the apps based on use time might be harder for you but easier for users.

Either way it would be a great way to _combine cleanness and maximum proficiency._

**Comment by Rod911** [comment] 2021-12-30 17:25
Duplicate of #165

**Comment by Rod911** [comment] 2021-12-30 17:26
Please leave any suggestions/comments in the linked thread.

**Closed** 2021-12-30 17:26 UTC
Labels: duplicate
