### ISSUE TITLE
Option to set a password to access hidden apps

### ISSUE THREAD

**Issue by 4SFED** [8bitPit/Niagara-Issues#1076] opened 2019-12-09 12:35 UTC
I would like to be able to hide apps and have all hidden apps only accessible via a password to prevent unauthorised users (ie: children) accessing things like YouTube, banking apps and so on.

**Comment by 8bitPit** [comment] 2019-12-09 17:08
Duplicate of #520

**Closed by 8bitPit** 2019-12-09 17:08 UTC
