### ISSUE TITLE
Centre wallpaper

### ISSUE THREAD

**Issue by miyke2525** [8bitPit/Niagara-Issues#1004] opened 2019-09-21 06:35 UTC
Love the launcher, but I think there is a problem placing wallpapers on the home screen. Most wallpapers are designed to display the centre of the image on the main home screen, but Niagara just aligns the left edge of the image with the edge of the display, which usually spoils the effect. Really need an option to centre the wallpaper.

**Comment by 8bitPit** [comment] 2019-09-21 08:03
Hi @miyke2525, thanks for the report. Which app do you use for applying wallpapers? Have you tried setting your wallpaper with Google Photos or Google Wallpaper?

**Comment by 8bitPit** [comment] 2019-09-29 18:28
Duplicate of #688

**Closed by 8bitPit** 2019-09-29 18:28 UTC
Labels: duplicate
