### ISSUE TITLE
Google "swipe to search" immediately closing again

### ISSUE THREAD

**Issue by sbellon** [8bitPit/Niagara-Issues#1500] opened 2021-02-06 10:47 UTC
**Describe the bug**
Swiping the Google icon upwards opens, but then immediately closes the Google search again.

If I just click on the Google icons and then the Search tab in the middle, then the search successfully opens (two clicks instead of one swipe).

This worked in the past with Niagara Launcher. I can't say for sure, but I think this behaviour started with 1.0.1.

I already tried to clear the cache, clear application data, and even did a complete uninstall/reinstall with a reboot in between.

**To Reproduce**
1. Activate the Google icon in the Niagara Launcher configuration
2. Swipe upwards the Google icon

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 5 II
 - Android version: Android 10

**Screenshots**
It happens so quickly, not possible to take a screenshot, I'm afraid.

**Comment by 8bitPit** [comment] 2021-02-06 14:46
Thanks for the bug report @sbellon. Unfortunately, it's caused by Google and we can't fix it: https://help.niagaralauncher.app/article/89-swipe-to-quick-search-with-google-not-working

**Comment by sbellon** [comment] 2021-02-06 16:13
Thanks for the quick answer. So, is this caused by an update of the Google app, coincidentally also a few days ago?

**Comment by sbellon** [comment] 2021-02-13 08:35
Sorry for being insisting, but I am not completely convinced yet. ;-)

Your referenced post above is from January 7th, 2021. I got to know about Niagara Launcher even after that and installed it a few days prior to 1.0.0 launch. At that time, Google swipe to search worked beautifully. So, at least on my phone, after 2021-01-07 the swipe action worked, but stopped at some point later.

I now tried to send the intent `com.google.android.googlequicksearchbox.GOOGLE_SEARCH` with MacroDroid and that also opens up the Google quick search nicely. So, can't you also just send `com.google.android.googlequicksearchbox.GOOGLE_SEARCH` intent on a swipe-up action on the G icon?

Perhaps you can share what Niagara Launcher is currently doing on a swipe-up action on the G icon, so I can try to emulate the same with MacroDroid?

I bought lifetime license of Niagara on release day of 1.0.0 and would be quite happy if you could take a look at this once more.

**Comment by 8bitPit** [comment] 2021-03-23 18:38
@sbellon interesting, thanks for sharing! I'm indeed using another intent action to open quick search ( `com.google.android.googlequicksearchbox.TEXT_ASSIST`). The problem with `com.google.android.googlequicksearchbox.GOOGLE_SEARCH` is, however, that the Google app doesn't automatically open the keyboard when launched.

**Comment by sbellon** [comment] 2021-03-23 21:03
For me (Sony Xperia 5 II, Android 11) the intent `com.google.android.googlequicksearchbox.GOOGLE_SEARCH` *does* automatically open the keyboard when launched.

**Comment by 8bitPit** [comment] 2021-03-25 14:21
Huh, okay, weird. It doesn't work on my Pixel 5 and Galaxy M31. I'm afraid we should stick to the other intent action as it probably works on more devices. Here's how it looks on the Pixel. (Don't mind the shifted colors, GitHub doesn't like to encode the video properly, for some reason.)

https://user-images.githubusercontent.com/9284845/112488026-7e0ad680-8d7d-11eb-8d3b-1c325b754bcd.mp4

**Comment by sbellon** [comment] 2021-03-25 14:39
Really weird.

But then, there's no workaround / chance for "swipe to search" working on my device? :-(

**Comment by 8bitPit** [comment] 2021-03-26 11:58
You could write Google about those two bugs, but I fear it will take a while until we fix them. For the sake of simplicity, I wouldn't add a workaround as the bug is not [impactful enough](https://help.niagaralauncher.app/article/8-niagaras-design-principles), sorry.

**Comment by sbellon** [comment] 2021-05-13 07:17
Just wanted to give you feedback: I updated to 1.2.0 beta today, configured the Niagara button and selected Google Search as "swipe up" action and it works just fine now. :+1:

**Comment by 8bitPit** [comment] 2021-05-15 17:16
Awesome, @sbellon, thanks for letting me know! I'll close the issue then :D

**Closed by 8bitPit** 2021-05-15 17:16 UTC
Labels: bug, infeasible

**Comment by 8bitPit** [comment] 2021-05-20 09:41
For anyone else experiencing the issue. Here's how to activate the Niagara button: https://help.niagaralauncher.app/article/116-niagara-button
