### ISSUE TITLE
Hide apps based on focus mode

### ISSUE THREAD

**Issue by jbytes1027** [8bitPit/Niagara-Issues#1464] opened 2021-01-13 17:29 UTC
**Describe the solution you'd like**
hide apps that are blocked by current digital wellbeing focus mode

**Comment by 8bitPit** [comment] 2021-01-16 14:52
I think that's a duplicate of: https://github.com/8bitPit/Niagara-Issues/issues/1119

**Closed** 2021-01-16 14:52 UTC
Labels: duplicate
