### ISSUE TITLE
Manually selected icon stays after icon pack uninstalled

### ISSUE THREAD

**Issue by KrzysztofKozlowski** [8bitPit/Niagara-Issues#1322] opened 2020-06-19 17:39 UTC
**Is your feature request related to a problem? Please describe.**
I know that this issue is not essential, but nevertheless it's something that doesn't work as it should, in my opinion. When you uninstall currently active icon pack, all icons that were set automatically are changed to their default versions. However, the ones that you set up manually stay the same. If it was your only icon pack, you are stuck and unable to change them back to default. When you try to edit the icon you get a message saying that you need an icon pack. The only solution is to install any icon pack, change icons to default manually or choose default icons in Look menu and then unistall it back.

Potentially connected to #830 (?)

**Describe the solution you'd like**
I think that option to reset icon to default should be accessible regardless of icon pack being installed or not. Just a button saying "Reset to defult" together with prompt that links to Play Store. I don't think it should be especially hard to implement since the functionality is already there.

In the end I would like to state that I absolutely love using Niagra Launcher and really appreciate all your work dedicated to making it better and better.

Kind regards,
Krzysztof

**Comment by Rod911** [comment] 2020-06-19 18:02
Duplicate of #553

**Comment by KrzysztofKozlowski** [comment] 2020-06-19 18:30
Maybe I didn't say what was on my mind correctly, but I don't see how is my issue duplicate of #553 since in there you:

1. Install icon pack.
2. Apply icon pack.
3. Want to change one of the automatically changed icons back to default and can't do that.

And in my case:

1. Install icon pack.
2. Apply icon pack.
3. Change one of the icons your icon pack was missing manually to something similar from icon pack.
4. Want to get rid of an icon pack (it bored you or something) and uninstall it.
5. All icons change back to default except the one you have changed manually. It seems natural since you don't want to use this icon pack anymore that it should revert to default as well.
6. If you don't have any other icon pack installed you can't revert this one icon back to default manually because Niagra wants you to install one. In the end most icons are default and you are stuck with one icon from pack that you don't want to use anymore.

Or is the solution for the other issue so similar that it would resolve this one as well? In that case sorry for taking up your time. All the best!

**Comment by 8bitPit** [comment] 2020-09-03 04:59
That's a bug then, thank you very much for the detailed explanation :)

**Comment by 8bitPit** [comment] 2021-12-15 11:03
Fixed in v.1.5

**Closed by 8bitPit** 2021-12-15 11:03 UTC
Labels: bug, in progress
