### ISSUE TITLE
[Feature request] Hiding apps from favorites when locked by Screen time/ Digital wellbeing

### ISSUE THREAD

**Issue by alex-devg** [8bitPit/Niagara-Issues#2294] opened 2023-06-01 17:28 UTC
The title might be clear enough

I think it would be useful to hide the apps that are locked by digital wellbeing instead having an app listed that we can't open

**Comment by Amorphous404** [comment] 2023-06-11 20:17
Hi @alex-devg, Thank you for your suggestion. It appears that the issue you've raised is a duplicate of #1119. Please follow up on the older issue for further updates.

• Duplicate of #1119

**Closed** 2023-06-11 20:19 UTC
