### ISSUE TITLE
Dim Wallpaper in Home/Favorites

### ISSUE THREAD

**Issue by CerberusCode** [8bitPit/Niagara-Issues#2471] opened 2023-12-06 20:33 UTC
### Is your feature request related to a problem?

A bit ig, its all about the readability

### Describe the solution you'd like

Since always been using this launcher for long i always used a dark/semi dark wallpaper till now & in my phone settings i always enable the "Adjust wallpaper to dark mode". But it still not satisfy me when it comes to readability, since this launcher have come an option to enable dim wallpaper in applist, i really love it the readability is very excellent for me. Now whats in my mind is, what if you will add an option too for the homescreen not just only in the applist. I hope this can be add in the futures update. Thank, have a wonderful day

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-04-19 11:45
Hey there, thanks for your suggestion.
I'll close this as a duplicate of #2342. Please feel free to check out the discussion and responses there.

**Closed by NiagaraSupport** 2024-04-19 11:45 UTC

**Comment by AndydeCleyre** [comment] 2025-10-05 17:57
As the [latest comment at #2342](https://github.com/NiagaraLauncher/Niagara-Issues/issues/2342#issuecomment-2323725887) states, that issue does not cover what the request is here.

> . . . 2694 and 2471 are about being able to ALSO dim the main screen, as one can currently dim the app-list and search. . . .
