### ISSUE TITLE
Amazon Music Artwork not showing

### ISSUE THREAD

**Issue by therrorie** [8bitPit/Niagara-Issues#1090] opened 2019-12-15 09:36 UTC
**Describe the bug**
When playing music from Amazon Music Prime or Unlimited artwork is not displayed on the desktop above the apps list

**To Reproduce**
1. Use of Amazon Music

**Smartphone (please complete the following information):**
 - Google Pixel 3a
 -  Android 10

**Screenshots**
![Niagara_Desktop_AmazonMusic](https://user-images.githubusercontent.com/3797597/70860817-bb4faa00-1f26-11ea-9891-1e293d9130de.png)

**Comment by Montell2099** [comment] 2019-12-15 18:19
#1052 The developer is aware of this. I'm pretty sure this is a widespread bug amongst all different kinds of media players that occurs every now and then. 

Soundcloud is also affected, but I haven't found a way to replicate the bug consistently.

**Comment by FreshPrince85** [comment] 2019-12-15 18:31
Spotify is also affected.

**Comment by Montell2099** [comment] 2019-12-15 18:35
> Spotify is also affected.

Yes, @8bitPit already mentioned that in the issue (1052) I linked to. Doesn't seem to be an app-specific problem.

**Comment by 8bitPit** [comment] 2019-12-16 19:32
Duplicate of #1052

**Closed by 8bitPit** 2019-12-16 19:32 UTC
Labels: bug
