### ISSUE TITLE
Notifications not showing, weather requires GPS

### ISSUE THREAD

**Issue by shooky-web-dev** [8bitPit/Niagara-Issues#719] opened 2019-01-24 07:04 UTC
On Samsung Galaxy S9+ notifications are not shown even the app has permissions. Also weather  shows warning to turn on location even it's on but using battery saving mode.

Edit:
Notifications now work after, disable/enable them again. The weather issue is still valid.

**Comment by 8bitPit** [comment] 2019-01-24 12:31
Duplicate of #178

**Closed by 8bitPit** 2019-01-24 12:31 UTC
