### ISSUE TITLE
Option to remove "recently searched" apps from "Niagara Search"

### ISSUE THREAD

**Issue by Walker65725** [8bitPit/Niagara-Issues#2630] opened 2024-03-19 06:58 UTC
### Is your feature request related to a problem?

Dear Devs,

When I swipe down on the home screen, and search for an app, it stays there as "last result" or "frequently searched".
But I don't see an option to remove those apps from that list.

All I can find is "hide from app list" but that puts it into the 'hidden apps' list and from there I have to retrieve it again.
Though it removes that app from that (after-search) list
But, it's like 10 extra steps.

Anything you guys can do about that?
Thank you.
Added below is the screenshot of what I was referring to.
![Screenshot_2024-03-19-12-25-08-31_a4824db61f40c53807964ea8b14c92fe](https://github.com/8bitPit/Niagara-Issues/assets/163980462/40eab423-7cc8-4489-8f3d-2a0fb0b3cd6e)

### Describe the solution you'd like

I'd appreciate if you guys can add an option to clear "recent searches" 
Or, if you can make it so that the list clears itself after a set amount of time (say 24 hours)
You attention to this problem is highly appreciated.
Thank you.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-04-11 09:35
Hey there, thanks for your request,
I'll close this as a duplicate of #2456. We don't have immediate plans to add the toggle you mentioned, but it's been requested enough that I'll bring it up for discussion again. Could you tell me why it's bothering you specifically? Privacy, aesthetics, or something else?

**Closed** 2024-04-11 09:35 UTC
