### ISSUE TITLE
Wallpaper not scaling appropriately 

### ISSUE THREAD

**Issue by aureole1599** [8bitPit/Niagara-Issues#863] opened 2019-05-06 02:36 UTC
When assigning a wallpaper, the launcher for some reason does not apply it correctly toward the resolution of the phone. The image is applied in a lower resolution either by zooming in or your launcher is capping the resolution of the wallpaper being assigned. I have even made wallpapers in photoshop to the correct resolution and PPI and the image still appears lower resolution after applying

**Comment by 8bitPit** [comment] 2019-05-07 08:31
Thanks for the report @aureole1599. Have you tried applying your wallpaper with the Google Photos app?

**Comment by aureole1599** [comment] 2019-05-07 18:56
Just tried. It doesn't center the image correctly. For example, there's
images that are meant to cover the galaxy camera cut-out and they dont line
up with them. So it's not centering and appears to be zooming in. I'm not
sure if it's recognizes the resolution correctly.


On May 7, 2019 at 4:31 AM, <Peter <notifications@github.com>> wrote:

Thanks for the report @aureole1599 <https://github.com/aureole1599>. Have
you tried applying your wallpaper with the Google Photos app?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/8bitPit/Niagara-Issues/issues/863#issuecomment-489987086>,
or mute the thread

**Comment by WuHaoyang000** [comment] 2019-05-10 02:13
You can delete all wallpaper apps, including plug-in apps

**Comment by aureole1599** [comment] 2019-05-10 03:08
I dont understand why I'd need to delete those apps. I'm not even trying to
change the background through those apps. It doesn't adjust to scale or
center properly no matter where the image comes from


On May 9, 2019 at 10:13 PM, <WuHaoyang000 <notifications@github.com>>
wrote:

You can delete all wallpaper apps, including plug-in apps

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/8bitPit/Niagara-Issues/issues/863#issuecomment-491129060>,
or mute the thread

**Comment by Rod911** [comment] 2019-05-10 03:36
And this issue does not occur with other launchers like Nova?

**Comment by aureole1599** [comment] 2019-05-10 05:47
Correct. This is the first launcher I've had this issue with. The hole
punch wallpapers do not line up with the galaxy s10. Everything is
off-center and maybe even zoomed in.


On May 9, 2019 at 11:36 PM, <Malcolm <notifications@github.com>> wrote:

And this issue does not occur with other launchers like Nova?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/8bitPit/Niagara-Issues/issues/863#issuecomment-491143787>,
or mute the thread

**Comment by 8bitPit** [comment] 2019-05-12 20:20
Okay, thanks for the replies. I'll try to fix it.

**Comment by aureole1599** [comment] 2019-05-12 23:22
No problem. I love helping out if you ever need anything. I love the
launcher


On May 12, 2019 at 4:20 PM, <Peter <notifications@github.com>> wrote:

Okay, thanks for the replies. I'll try to fix it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/8bitPit/Niagara-Issues/issues/863#issuecomment-491626078>,
or mute the thread

**Comment by 8bitPit** [comment] 2019-05-13 19:56
Thank you @aureole1599 :)

**Comment by 8bitPit** [comment] 2020-03-17 20:42
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/863

**Closed by 8bitPit** 2020-03-17 20:42 UTC
Labels: bug
