### ISSUE TITLE
Temporary widgets pushing app icons beyond the bootom of homescreen.

### ISSUE THREAD

**Issue by lalboy** [8bitPit/Niagara-Issues#2199] opened 2023-02-08 04:20 UTC
The music widget keeps pushing apps down on the homescreen. 
Theres usually no space at the bottom and the apps get hidden. But the icons become out of reach if i pull all homescreen content towards the top.

**Comment by Amorphous404** [comment] 2023-02-08 07:41
This is an intended behavior. To workaround this issue, Only place 8 apps on your favorites page; you can also reduce the icon size from Niagara settings.
(Niagara Settings -> Look -> App icon size)

We also added a little tweak around the behavior since v1.8.0,

Check: https://github.com/8bitPit/Niagara-Issues/issues/1669

> 🎵 Media Widget · If you move the Niagara Launcher past its default position, the media widget begins to move the widget up instead of the favorites down. Currently, this is not supported if you replace Niagara’s clock with a widget.

https://medium.com/niagara-launcher/going-global-6bb58c2d6bb7


Duplicate of #1669

**Closed** 2023-02-08 09:02 UTC
