### ISSUE TITLE
Being able to remove icons completely 

### ISSUE THREAD

**Issue by FatehMammadli** [8bitPit/Niagara-Issues#2256] opened 2023-04-22 19:00 UTC
### Describe the solution you'd like

One option is to use Niagara dots as icons, but for a more minimalist and less distracting view, it would be amazing to eliminate the icons altogether.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-04-22 19:28
Duplicate of #140

**Closed** 2023-04-22 19:28 UTC
