### ISSUE TITLE
Mi dual apps

### ISSUE THREAD

**Issue by prabhumns** [8bitPit/Niagara-Issues#757] opened 2019-02-14 07:36 UTC
In miui there's a feature for creating dual apps. I created a dual app for whatsapp. So when u click the actual whatsapp icon it is again asking which whatsapp to open i.e., whether to open the actual whatsapp or the dual app. When i click the dual whatsapp it is showing an error.

**Comment by 8bitPit** [comment] 2019-02-15 19:24
The launcher should support multiple profiles already. Which version of Niagara are you using?

**Comment by 8bitPit** [comment] 2019-02-24 14:11
You can reopen the issue anytime, but for now I'm closing it.

**Comment by prabhumns** [comment] 2019-02-27 05:46
I am using version 0.7.3. it is supporting dual apps but we have to click twice for that. Two different icons for different profiles should be there

**Comment by 8bitPit** [comment] 2019-04-16 20:39
Sorry, me and the community couldn't reproduce the issue, it might be a bug from Xiaomi's end.

**Comment by help-14** [comment] 2019-06-25 02:47
Using dual app will result in "App isn't available"

https://imgur.com/UakDcZB

**Comment by 8bitPit** [comment] 2019-06-25 18:50
@help-14 Can you please test opening the same app with another Launcher that is based on Google's Launcher3? Lawnchair Launcher is such one, for example.

**Comment by prabhumns** [comment] 2019-06-25 19:39
Have look at this image to get more clarity on the situation https://drive.google.com/file/d/15XHLQq6EAQkGmfgBTDToSadNOhmmThYT/view?usp=sharing

And yes. It is similar with Lawnchair launcher

**Comment by 8bitPit** [comment] 2019-06-28 19:25
@prabhumns Sorry for that. Because you can reproduce the issue with a launcher that is based on Google's launcher, I think it might caused by Xiaomi. You could try out [Island](https://play.google.com/store/apps/details?id=com.oasisfeng.island&hl=en), this app creates a work profile which should be supported by Niagara or most other third party launchers.

**Comment by 8bitPit** [comment] 2019-08-17 12:56
I'm closing this issue because it seems that this is a bug caused by Xiaomi and does not affect many users. I'm sorry for any inconveniences. The app [Island ](https://play.google.com/store/apps/details?id=com.oasisfeng.island&hl=en) let's you create a separate work profile which should do the same as Xiaomis Dual App feature.

**Closed by 8bitPit** 2019-08-17 12:56 UTC
Labels: bug, wontfix
