### ISSUE TITLE
Disable hidden apps from being listed under app search

### ISSUE THREAD

**Issue by Ujwal-B** [8bitPit/Niagara-Issues#2951] opened 2024-10-04 07:11 UTC
### Is your feature request related to a problem?

Apps which are disabled are still visible when initial few letters during search matches with the app names. It would be nice to toggle this visibility so we have the option of completely removing them from the app drawer.

### Describe the solution you'd like

Having an option to toggle the visibility of hidden apps during app search in niagra settings looks like a good idea to me.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-10-04 16:19
Hey there, thanks for the suggestion.
I’ll note your feedback for future discussion. Could you elaborate on why it’s important for you to have these hidden? As far as I know, it’s not currently planned since it would require significant changes for relatively little impact. I’ll close this as a duplicate of #468 and related tickets. Should anything change, we'll update you accordingly.

**Closed by NiagaraSupport** 2024-10-04 16:19 UTC
Labels: duplicate

**Comment by Ujwal-B** [comment] 2024-10-04 19:56
Hey there,

Thanks for checking up on the ticket. I primarily hide apps to stop myself
from accessing them. Having them not be visible at all even when searched
for would reduce its reach and help keep it away from my mind. I'm aware
that we can unhide it via settings if I want to access it, but since it
requires me to open the settings and uncheck the required app, it is a
mental barrier that keeps me from doing that.

Since I'm using it for increasing productivity, having lesser access to
them is better. Sometimes when I need to search for some other app, let's
say "Duolingo", I start by typing D, and if I've hidden "discord", I can
still see it in the app menu because they both start with the same letter.

I can imagine the changes required to modify existing codebase to
accommodate this change, and I really appreciate your insight on this
suggestion. I'll be happy to know if you consider this feature in any
future updates.
