### ISSUE TITLE
Niagara keeps asking to be set as default launcher

### ISSUE THREAD

**Issue by lainovic** [8bitPit/Niagara-Issues#1917] opened 2022-04-10 17:59 UTC
### Describe the bug

![Screenshot_20220410-195014_Niagara Launcher](https://user-images.githubusercontent.com/57601153/162632707-2e64f7f9-f4fd-4b33-b9bb-54d3c33837cb.jpg)

Should be evident from the screenshot. Selecting Niagara as rhe default launcher doesn't help, the popup doesn't go away.

Also, tapping on 'always' select, when asked, doesn't help either, as in the image below.

![Screenshot_20220410-195428_Android System](https://user-images.githubusercontent.com/57601153/162632810-4825ad5a-42b3-4942-9369-63c4d041666d.jpg)

### Steps to reproduce

None needed.

### Device name

Samsung Galaxy Note 20 Ultra

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20220410-195428_Android System](https://user-images.githubusercontent.com/57601153/162632850-ca1afca2-ecf5-427a-92f8-07b4525b6219.jpg)
![Screenshot_20220410-195014_Niagara Launcher](https://user-images.githubusercontent.com/57601153/162632854-a1a0545a-b5ad-4fc2-9949-0edcb74a268d.jpg)

**Comment by Oddward** [comment] 2022-04-10 18:15
This is a duplicate of recent issue #1864, please track it there, and check the [help article](https://help.niagaralauncher.app/article/102-niagara-launcher-not-staying-as-default). 

If you haven't already, install one of the latest beta versions from [releases](https://github.com/8bitPit/Niagara-Issues/releases)

**Closed by Oddward** 2022-04-10 18:15 UTC
Labels: bug
