### ISSUE TITLE
Look at the right ,bug with scrolling letters

### ISSUE THREAD

**Issue by viktor0112** [8bitPit/Niagara-Issues#1242] opened 2020-04-06 17:53 UTC
![Screenshot_20200406-205258](https://user-images.githubusercontent.com/63256663/78589292-a8037a00-7848-11ea-9934-ba58fee0fc0b.png)
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by Martin5001** [comment] 2020-04-07 07:31
The same happened to me after going out of game in landscape mode. I was rotating the phone from landscape to portrait simultaneously with the home button press. Android 9, Samsung Galaxy J7

**Comment by alvinongko** [comment] 2020-04-09 03:35
I have the same issue too. Happens every time i exit landscape game. I'm using redmi note 8. For the moment, restarting the launcher will fix the issue
![Screenshot_2020-04-09-09-00-38-355_bitpit launcher](https://user-images.githubusercontent.com/28228513/78855341-d2725480-7a4d-11ea-93a0-eb0d17b019f4.jpg)

**Comment by Martin5001** [comment] 2020-04-09 07:23
For me clicking Home button was enough to fix it.

**Comment by ccocallas** [comment] 2020-04-12 00:13
I am also having this happen on my Samsung Galaxy 8+, Android 9. 

Steps to reproduce:
1. From the Home screen, rotate the phone to Landscape.
2. Tap any app that supports Landscape viewing, such as Gmail.
3. Tap the Back button to return Home.
4. Rotate the phone to Portrait.
   a. Notice that all the Home screen apps and widget are now higher on the screen than usual.
5. Scroll the side of the screen to access the alphabetic listing.
   a. Become alarmed that all the letters of the alphabet are no longer respecting social distancing protocols!

The only restoration tactic that works for me is to Restart Launcher from the Advanced section of Launcher Settings.

**Comment by 8bitPit** [comment] 2020-04-12 20:42
Thank you everyone for your reports. Unfortunately I haven't found a way to reproduce this. When I open another app in landscape mode and get back to Niagara, everything's normal (Android 10). I also tried this on an emulated device (Android 5). I will soon try this on an Android 9 emulated device as well.

**Comment by mindphreak** [comment] 2020-04-13 15:01
Hi Pit, I'm using a Xiaomi note 5 pro running on Android 9 (MIUI 11.0.3). I am stumbling upon this issue very often. I haven't found a proper way to reproduce it. At times it gets corrected. And then again goes back to the same state.
![Screenshot_2020-04-13-15-48-28-511_bitpit launcher](https://user-images.githubusercontent.com/30364141/79131165-088e3c00-7da0-11ea-8120-14f571802322.jpg)

**Comment by 8bitPit** [comment] 2020-04-14 18:38
@mindphreak really interesting, thanks for sharing!

**Comment by Martin5001** [comment] 2020-04-14 18:57
Yeah to me this happened with specific game too, but I haven't realized it till now. It was PC Creator – PC building simulator.

**Comment by mindphreak** [comment] 2020-04-14 19:40
@8bitPit No probs. Good luck with it..! Here is a bonus observation. After breaking it using Stick Cricket 2, it was corrected when I ran a game (Hitman Sniper) which do not collapse the scroll.

**Comment by nickclapp** [comment] 2020-04-17 13:17
Same issue here, was playing Hitman Go in landscape mode. Left the game and the alphabet was at top of screen identical to the other screenshots shared. Android 9. Only fix was to restart the launcher.

Looks like during the transition from landscape to portrait it is using the height of the landscape screen instead of portrait screen which leads to the alphabet being wrongly positioned at the top of the screen.

**Comment by 8bitPit** [comment] 2020-04-17 18:22
Hey, I tried my best to fix the bug, but because I cannot reproduce it, it's unclear whether I succeeded. Can you please install [this apk](https://drive.google.com/open?id=1yKeyVWmbClhB-FKjIr72ArwKq1cZU4Fw) and check if issue doesn't appear anymore?

**Comment by ccocallas** [comment] 2020-04-17 18:38
That seems to work for me - I can no longer replicate the problem in the same manner as before!

**Comment by 8bitPit** [comment] 2020-04-17 18:44
Awesome, thank you for testing!

**Comment by mindphreak** [comment] 2020-04-17 22:36
Well done..! You fixed it..! Works well for me.

**Comment by viktor0112** [comment] 2020-04-17 22:39
No they didnt

На сб, 18.04.2020 г., 1:37 ч. mindphreak <notifications@github.com> написа:

**Comment by alvinongko** [comment] 2020-04-23 12:52
Works for me. Thanks!

**Comment by 8bitPit** [comment] 2020-04-25 21:40
@viktor0112 please try out v0.24.2

**Comment by 8bitPit** [comment] 2020-04-25 21:40
@mindphreak & @alvinongko great, thanks for letting me know :)

**Comment by 8bitPit** [comment] 2020-04-25 21:40
Fixed in v.0.24

**Closed by 8bitPit** 2020-04-25 21:40 UTC
Labels: bug
