### ISSUE TITLE
calendar app change icon to current date number

### ISSUE THREAD

**Issue by weeowey** [8bitPit/Niagara-Issues#2045] opened 2022-09-07 18:15 UTC
### Is your feature request related to a problem?

I don't like that my calendar app's icon doesnt change to the correct day number i.e, 17 on the 17th of august, 2 on the 2nd september, etc.. 

### Describe the solution you'd like

I would like the calendar app to change it's icon every day to the current date number (i.e, the date is the 17th of August and the icon will change to have a 17 on it) 

(if supported by the icon pack installed)

This will add some extra polish to the launcher if it could do this, possibly even make it a pro feature.

I do see some possible issues implementing this, but if you don't ask, you don't get, but it irks me that my calendar app doesnt change it's icon to the correct date number like it used to. Small detail, i know, but i feel like it wouldnt go unappreciated for that little extra piece of detail.

All the best, and thank you for making such a great, clean launcher!

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment] 2022-10-15 06:44
No comment since after a month and half.

**Comment by Amorphous404** [comment] 2022-12-15 07:04
Duplicate of #533, you can request to open up the previous ticket and add your feedback there.

Thank you

**Closed** 2022-12-15 07:05 UTC
Labels: duplicate

**Comment by sbach89** [comment] 2023-05-20 16:00
@Amorphous404 #533 is closed

**Comment by Amorphous404** [comment] 2023-05-20 17:14
Reopened it :)
