### ISSUE TITLE
Widget's with swipe

### ISSUE THREAD

**Issue by nefas83** [8bitPit/Niagara-Issues#657] opened 2018-12-17 09:35 UTC
Hi,

The only thing I miss are widget's.
Maybe is it possible to bring widget's to Niagara with some nice swiping like the app drawer.

At the moment it doesn't matter if I swipe left or right. 
But as additional features it could be possible to set one side (by user choice) for swiping through widget's.
One widget per screen like a virtel deksoto that's works as an overly. 
Not like a complete desktop screen. More like a window over the front screen. 

So I can use the calendar widget to see my schedules.
With a press on the home buttony the overlay fade away and the "background" Niagara can back to front.

I will try to create an example picture today.

Best regards

**Comment by Rod911** [comment] 2018-12-18 02:57
You can see #117 and #59 for widget support discussions.
As for your suggestion about an overlay, here's a Chinese app which does that system wide. It's called[全局负一屏](https://www.coolapk.com/apk/com.example.xf.negativeonescreen) which ends up looking like ![Screenshot](https://i.imgur.com/moN77yj.png)

**Comment by 8bitPit** [comment] 2018-12-21 22:40
Thanks for linking & your suggestion @Rod911 :)

**Comment by 8bitPit** [comment] 2018-12-21 22:41
Duplicate of #59

**Closed by 8bitPit** 2018-12-21 22:41 UTC
