### ISSUE TITLE
Sort function not working..

### ISSUE THREAD

**Issue by jook1356** [8bitPit/Niagara-Issues#601] opened 2018-11-23 14:21 UTC
After this update, app sort doesn't work for another language (Korean). Some apps sorted correctly, but the others not. Check please. Thank you very much, This launcher is very comfortable since I was born!

**Comment by jook1356** [comment] 2018-11-24 15:15
I am the first time to github so I can't find where to upload screenshots.

It's something like this.


#
인터넷
뮤직
갤러리
동영상

A
Adobe reader
Ad blocker

B
Black me
Backdrops
Billboard charts

C
Camera
Chrome

As you see, English sort working properly, but another languages are not. 

+ Um... where can I upload screenshots...

**Comment by 8bitPit** [comment] 2018-11-24 22:46
Thanks for helping, what behavior would you prefer: sorting each Korean written app in a custom section or integrate them in the Latin alphabet (Romanization: https://en.wikipedia.org/wiki/Revised_Romanization_of_Korean)

PS: You can just paste images in your comment :)

**Comment by jook1356** [comment] 2018-11-25 07:49
Thank you. But I want to ask that, will you solve this problem? It's really serious problem for me.. The solution that you noticed is temporary...

**Comment by 8bitPit** [comment] 2018-11-25 22:32
Yeah, I'm trying to find the best solution which works for the most amount of people.
So which implementation would you prefer:

> what behavior would you prefer: sorting each Korean written app in a custom section or integrate them in the Latin alphabet (Romanization: https://en.wikipedia.org/wiki/Revised_Romanization_of_Korean)

**Comment by jook1356** [comment] 2018-11-26 17:20
I think sorting each Korean written app in a custom section is more better.

By the way, before the update, Korean sort function work as well.

Something like this. I don't know why it doesn't work suddenly..

ㄱ
게임
그랩

ㄴ
네이버
네이버 카페

ㅌ
토렌트
트렌드

**Comment by 8bitPit** [comment] 2018-12-26 21:04
Duplicate of #575

**Closed by 8bitPit** 2018-12-26 21:04 UTC
