### ISSUE TITLE
Vibration on right swipe does not work consistently

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#988] opened 2019-09-08 06:59 UTC
When I swipe right phone vibrates slightly, but these vibrations are triggered only sometimes. Also the intensity is not always the same. (Actually it is so subtle sometimes that I had to turn on battery saver to disable vibrations to make sure I am not making the sound myself by my finger.)
(Android 9 on Nokia 5)

**Comment by 8bitPit** [comment] 2019-09-11 14:34
Interessting, but this might be caused by your device. Have you tried reproducing the issue on another phone? On my essential phone, for example the vibration's length and strength feels always the same.

**Comment by Martin5001** [comment] 2019-09-11 14:43
No I haven't. I currently don't have another phone to test. Having an option to disable vibrations would solve the problem for me.
I personally think it might be caused by my device in part with vibrations being not strong enough (other apps using stronger vibrations work normally, and I also recall this happened with another app when I set lower vibrations).

**Comment by Montell2099** [comment] 2019-12-15 18:31
I seldom use the right-swipe function but when I do, it seems to vibrate in a consistent matter using my Pixel 2.

**Comment by Martin5001** [comment] 2020-01-20 17:26
UPDATE: This problem is also present on Samsung Galaxy J7 (Android 9 Pie)

**Comment by 8bitPit** [comment] 2020-12-02 21:51
Fixed in v.0.34.0

**Closed by 8bitPit** 2020-12-02 21:51 UTC
Labels: bug
