### ISSUE TITLE
App title rather than icons.

### ISSUE THREAD

**Issue by Chaupeter** [8bitPit/Niagara-Issues#997] opened 2019-09-14 06:05 UTC
This feature is not related to any known bug.

Is it possible to have the option of displaying the App name ( title ) instead of the icon and to have this list left justified in the home screen. 

This would present a user with a list of apps to choose from rather than either an icon and title or just an icon which are the options at present.

Thank you for your consideration.

**Comment by Martin5001** [comment] 2019-09-14 16:48
Also when you select icons only option, the ripple effect shown behind them on tap should be disabled I think (or be under the icon itself only, not the area where text was supposed to be before), but there might be some reason for this, I don't know.

**Comment by 8bitPit** [comment] 2019-09-15 19:26
@Chaupeter do you mean something like this: #140

**Comment by 8bitPit** [comment] 2019-09-15 19:28
@Martin5001 the ripple shows you the item's touch area. I think changing it to a smaller circle would be inconsistent.

**Comment by 8bitPit** [comment] 2019-10-03 09:39
Duplicate of #140

**Closed by 8bitPit** 2019-10-03 09:39 UTC
Labels: question
