### ISSUE TITLE
Hide restricted apps in frequently used list

### ISSUE THREAD

**Issue by tmayoff** [8bitPit/Niagara-Issues#2277] opened 2023-05-12 13:45 UTC
### Is your feature request related to a problem?

I use the app timers and modes to restrict app usage throughout my day. However when apps are restricted they still appear as suggested apps on the main screen.

### Describe the solution you'd like

If possible (I'm not sure to what extent this is a One UI feature vs android) it'd be nice for Niagara to not show apps that are restricted as part of the list of frequently used list on the main screen.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-05-15 23:13
Hi @tmayoff, Thank you for your suggestion. It appears that the issue you've raised is a duplicate of #1119. Please follow up on the older issue for further updates. Thank you for your cooperation.

🔗 Merged with #1119

**Closed** 2023-05-15 23:13 UTC
