### ISSUE TITLE
The ability to access the app list via swipe

### ISSUE THREAD

**Issue by bala7s** [8bitPit/Niagara-Issues#738] opened 2019-02-04 11:08 UTC
It would be nice, if there would be an option to open the app list with a swipe like on Android Oreo's default home screen.

**Comment by 8bitPit** [comment] 2019-02-05 22:17
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/122

**Closed by 8bitPit** 2019-02-05 22:17 UTC
