### ISSUE TITLE
Dialer shortcut doesn't open

### ISSUE THREAD

**Issue by Fraterius** [8bitPit/Niagara-Issues#1328] opened 2020-06-24 14:24 UTC
**Describe the bug**
Speed dial created through sesame shortcut throws an error without any other actions when clicked through search menu or through app menu (pinned shortcuts). The same shortcuts work without any issues in Nova Launcher.

**To Reproduce**
1. Go to home screen
2. Swipe on dialer and choose edit icon then edit shortcuts
3. Choose Contacts and plus sign next to the speed dial. Then choose phone number to create speed dial shortcut for it.
4. When you search the shortcut it appears in list with no problem (also with avatar).
5. When you click the shortcut it only shows Error in popup and nothing else happens.

**Smartphone (please complete the following information):**
 - Device: Huawei p9 
 - Android version: 7

**Screenshots**
Unavailable

**Comment by Fraterius** [comment] 2020-06-26 20:44
Today I've created shortcut to direct dialer and it also doesn't work. Only thing that is showing up after click is:

Shortcut isn't available.

Other shortcuts seems to be working correctly. The only one which doesn't work is direct dial. If there's anything that I can provide just let me know.

**Comment by Fraterius** [comment] 2020-06-26 21:09
Maybe Niagara needs "Phone permission". Both Nova launcher and sesame shortcuts uses this permission but I don't see Niagara there to grant it this permission.

Right now I've tested every option I could to add direct dial shortcut on Niagara but it simple fails.

**Comment by Rod911** [comment] 2020-06-29 18:42
Unable to reproduce issue with provided steps.
Can you try refreshing shortcut data from Sesame settings and re-doing the above steps?

**Comment by Fraterius** [comment] 2020-06-29 19:22
@Rod911 yup I did that, and I did a lot other things. I think that it has something to do with Huawei dialer, or some kind of dialers in general (maybe something with permissions, **cause any other apps that is using this kind of feature which is direct dial is asking for phone permissions, for example nova launcher and sesame shortcut**).

To be clear after some investigation it's general problem with direct dial shortcut. When I try to add shortcut through Launcher Settings -> Features -> Add shortcut -> Contacts (Speed dial) -> pick phone number from address book, created shortcut also doesn't work but it throws different kind of message: Shortcut isn't available.

It's not problem related to sesame shortcut, when I pick this shortcut through sesame search (**not Niagara's one**) it works like a charm.

Recently I've found that other people also has this problem with direct dial shortcuts (there's exactly the same error as in my case):
https://www.reddit.com/r/NiagaraLauncher/comments/gu0g9i/-/fv7ciyg

If I can do anything to help You out just let me know, other than that it works great, Thanks in advance.

**Comment by Rod911** [comment] 2020-06-30 18:23
Funnily enough, I use Huawei too.
Niagara doesn't need that permission because the shortcuts are created by Sesame and not Niagara. So this might also be an issue with the Sesame integration, but I cant say anything for sure since Huawei has its own boatload of issues when it comes to third party stuff like launchers, notifications, etc,.

**Comment by Fraterius** [comment] 2020-07-01 00:45
@Rod911 I thought that this permission is needed not for creation but for using the shortcut (somehow it sounds more obvious to me), but I'm not a java/android expert.

I think it's not strictly Sesame related bug (I've reported it that way, cause I've found it there), like I said above at my device I'm unable to create usable shortcut to dial contact directly without contact app (with or without Sesame).

**Comment by Fraterius** [comment] 2020-07-05 17:41
Further investigation:
When I've got contact shortcut (contact shortcut to address book) and I swipe on it (there is SMS, call and email choices) and then I choose call, it does work. From what I understand those shortcuts are contact actions add-on in sesame.

Not sure what is the difference here in implementation but maybe it's a good point to start debugging this issue if we have two cases one which does work and other which doesn't.

**Comment by 8bitPit** [comment] 2020-07-06 20:54
Hi @Fraterius thank you for going so much into detail. It seems that the launcher needs the phone call permissions on older contact apps to open shortcuts. Here's what I found in Google's Launcher3 code: 
> Due to legacy reasons, direct call shortcuts require Launchers to have the corresponding permission. Show the appropriate permission prompt if that is the case.

Maybe Niagara Launcher will also request the needed permission in the future. Moreover, you can workaround it by downloading another contacts app (e.g. [Contacts by Google](https://play.google.com/store/apps/details?id=com.google.android.contacts)), hope that helps.

**Comment by Fraterius** [comment] 2020-07-06 21:55
Hello @8bitPit, I've already tried with Contacts by google as it's my primary contact app but no matter for what app the shortcut is created (stock Contact app or the one from google) I'm always getting "Shortcut isn't available". I really think that I've tried almost everything I could. Recently I even created sesame shortcut to tasker task which directly dials the number (the task also works in tasker) but with the same results.

Of course the Contact app has all the permissions and dialing directly within the app works without any problem.

This way or another, if You need any feedback/help from my part don't hesitate to ask. I'll gladly test any alpha/beta to provide some extra informations. Thanks a lot for great product and that Your spare some of your time on this issue.

**Comment by Rod911** [comment] 2020-09-05 07:43
@Fraterius should be fixed as of v0.32.2

**Comment by Fraterius** [comment] 2020-09-05 09:54
@Rod911 I honestly switched to newer phone where everything seems to be working correctly 😉. If someone can confirm that it's fixed than we can close this one.

**Closed** 2020-09-07 07:19 UTC
Labels: bug

**Comment by jeet-chanchawat** [comment] 2021-09-24 17:10
I too am facing this issue on Samsung A50 . Using niagra launcher with native direct dial shortcut. Having premium upgraded.

**Comment by 8bitPit** [comment] 2021-12-21 14:08
Thanks for reporting @jeet-chanchawat. We moved the conversation to https://github.com/8bitPit/Niagara-Issues/issues/1579
