### ISSUE TITLE
Web apps to homescreen

### ISSUE THREAD

**Issue by Pug2erto** [8bitPit/Niagara-Issues#804] opened 2019-03-23 23:22 UTC
Please add the ability to add web apps to the home screen I cannot find a way to do this with Niagara. Amazing launcher btw.

**Comment by 8bitPit** [comment] 2019-03-24 10:11
Thank you.

**Comment by 8bitPit** [comment] 2019-03-24 10:11
Duplicate of #785

**Closed by 8bitPit** 2019-03-24 10:11 UTC
