### ISSUE TITLE
Automatically switch icon pack based on dark mode

### ISSUE THREAD

**Issue by majutsushi** [8bitPit/Niagara-Issues#2054] opened 2022-09-12 03:28 UTC
### Is your feature request related to a problem?

Switching between light and dark mode necessarily changes the background colour. This is useful so that the display is readable during the day but not blindingly bright at night. However, not all icon packs work on both light and dark backgrounds. For example, when going for a minimalist, low-distraction look the LineX White/LineX Black icon packs work really well, but due to their simple colour scheme they only work on backgrounds that have roughly the opposite colour. This means that you could can only use the Black icon pack when dark mode is disabled (i.e. during the day) and vice versa. This is obviously not ideal, because whichever pack you choose is going to be essentially invisible half of the time.

The only icon packs that work with both light and dark backgrounds are ones that either have an ugly border or that are very colourful, which is much more distracting. Having the launcher automatically switch between the two icon packs based on whether dark mode is enabled would elegantly solve this issue.

### Describe the solution you'd like

Make it possible to specify two icon packs, one when dark mode is disabled and one when it is enabled. With the recent changes that remember custom icon assignments this hopefully shouldn't be too complicated to add. Ideally this would also change the wallpaper, but there already are other apps that can do that.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment] 2022-10-18 14:19
I think niagra has already given too much for free user. even not ad.

**Comment by Amorphous404** [comment] 2022-12-15 12:37
Duplicate of #1983

**Closed** 2022-12-15 12:38 UTC
Labels: duplicate

**Comment by majutsushi** [comment] 2022-12-29 03:23
I don't think the workarounds suggested in #1983 are a viable solution for this. They rely on either everyone having to manually modify their preferred icon pack and hoping that there is a way to modify the pack in a way that makes the icons recognizable without making them look ugly, or having to use a different icon pack that may look very different from the preferred one. I just did a quick search for dynamic "Material You" icon packs, and there are really only two popular ones, neither of which looks anywhere close to what I would want.

In addition the comment on the other ticket was written before the "Iconic update" that made it possible to switch icon packs including manually changed icons, so most of the technical objections no longer apply.

Please consider taking a look at this.
