### ISSUE TITLE
Change favorites based on time and/or location

### ISSUE THREAD

**Issue by noahevers97** [8bitPit/Niagara-Issues#2769] opened 2024-06-22 10:28 UTC
### Describe the solution you'd like

Hi!

To make everything much more productive, I would like to see a feature where the favorites menu changes based on your location and/or time/day/phone mode.

If I'm at work or if my phone is set to work mode, I don't want to be distracted by my other apps, but I would like to see the work-related apps, for example, Jira, Outlook, and some other apps. And if I'm at home, I would like to see other widgets/apps to control my Home Assistant.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2024-06-24 21:50
Thanks for suggesting this.

The request is a duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1517

Please head over to the issue and give it a thumbs up or add your thoughts so we can track the popularity of issues.

**Closed by TFackler** 2024-06-24 21:50 UTC
Labels: duplicate
