### ISSUE TITLE
Vibration on alphabet scroll

### ISSUE THREAD

**Issue by humza-a-khan** [8bitPit/Niagara-Issues#1147] opened 2020-01-19 20:08 UTC
Would it be possible to add an option to have vibration when scrolling through each letter of the alphabet? It would add some good haptic feedback.

On another note: I have a Note 10+ which has a great vibration motor. When swiping on an app to bring up extra options, Niagara uses its own vibration "pattern" which feels a bit cheap in comparison to the system vibration feedback. Would it be possible to add an option to use the system vibration throughout Niagara?

**Comment by Martin5001** [comment] 2020-01-20 17:25
I think having a slider to set the vibration intensity would solve this problem.

Also... #988 
I have used Niagara on two devices (Nokia 5 and Samsung Galaxy J7) and on both of them this vibration feedback was inconsistent – sometimes strong enough to be heard but not felt (which is good) but other times I wouldn't even notice it. I think it depends on the way I hold the phone and at which stage of the rotation the motor stopped and it sometimes gets blocked as the vibration (rotation) is not strong/long enough.

So due to this problem I would like the option to disable the vibration completely.

**Comment by 8bitPit** [comment] 2020-01-21 10:04
> I think having a slider to set the vibration intensity would solve this problem.

In my opinion a slider would be overkill for this use case.
Android 10 tries to tackle this issue by defining vibration patterns that have to be implemented (and individualized) by device manufacturers: https://developer.android.com/reference/android/os/VibrationEffect
I noticed I only use the new method for Niagara Pro's purchase button, not for the app swipe menu, I'll write it down on my todo-list ^^.

**Comment by disacrol** [comment] 2020-01-22 22:56
But, also the haptic feedback for when scrolling through the alphabet? I disable vibration myself, but I admit it would feel great for people who don't.

**Comment by 8bitPit** [comment] 2020-01-23 21:28
@disacrol yes this could be cool, forgot about the initial request. However, this has already been requested: https://github.com/8bitPit/Niagara-Issues/issues/969

**Comment by 8bitPit** [comment] 2020-01-23 21:28
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/969

**Closed by 8bitPit** 2020-01-23 21:28 UTC
