### ISSUE TITLE
App used time. 

### ISSUE THREAD

**Issue by NripPrajapat** [8bitPit/Niagara-Issues#2721] opened 2024-06-02 12:50 UTC
### Is your feature request related to a problem?

No. 

### Describe the solution you'd like

For the digital wellbeing improvement,
I like to suggest a feature, for the Home screen or maybe app list,
Next to the name of app add a place where it exactly tells the user, for long in the day, he/she used that particular app.

I'll provide an illustration.
1. A being the app icon.
2. B being the app name.
3. C being the app timer.

Senerios
1. A - C (for minimalistic users, ones who they don't use app names.)
2. A - B - C. (For the other ones.) 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-09-23 07:24
Hey there, thanks for the request.
I'll close this as a duplicate of #1811. Please take a look at that ticket for answers and updates.

**Closed by NiagaraSupport** 2024-09-23 07:24 UTC
