### ISSUE TITLE
Add chinese-name app sort support

### ISSUE THREAD

**Issue by Drohe** [8bitPit/Niagara-Issues#617] opened 2018-11-27 14:00 UTC
Hi there!
Could you add Chinese  app support in name sort  maybe with "pingying"!

**Comment by 8bitPit** [comment] 2018-11-27 22:13
Duplicate of #234

**Closed by 8bitPit** 2018-11-27 22:13 UTC
Labels: duplicate

**Comment by Drohe** [comment] 2018-11-28 00:15
😁
forgive my poor language skill

**Comment by 8bitPit** [comment] 2018-11-30 21:52
No problem, I'm a non-native English speaker as well :)
