### ISSUE TITLE
Ghost icon when scrolling immediately after closing favorite app

### ISSUE THREAD

**Issue by evanc577** [8bitPit/Niagara-Issues#1575] opened 2021-04-20 04:02 UTC
**Describe the bug**
Scrolling immediately after closing a favorite app and returning to the launcher sometimes causes ghost icons of the recently closed app to appear.

The ghost icon does not scroll or disappear until a new app is opened. It also obscures other app icons. Tapping the ghost icon does nothing. Sometimes, the ghost icon will remain, while the actual app's icon disappears.

It seems like it is related to the wiggle animation that the icon does when returning to the launcher. The issues only seems to occur if you manage to scroll while the animation is still playing.

**To Reproduce:**
1. Open a favorite app
2. Close the app
3. Immediately try to scroll
4. Ghost icon appears

**Smartphone:**
 - Device: Google Pixel 4a
 - Android version: 11

**Screenshots**

https://user-images.githubusercontent.com/14303970/115335642-95b26080-a16b-11eb-9db3-f4c5f2036095.mp4

**Comment by Maxr1998** [comment] 2021-04-20 17:08
That's a known issue unfortunately, and seems to be a bug in the Android system that's caused by the launcher's implementation of the new app closing animation. We used the implementation from Launcher3 (the base for Pixel Launcher) as a reference, however the bug doesn't occur there.
We'll hopefully be able to fix it in the future.

Also, Dami bias, I see.. :eyes:
The new Japanese single is amazing, *Don't light my fire* is my favorite Japanese track by them now.

**Comment by Maxr1998** [comment] 2021-07-29 11:51
Update: this bug also happens with other launchers e.g. Nova Launcher, and can be reproduced reliably with the HelpScout app. We reported the issue to Google and are waiting for them to fix it now.
https://issuetracker.google.com/issues/194427611

**Comment by 8bitPit** [comment] 2021-07-30 15:50
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1575

**Closed by 8bitPit** 2021-07-30 15:50 UTC
Labels: bug
