### ISSUE TITLE
Hard to reach top of alphabet. 

### ISSUE THREAD

**Issue by shinogirl** [8bitPit/Niagara-Issues#2604] opened 2024-02-23 15:08 UTC
### Is your feature request related to a problem?

Its hard to reach the top of the alphabet on a big phone or device. You may risk dropping it when attempting with one hand. 

### Describe the solution you'd like

So i want the ability to move the height/ adjust  how compact the alphabet is, as with a big phone its a little risky and irritating to try to reach the top with one hand. I believe this is considered customization and therefore will be rejected? I think its a very useful feature, and I'm actually surprised no one else has asked for this yet. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment] 2024-02-28 10:14
Hey there, thank you for your request.
This seems to be a duplicate of #334. It's unlikely to be changed soon, but I'll tell the others this is a currently often-requested feature.

**Closed by NiagaraSupport** 2024-02-28 10:14 UTC
