### ISSUE TITLE
Pie Navigation Gesture ( e.g., slide right to open previous app , slide up home button to open recent apps) are not available/working

### ISSUE THREAD

**Issue by joy-debnath-bge** [8bitPit/Niagara-Issues#901] opened 2019-06-06 05:46 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by Rod911** [comment] 2019-06-06 05:52
Duplicate of #86

**Closed** 2019-06-06 05:53 UTC
Labels: duplicate
