### ISSUE TITLE
Scrolling up gets you back to favorites/main screen 

### ISSUE THREAD

**Issue by ascended1** [8bitPit/Niagara-Issues#1064] opened 2019-11-26 23:57 UTC
I'd love to se an option that enables you to get back to your favourites when you scroll up to the top from the alphabet list. 

I know that you can use the side bar for that, but sometimes I just like to scroll via the list. 
Here's a screen record if it makes more sense. 
https://streamable.com/3xssb

**Comment by 8bitPit** [comment] 2019-11-29 18:55
Thanks for the request. The swipe gesture is being discussed here: https://github.com/8bitPit/Niagara-Issues/issues/122

**Comment by 8bitPit** [comment] 2019-11-29 18:55
Duplicate of #122

**Closed by 8bitPit** 2019-11-29 18:55 UTC
Labels: duplicate
