### ISSUE TITLE
Request to add a second screen for widgets

### ISSUE THREAD

**Issue by PickleHik3** [8bitPit/Niagara-Issues#2257] opened 2023-04-23 00:39 UTC
### Is your feature request related to a problem?

I would love to have a second screen to swipe to for widgets. 
Similar to the "flow launcher", where second screen could have builtin widgets + options to add our own. 

This is a really useful feature for me as it would help me put up calender and email widgets for easy access to them when needed. 

Cheers!

### Describe the solution you'd like

Your support to consider adding a second screen for widgets. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Lorestan00** [comment] 2023-04-23 03:01
This would be helpful. A separate screen for widgets. Stackable widgets are great but often you do want to just see widgets immediately and there is only so much space on the standard home screen

**Comment by Amorphous404** [comment] 2023-04-23 09:27
Hi @PickleHik3, Sorry, we decided against adding a dedicated widget page in Niagara. Please refer to this comment:
https://github.com/8bitPit/Niagara-Issues/issues/117#issuecomment-464157151

**Tip:** With [v1.9](https://github.com/8bitPit/Niagara-Issues/releases), you can create widget stacks (group 4 widgets together)
• [Adding Multiple)Widgets](https://help.niagaralauncher.app/article/41-adding-multiple-widgets)

E.g., You can assign a pop-up folder to the Niagara button action -> And create a stack widget to combine your calendar and email widgets.

Duplicate of #1059

**Closed** 2023-04-23 09:27 UTC
