### ISSUE TITLE
Subfolders/sub popups up to 1 additional depth

### ISSUE THREAD

**Issue by JonyWater** [8bitPit/Niagara-Issues#1925] opened 2022-04-14 14:08 UTC
### Is your feature request related to a problem?

One immediate problem is that when I add apps to a folder
I cannot get to the app's shortcuts popup within that folder
I have to find the individual app in the list and open its shortcut menu

Of course , there are more use cases for a general subfolder to be available
Grouping sub categories into one category folder

### Describe the solution you'd like

Folder
 <ul> 
<li>App
    <ul>
      <li>Notifications<li/>
      <li>Shortcuts<li/>
    </ul><li/>
<li>Sub-folder
     <ul>
      App
        <ul>
      <li>Notifications<li/>
      <li>Shortcuts<li/>
    </ul><li/>
</ul>
To keep things simple, the best solution is probably without sub-sub-folders (subfolders of a subfolder)

I hope you would like my feature and consider adding it to your lovely launcher :)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment] 2022-04-14 20:08
This could be considered a duplicate of #1869 and any requests to reopen it should be mentioned there - the devs intentionally kept the launcher to a single hierarchy to reduce complexity for the user as well as the developers - but I'll add to it a slightly different suggestion from a user that might be a less arbitrary way to limit the depth to 2 levels. 

The idea is to make it so you can open an app pop-up from inside the folder, but this 2nd level pop-up only contains the app's notifications & original shortcuts, excluding any other pinned content the original app's pop-up might have.

## Visualization

App's original pop-up:
- pinned widget
- its notifications
- pinned apps
- its shortcuts
- pinned shortcuts

Folder pop-up: 
- pinned widget
- pinned apps
- pinned shortcuts

App's pop-up opened from folder:
- its notifications
- its shortcuts

## Pros
- this could utilize the same swipe right gesture to expand apps in a pop-up as in the app list (more symmetrical than the arrow)
- less need to manually add shortcuts anywhere

## Issues
- requires having different versions of an app's pop-up
- might be confusing when a user can swipe right to expand a pop-up or clear notification instead, which is more consistent with the pop-ups work
- there's likely to be more requests after to add those missing elements to the 2nd level pop-up anyway, bringing back the problem of pop-up ception
- may be too time consuming & complex depending on current structure

**Comment by JanJenicek** [comment] 2022-05-19 13:27
Hi there,

I see the point of overcomplexity for some users. 

At the same time I have some use cases for such feature. Especially in favorites. Where each entry is premium space.
Currently heaving Messaging folder with SMS app, Email clients, Telegram, WhatsApp, etc. (currently 7 apps could be more easily) for some I would really appreciate to have additional popup. 

Example might be Outlook for Android app. I want to keep all my notifications under one icon, they don't have to be at same level with the icon itself. Also I want to have list of shortcuts to various email inboxes within the app. Everything flat in single folder "Messaging" leads to excessively long list.

I tried to use Island and Parallels for affected apps, but it does not lead to desired function. In addition I miss on single calendar storage... and there are more problems with this solution in general.

It would be really cool to have this feature as beta, activated via /{cmd}, if effort to make it would be reasonable. My approach would be little bit different from proposed.

My take on your questions:

- Bottom popup can be closed as I don't see it necessary or desired to return to it, except when no content is present in new popup, then ignore the action all together. Popups of apps without content would be configured via long press only.
- Propagated down, folder would show app as is in all-apps including its popup when triggered.
  - Downside: notification on same level with the app would be gone or would require different trigger action.
- I would keep same popup for app no matter from where it is opened.
   - Downside: it may lead to recursion. But as there is only one active popup at the time, it should not cause issues.

<br/><br/>
<hr/>
I'm using Niagara for 3 days and loving it regardless of this feature. ;-)

**Comment by TFackler** [comment] 2022-06-03 16:51
We are glad you are enjoying Niagara so far :) Thank you for taking the time to answer in detail.

Sadly we still think this feature would add too much complexity compared to the small reward it brings to the majority of our users. 

If you want to read more about our design principles, please head over [here](https://help.niagaralauncher.app/article/8-niagaras-design-principles).

**Closed** 2022-06-03 19:08 UTC
Labels: awaiting-response, wontfix

**Comment by 8bitPit** [comment] 2022-06-04 06:07
This ticket was closed for the wrong reason,  please ignore the github-actions bot's message and refer to TFackler's reply instead.

**Comment by texastoland** [comment] 2022-11-27 04:59
I want to add my +1 beyond an emoji reaction 👍🏼

My use case is the same as the OP. I have several messaging apps I'd like to use the inline reply feature with. I originally added secondary messaging apps as shortcuts in my primary app's popup. I just switched to folders and miss access to quick actions in general.

I agree that nested popups generally smell of bad UX. 1 alternative idea would be to treat folders like when you press and hold a letter on the home screen. The UI is replaced by only the shortcuts relevant to that letter. The only difference with folders would be the possibility of a widget too.

**Comment by 8bitPit** [comment] 2023-01-04 11:46
Thanks for sharing your use case and ideas, @texastoland; valid points. Would adding your favorite shortcuts from your apps inside the pop-up (i.e. your messaging apps) to the popup also work, or would those be too many shortcuts? Currently, adding shortcuts to a popup is tucked away deep in our settings (we plan to improve the workflow): long-press an app with a pop-up > Advanced > Edit [app name] pop-up > scroll all the way down to the shortcuts section and tap "More shortcuts" > select the shortcut you'd like to add.

**Comment by texastoland** [comment] 2023-01-04 13:44
I'm aware of shortcuts. It wouldn't help for a few reasons:

1. It's quick replies in response to notifications that I miss the most.
2. The advantage of shortcuts is discoverability. I never press and hold icons in other skins. But I swipe in Niagara all the time. I wouldn't know which ones to add.
3. I currently have 14 apps in a communication folder, 13 in travel, 13 in tools, etc. Even if they averaged out to only 1 or 2 shortcuts per app that'd make an unbearably long list.

**Comment by 8bitPit** [comment] 2023-01-18 11:16
Thanks for the additional input, @texastoland.

> 1. It's quick replies in response to notifications that I miss the most.

Quick replies should be supported; a reply button or text box shows up if you expand the notification.

> 2. The advantage of shortcuts is discoverability. I never press and hold icons in other skins. But I swipe in Niagara all the time. I wouldn't know which ones to add.

Good point.

> 3. I currently have 14 apps in a communication folder, 13 in travel, 13 in tools, etc. Even if they averaged out to only 1 or 2 shortcuts per app that'd make an unbearably long list.

Oh, you must be using a lot of apps 😅 I believe this is the main driver of why Niagara Launcher's pop-ups are so-so for you. Placing your most used apps directly in your favorites would also be insufficient because you have too many apps you're often using, right? Would be interesting to analyze how many different apps most users use every day.

**Comment by texastoland** [comment] 2023-01-19 00:46
> Quick replies should be supported; a reply button or text box shows up if you expand the notification.

Wow I didn't notice before 🙌🏼

> Oh, you must be using a lot of apps

Yeah I travel full-time so I depend heavily on my apps.

> Placing your most used apps directly in your favorites would also be insufficient because you have too many apps you're often using, right?

Exactly. I'm currently trying to reduce the folders in favorites because even that's cluttered.

> Would be interesting to analyze how many different apps most users use every day.

That sounds compelling to find out if my usage case is an outlier.

> I believe this is the main driver of why Niagara Launcher's pop-ups are so-so for you.

This made me reflect on my XY problem.

I love using Niagra. I love the alphabet "dial". But I often use similar apps together and it's difficult to even remember their names.

I like the folders but they do clutter Niagra's minimal vibe a little. In my ideal world (not necesarilly aligned with your design goals) I'd like to be able to group by folders (or category etc.) instead of alphabet. I previously used [Smart Launcher](https://play.google.com/store/apps/details?id=ginlemon.flowerfree&hl=en&gl=US) which organizes their drawer accordingly.

![](https://play-lh.googleusercontent.com/kEfw6GOD4tw2vYBvUcmE6KJZqkFkOXJq2KlYLLJy1jIvyueVk4J-nahB2dYZrOjcUGM=w5120-h2880-rw)

PS thanks for your replies!

**Comment by Lorestan00** [comment] 2023-04-14 21:33
My point around apps in folders is really about consistency. The moment you remove them fro your homescreen you lose the ability to use that apps shortcuts.

The average user has around 80 apps and I would imagine power users have many many more so are likely to want to use folders to organise apps but then risk losing baked in functionality
