### ISSUE TITLE
Clock on Samsung

### ISSUE THREAD

**Issue by asherperlmuter** [8bitPit/Niagara-Issues#729] opened 2019-01-29 19:07 UTC
When I click on the time on my homescreen, it takes me to alarms only, and not the full clock app

Note9 Android 8.1
Niagra 0.7.3

**Comment by 8bitPit** [comment] 2019-01-31 18:44
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/429

**Closed** 2019-02-24 12:32 UTC
Labels: duplicate
