### ISSUE TITLE
Allow removal of icons

### ISSUE THREAD

**Issue by dedsec594** [8bitPit/Niagara-Issues#2217] opened 2023-03-02 16:05 UTC
An addition to the icons feature for selecting no icons. So you would have default, icon pack, Niagara dots, or no icons.

**Comment by Amorphous404** [comment] 2023-03-02 16:39
Please use the Github search feature, before creating a issue.

See: https://github.com/8bitPit/Niagara-Issues/issues/140#issuecomment-753679560

Duplicate of #140

**Closed** 2023-03-02 16:39 UTC
