### ISSUE TITLE
A glitch when swiping up on homescreen.

### ISSUE THREAD

**Issue by CJTS15** [8bitPit/Niagara-Issues#2609] opened 2024-02-29 09:47 UTC
### Describe the bug

There is a glitch on the homescreen when accessing or doing swiping up gesture. I am using Pixel 6A with Niagara Launcher Pro latest version.

### Steps to reproduce

1. When in homescreen.
2. Then do swipe up gesture to access recent app.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Pixel 6A

### Android version

Android 14

### Screenshots / Screen recordings

![IMG_20240229_174717_015](https://github.com/8bitPit/Niagara-Issues/assets/15966569/69d00d9d-606f-4702-9ecd-ac38b5396f9f)

**Comment by NiagaraSupport** [comment] 2024-02-29 11:59
Hey there, thanks for the report.
Thanks for the report. I'll go ahead and close this as a duplicate of #2571. Please check out the response there as well.

**Closed by NiagaraSupport** 2024-02-29 11:59 UTC
Labels: bug
