### ISSUE TITLE
Folders Within Folders 

### ISSUE THREAD

**Issue by Abel2Disable** [8bitPit/Niagara-Issues#2087] opened 2022-10-14 11:55 UTC
### Is your feature request related to a problem?

I don't like scrolling to the bottom of the app list to access my folders. I'd be to have them more easily accessible without having to clutter my home screen. 

### Describe the solution you'd like

Provide users the option to add a folder to Niagara Button and add multiple folders inside that folder. That could allow for the Niagara Button to be a quick and easy shortcut to all user-created-folders that aren't wanted on the main home screen list.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment] 2022-10-14 15:28
i dont think niagra will agree on this

**Comment by TimEvWw** [comment] 2022-10-23 18:51
Seconded. It would clear up my home screen and still having everything at my finger tips. I've seen people hide every application so only the folders are available in the alphabet

**Comment by Amorphous404** [comment] 2022-12-11 11:24
https://github.com/8bitPit/Niagara-Issues/issues/1925#issuecomment-1146172198

The ticket is accidentally closed, you can still add your feedback/suggestions in that thread :)

Duplicate of #1925

**Closed** 2022-12-14 18:59 UTC

**Comment by Amorphous404** [comment] 2023-07-16 13:59
>I don't like scrolling to the bottom of the app list to access my folders. I'd be to have them more easily accessible without having to clutter my home screen.

You don't have to scroll through the app list to access the pop-up folder; you can directly land on the folder section by tapping the diamond shape (🔹) icon in the alphabet scroller.
https://github.com/8bitPit/Niagara-Issues/issues/2253#issuecomment-1518277684

>Provide users the option to add a folder to Niagara Button and add multiple folders inside that folder. That could allow for the Niagara Button to be a quick and easy shortcut to all user-created-folders that aren't wanted on the main home screen list.

Please refer to #1925. The ticket is accidentally closed. However, you can still leave your suggestions in that thread :)

- Duplicate of #1925
