### ISSUE TITLE
Allow Resizing of App Icon Without Effecting The List Size

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1957] opened 2022-05-09 14:06 UTC
### Is your feature request related to a problem?

Yes, Changing Icon Size Effects The List Size In Niagara

### Describe the solution you'd like

I have some very great icon packs, which i prefer using them with small size, I'm able to do that on other launchers, but I'm not able to achieve the same in Niagara without effecting the list size,

![Screenshot_20220509-192936_Niagara Launcher](https://user-images.githubusercontent.com/96917972/167427695-a41b0bc0-2de7-4e9f-b3d1-6feaf8f7bea3.png)
---------------------------------------------------------------------------------------------------
![Screenshot_20220509-192945_Niagara Launcher](https://user-images.githubusercontent.com/96917972/167427706-9169f960-cdee-4d9c-b567-8403a8ed82e3.png)

Please make it possible to do this in Niagara.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment] 2022-05-12 18:08
This seems like a duplicate of issue #1282 from 2020 and the original feature planned in [#304](https://github.com/8bitPit/Niagara-Issues/issues/304) in 2018, not sure if devs decided against it or just haven't gotten around to it yet. 

It requires separating setting icons into more configuration options so it seems unlikely 😬 . However you can currently achieve this with Icon Pack Studio (setting your preferred icon size for the list height in Niagara and resizing the icons in Icon Pack Studio), but you'll have to export the IPS icons again whenever you install more apps

You might want to reopen one of the existing issues for it, to reduce duplicates.

**Closed by Oddward** 2022-05-12 18:08 UTC

**Comment by topsy-turvy99** [comment] 2022-05-12 18:34
> This seems like a duplicate of issue #1282 from 2020 and the original feature planned in [#304](https://github.com/8bitPit/Niagara-Issues/issues/304) in 2018, not sure if devs decided against it or just haven't gotten around to it yet. 
> 
> It requires separating setting icons into more configuration options so it seems unlikely 😬 . However you can currently achieve this with Icon Pack Studio (setting your preferred icon size for the list height in Niagara and resizing the icons in Icon Pack Studio), but you'll have to export the IPS icons again whenever you install more apps
> 
> You might want to reopen one of the existing issues for it, to reduce duplicates.

Do i have to comment the same with reference in a new issue?

**Comment by Oddward** [comment] 2022-05-12 19:08
@topsy-turvy99 no, just add a new comment in that old issue to request to reopen it, opening a new issue is just adding more duplicates 😅

**Comment by topsy-turvy99** [comment] 2022-05-12 19:12
Lol, okay i already did that, closing it then 😅
