### ISSUE TITLE
Blinking display with gesture navigation in android Q 

### ISSUE THREAD

**Issue by moviti** [8bitPit/Niagara-Issues#947] opened 2019-07-31 15:37 UTC
**Describe the bug**

**To Reproduce**
1. activate full gesture navigation in androidQ
2. running any app in front
3. swipe the pill up. it represents "back to home"
4. displays "Niagara home", "last app ","home" quickly, like blink

5. Sometime Niagara force changes navigation setting to 3 button nav from Full gesture.

**Smartphone (please complete the following information):**
 - Device: Pixel3
 - Android version: Android Q DP5

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment] 2019-08-02 20:09
Sorry, but that issue is caused by Android Q, but gesture navigation on third party launchers won't be supported on Android Q anyways:
>Custom launchers are another area where we’ve heard feedback and we’re continuing to work on issues, particularly with stability and Recents. Starting in Beta 6, we’ll switch users to 3-button navigation when they are using a custom launcher by default. We’ll address the remaining issues in a post-launch update allowing all users to switch to gestural navigation. 

Source: https://android-developers.googleblog.com/2019/07/android-q-beta-5-update.html

**Closed by 8bitPit** 2019-08-02 20:09 UTC
Labels: bug
