### ISSUE TITLE
Swipe to Screen Off

### ISSUE THREAD

**Issue by ihrubab** [8bitPit/Niagara-Issues#1197] opened 2020-02-26 11:11 UTC
I know the pro version has swipe to show folders. But is it possible to add Actions to Swipe where we can choose Actions like "Screen Off", "Vibrate or Silent"

**Comment by 8bitPit** [comment] 2020-02-26 12:38
Hi @ihrubab, turning of the screen might work by a double tap gesture in the future: #63 For a more general discussion about gestures, you can also visit #2 Hope this helps

**Comment by 8bitPit** [comment] 2020-02-26 12:38
Duplicate of #63

**Closed by 8bitPit** 2020-02-26 12:38 UTC
