### ISSUE TITLE
 Problem with icon color change to follow wallpaper color

### ISSUE THREAD

**Issue by Ralendil** [8bitPit/Niagara-Issues#1953] opened 2022-05-05 20:01 UTC
### Describe the bug

Niagara is known to have a feature that permits dynamic icons, like the pack Pix Material You Light/Dark, to adjust dynamically to night / day mode or to the wallpaper color.
From my experience, this works perfectly when the switch between night and day mode is happenning. However, regarding the icon color change, it works, but not always. I would estimate that it works 4 times / 5 (ie 80%). From my experience, I would say that niagara refresh too fast the color and that pix material has not yet refreshed the color than niagara has updated it.

Can you fix this ?

Additional informations:
1. Phone is rooted
2. I use repainter  (but the bug can happen without using it, tested before submitting the ticket)

### Steps to reproduce

1. Install Pix Material You Light/Dark
2. Change your wallpaper multiples times

### Device name

Google Pixel 6 Pro

### Android version

Android 12

**Comment by Oddward** [comment] 2022-05-05 23:06
Hey, thanks for the thorough post. I believe this is a WIP waiting on API updates from Android 13 according to Peter's comment in this similar issue #1800 , otherwise, the devs will look into it

**Comment by Ralendil** [comment] 2022-05-05 23:13
What says Paul Omalley already happens. Niagara force the icons to refresh and it works 80% of the times. However, niagara is so fast, that sometimes it refresh them before Pix Material light / dark had time to adapt the color of them.
Maybe I am wrong, but, for the pix material app, it would only need that the niagara refresh happens just 1 second later...

I post this message in the other ticket.

**Comment by timm0e** [comment] 2022-05-10 06:09
Thanks for your bug report!

We will be looking into reproducing the error by ourselves and hope to provide a fix for this in the future!

**Comment by topsy-turvy99** [comment] 2022-05-11 10:23
> Thanks for your bug report!
> 
> We will be looking into reproducing the error by ourselves and hope to provide a fix for this in the future!

Yes, i can confirm this on my LineageOS A12.1 where the Icon Color refreshes Only For the 1st & 2nd Unlock, then it stops refreshing, then i have to restart/or reselect the icon pack to refresh them,

Day/night works flawlessly

One more suggestion, can it be optimised to refresh the icon more faster, like first it can refresh the colors from favorites icon, then it can go for refreshing the app list icon, to make it look more consistent? 😇

**Comment by UrsKR** [comment] 2023-10-09 06:13
In saw a very similar issue today, where all icon colors where refreshed except for the icons where I custom assigned an icon since Pix MY L/D did not have a fitting one.

**Comment by 8bitPit** [comment] 2023-11-20 19:08
Thank you very much for reporting, everyone! We fixed a bug in v1.10 (currently in [open beta](https://github.com/8bitPit/Niagara-Issues/releases)) that could prevent icons from refreshing after a color change. I hope that was the culprit; please let us know if you ever run into this issue again.

**Closed** 2023-12-11 10:18 UTC
Labels: bug, good issue, in progress / implemented
