### ISSUE TITLE
A notification category

### ISSUE THREAD

**Issue by Vai-Raj** [8bitPit/Niagara-Issues#762] opened 2019-02-16 10:17 UTC
The launcher should have a new category between the (*) and the (#) category specially dedicated to the apps that have received notification i.e. all the apps that have received a notification will appear there.

**Comment by 8bitPit** [comment] 2019-02-18 09:55
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/9

**Closed by 8bitPit** 2019-02-18 09:55 UTC
