### ISSUE TITLE
Swipe Google pill for Google-Feed

### ISSUE THREAD

**Issue by Chillibo** [8bitPit/Niagara-Issues#182] opened 2018-09-11 17:16 UTC
Hey. I really like your launcher,
I'm asking myself if there is a chance to get the function to swipe the Google pill e.g. To left, to get the Google feed? I really would love it. I'm missing this feature from pixel launch er, but I wanna stick with yours ✌🏼

**Comment by Chillibo** [comment] 2018-09-11 17:18
Damn, sorry for wrong section

**Comment by Shinra04** [comment] 2018-09-13 05:33
Enable G icon from settings. Tapping the icon brings the news feed. If you want the news feed to be mapped to the pill then... get over it.

**Comment by 8bitPit** [comment] 2019-04-16 19:53
Duplicate of #3

**Closed by 8bitPit** 2019-04-16 19:53 UTC
Labels: duplicate
