### ISSUE TITLE
Access all apps with scrolling 

### ISSUE THREAD

**Issue by MirrorsMind** [8bitPit/Niagara-Issues#1138] opened 2020-01-14 13:35 UTC
I'd like to access all of my apps (not only favourites with scrolling down)

So my idea would be, after scrolling to the end of my added favourites, to add the accessibility to scroll even further down to the apps beginning with A. So it's like tapping on A on the grid but for me personally it would be an even smoother user experience. I hope I explained it well enough. 

Another thing would be, after scrolling up, that the search function, which appears normally with pressing the home button in my case, is useable. 

Other then that, I really like your launcher and love the simplicity. Keep it up!

**Comment by Martin5001** [comment] 2020-01-14 14:06
I think in case of implementation users should have the option to choose between this and the current scrolling.

**Comment by MirrorsMind** [comment] 2020-01-14 14:32
Yeah, I support that option fully.

**Comment by 8bitPit** [comment] 2020-01-15 14:34
@MirrorsMind thank you for your request and your kind words. Implementing a swipe up gesture is under discussion: https://github.com/8bitPit/Niagara-Issues/issues/122

**Comment by 8bitPit** [comment] 2020-01-15 14:35
Duplicate of #122

**Closed by 8bitPit** 2020-01-15 14:35 UTC

**Comment by MirrorsMind** [comment] 2020-01-15 15:43
Oh thanks, didn't know it was already suggested, sorry about my mistake.

**Comment by 8bitPit** [comment] 2020-01-15 17:05
No problem at all!
