### ISSUE TITLE
Ability to keep Home screen notifactions but disable the player.

### ISSUE THREAD

**Issue by Zyrin36** [8bitPit/Niagara-Issues#1033] opened 2019-10-24 22:51 UTC
Its frustrating when the home screen gets crowded because the is on.

Same as the tittle the ability to choose in the settings if a person wants the onscreen player to be on or off.

**Comment by 8bitPit** [comment] 2019-10-26 14:51
Hey @Zyrin36 , I believe this is a duplicate of https://github.com/8bitPit/Niagara-Issues/issues/111

**Closed by 8bitPit** 2019-10-26 14:51 UTC
Labels: duplicate
