### ISSUE TITLE
Padding between widget and icons

### ISSUE THREAD

**Issue by niikkhhil** [8bitPit/Niagara-Issues#3043] opened 2024-12-04 17:33 UTC
### Is your feature request related to a problem?

It will be really nice to give an option to add padding between the niagara widget and the icons in the home screen, it'll look much cleaner. 
hopefully the devs will consider this suggestion..

### Describe the solution you'd like

give an option to add padding between the widget and the icons.
![Uploading IMG_20241204_230323.jpg…]()

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment] 2024-12-09 11:56
Please see commonly requested customization options:

❌ Adding Customizable Padding / Empty Space Below the Niagara Widget
While we don't plan to offer this option, you can add an invisible third-party widget to serve as a spacer between the Niagara widget and your favorites. Many apps offer [invisible widgets on Google Play](https://play.google.com/store/search?q=invisible%20widget&c=apps) (use at your own risk).

Duplicate of #2626

**Closed by TFackler** 2024-12-09 11:56 UTC
