### ISSUE TITLE
MIUI Theme font overriding launcher's built-in fonts

### ISSUE THREAD

**Issue by RigleyC** [8bitPit/Niagara-Issues#1923] opened 2022-04-13 15:15 UTC
### Describe the bug

When you apply a font from MIUI theme, the font on app list is override to another, just stay the selected font on some parts of the app, like in the clock.
As you can see in the screenshot, the font from clock and app names are different.
The problem doesn't occurs when the default font of the system is selected.

### Steps to reproduce

1. Go to font manager
2. Apply ant font you want
3. Change the app font to "Josefina sans"

### Device name

Redmi Note 10 Pro

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_2022-04-13-12-08-06-714_bitpit launcher](https://user-images.githubusercontent.com/21021245/163213027-364c3f12-7647-410d-92a9-9270f67ed49e.jpg)

**Comment by RigleyC** [comment] 2022-04-14 23:45
Yes, still happen.
I think this is a problem from MIUI 12/13.
Some problems doesn't happen in this version.
1. Change the region to India ( so I can use fonts)
2. Apply any font ( I usually change to use iOS emojis)
3. After reboot the font that I use on Nigara (Josefin Sans) only apply to clock and settings, modals (I call modal things like the calendar hover, the card that goes up when you press a app for a long time), apps names, battery, date, everything is using a thin font, I believe it could be the font applied from MIUI,

**Comment by Oddward** [comment] 2022-04-15 17:30
Many apps seem to apply the system's default font in their UI, so if you change the system font they would reflect that change (e.g. in Niagara the default setting in the Look settings is *System* which here follows what I set for MIUI). If an app is using its own bundled custom fonts it's specified in its code, can't really be overridden afaik. It's possible that Niagara was accidentally applying the system font in the favourites for you at the time, but I can't reproduce it on 1.6.5.

Also, 1.6.5 only recently started slowly rolling out to Play store so the latest for you at the time might have been an older version, check in _Niagara settings > Advanced > under App info_

---
Changelog item from 1.6.4: 
- _Bugfix: Custom fonts are applied on all Niagara Launcher screens again_

**Comment by RigleyC** [comment] 2022-04-15 19:48
I believe with MIUI 11 this problem doesn't happen, that's why you can't reproduce, I have this problem since MIUI 12. Also, I'm using the 1.6.5 from Niagara Channel's.
When I saw the changelog about font there was a hope. 😅
Right now I'm using Josefin Sans as a custom font and is applied to all sections, favorites, Niagara Settings, Calendar etc. Don't know why this way works and when I select a font from the list (System, Work Sans or Josefin) it doesn't work.
For now, I'm good with this solution. 😄

**Comment by timm0e** [comment] 2022-05-10 15:15
This is probably intended by MIUI, since else they might not be able to override fonts of apps.

**Comment by 8bitPit** [comment] 2022-12-11 07:14
Good news; we could find a workaround for that issue. It's now fixed in v1.8.6: https://github.com/8bitPit/Niagara-Issues/releases. Thanks for reporting, @RigleyC.

**Closed by 8bitPit** 2022-12-11 07:14 UTC
Labels: bug
