### ISSUE TITLE
Apps in popup folder - inconsistent 

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2244] opened 2023-04-14 15:18 UTC
### Describe the bug

Not sure if this is bug but certainly inconsistent... On an app on the homescreen if you swipe it will show any predefined app shortcuts and a widget if one has been manually added in. When a app is in a popup folder however swiping on the app leads to.... Well nothing happening.. No app shortcuts and no ability to add widgets.

It would make sense for the functionality for an app on the homescreen to be replicated in an popup folder especially since you're losing basic functionality such as app shortcuts as well as nice to haves such as widgets. 

### Steps to reproduce

1. Swipe on app in popup folder and nothing happens 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Galaxy Fold 4

### Android version

Android 13

**Comment by Amorphous404** [comment] 2023-04-14 20:34
Hi @Lorestan00, The team has deliberately designed the launcher to have a single hierarchy in order to keep the launcher less complex; however, there's an ongoing discussion about the same; if you have any ideas or suggestions, please feel free to share them on the linked issue.

Duplicate of #1925

**Closed** 2023-04-14 20:34 UTC
Labels: bug
