### ISSUE TITLE
I am unable to swipe away notifications..

### ISSUE THREAD

**Issue by DJMistry02** [8bitPit/Niagara-Issues#888] opened 2019-05-22 21:37 UTC
I am unable to swipe away a notification from WhatsApp after I have replied to it from the notification bar notification or from the Niagara stylised notification thing.(the swipe right on app and tap to reply)
It is very annoying.
This specifically occurs in WhatsApp mainly because I don't use any other app for chatting.
U simply need to reply to a message that appears as a notification for this thing to happen.

Device: Moto one Power
Android pie

**Comment by 8bitPit** [comment] 2019-05-23 13:51
Duplicate of #766

**Comment by 8bitPit** [comment] 2019-05-23 13:53
Thanks for the report. Does it happen every time after replying in WhatsApp?

**Comment by DJMistry02** [comment] 2019-05-23 13:55
Yes it does happen every time.

**Comment by DJMistry02** [comment] 2019-05-24 01:50
Hey! 
A restart seems to have solved the problem. I will update u if it happens again.

**Closed** 2019-05-24 01:58 UTC
Labels: bug, duplicate

**Comment by 8bitPit** [comment] 2019-05-24 06:55
Thank you for the additional information @DJMistry02
