### ISSUE TITLE
Widget 

### ISSUE THREAD

**Issue by Abhishek9778** [8bitPit/Niagara-Issues#2309] opened 2023-06-17 16:25 UTC
### Is your feature request related to a problem?

I have been using niagra from a long time and I would really like if you add more in app widgets And widget customisation it will make niagra launcher my favourite of all plzzzz : sorry for bad eng

### Describe the solution you'd like

I have been using niagra from a long time and I would really like if you add more in app widgets And widget customisation it will make niagra launcher my favourite of all plzzzz : sorry for bad eng

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Abhishek9778** [comment] 2023-06-17 16:26
I have been using niagra from a long time and I would really like if you add more in app widgets And widget customisation it will make niagra launcher my favourite of all plzzzz : sorry for bad eng

**Comment by Amorphous404** [comment] 2023-06-17 17:45
Hi @Abhishek9778, Thanks for reaching out! It's already possible to add multiple widgets :), Please refer to this article:
- [Adding (Multiple) Widgets](https://help.niagaralauncher.app/article/41-adding-multiple-widgets)

**Comment by Amorphous404** [comment] 2023-06-17 17:59
- Duplicate of #117

**Closed** 2023-06-17 17:59 UTC
