### ISSUE TITLE
Mini Note Widget

### ISSUE THREAD

**Issue by loetters** [8bitPit/Niagara-Issues#2237] opened 2023-04-07 06:13 UTC
### Describe the solution you'd like

Hi,

I looking for a small widget that is reachable with 1 or 2 clicks for a quick note. There is no need for sync or anything just a quick way to make a small note 4 rows. Visible on the go without going into one note Evernote or whatever.

If there is already a way I'm happy to hear.

Regards Lukas 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-04-07 07:07
Hi @loetters, Your request appears similar to issue #1776. So I request you to follow the linked issue.

Duplicate of #1776

**Closed** 2023-04-07 07:07 UTC
