### ISSUE TITLE
Widget Screen

### ISSUE THREAD

**Issue by arunganesh36** [8bitPit/Niagara-Issues#595] opened 2018-11-21 20:33 UTC
I like the graphics in this app. I hope swipe right from the home screen is still empty. We can add the widget screen there, where we can put all the widgets in order. Sometimes, I miss my calendar and notepad widgets.

**Comment by 8bitPit** [comment] 2018-11-21 21:34
Duplicate of #59

**Closed by 8bitPit** 2018-11-21 21:34 UTC
Labels: duplicate
