### ISSUE TITLE
Change icon shape to other than circle

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#998] opened 2019-09-14 11:58 UTC
This is just a minor one but it would be nice to have option to choose from other standard icon shapes, such as rounded square, drop, etc., in addition to current circle option. (Icon packs can do this too, but it would be useful to use on icon packs which don't have this option built-in.)

**Comment by 8bitPit** [comment] 2019-09-15 19:37
I believe this is a duplicate of #448

**Comment by Martin5001** [comment] 2019-09-16 05:27
It is, sorry for that.

**Comment by 8bitPit** [comment] 2019-09-16 07:05
No problem 😁

**Closed by 8bitPit** 2019-09-16 07:05 UTC
Labels: duplicate
