### ISSUE TITLE
Music Player icon should disappear if widget is from the same app. 

### ISSUE THREAD

**Issue by sid32** [8bitPit/Niagara-Issues#1415] opened 2020-11-20 00:48 UTC
Don't need a music player widget and a music player icon on the home screen if they match.

**Comment by 8bitPit** [comment] 2020-11-20 07:40
Agreed, Niagara Launcher should already hide the media player as long as a widget of the same app is visible. I just checked that on the latest version and it works fine on my device. Any tips on how to reproduce this issue?

**Comment by Martin5001** [comment] 2020-11-20 12:50
Maybe he meant the built-in Niagara mini player, not 3rd party widget? As I understand it, he means that because there's the Niagara widget, he doesn't need to open the app itself to play/pause/skip so would like to hide the app icon after the Niagara player shows. Not sure if I'm correct @sid32?

**Comment by sid32** [comment] 2020-11-20 14:37
I mean when headphones are attached my music player icon appears. That is great. But then I start playing audio and the icon stays. So I have a podcast addict widget and a podcast addict icon. 

What I want is that if podcast addict widget is there, then no music icon. Close widget then icon comes back. 


![Screenshot_20201120-092155](https://user-images.githubusercontent.com/1593561/99811926-cb4b1300-2b13-11eb-8488-1e8dc401d52b.png)

**Comment by 8bitPit** [comment] 2020-12-07 09:19
Ah, I see; thanks for the clarification @sid32. I believe this issue is a duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1129; hiding the music app could be too confusing for the user.

**Closed by 8bitPit** 2020-12-07 09:19 UTC
Labels: question
