### ISSUE TITLE
App drawer scroll animation/smoothness?

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#198] opened 2018-09-12 20:46 UTC
Are there any plans on implementing any kind of smoothness when scrolling through the app drawer?

It's fast as it is, but I think it feels kında choppy just jumping from apps A-Z with instant page renewal, so to speak.

I hope you understand.

**Comment by Shinra04** [comment] 2018-09-13 05:15
Yeah, I had the same suggestion, but then I realised that when you're scrolling say, from top to bottom and if the apps were to have some 'give' and flow they would do so in the OPPOSITE direction to the scroll's. This would look even weirder and unsettling in my opinion.

**Comment by Shinra04** [comment] 2018-09-13 17:29
You didn't seem to catch my point. In a regular app drawer, you're swiping up and the apps flow up too, which feels intuitive. However, with the apps scroll, you're moving your finger downwards while the apps would have to move upwards. It just wouldn't go well together.

**Comment by 8bitPit** [comment] 2018-09-15 16:12
Which type of animation @Montell2099? Implementing an animation there, that's not bothering is tough.

**Comment by Montell2099** [comment] 2018-09-15 23:58
@Shinra04
I see what you mean, perhaps you're right and that wouldn't feel intuitive.

@8bitPit
Maybe not an animation, but something like displaying the other apps (not only the ones from the current selected letter) at a lower opacity. For example, when I'm hovering at "I" only Instagram shows up and a lot of screen real-estate is being wasted in my search of the desired app I'm scrolling for.

**Comment by Shinra04** [comment] 2018-09-16 07:32
Ohh, I like this idea of showing other apps at lower opacity in the back. It could allow for a gesture to launch the app in full opacity with something like a left swipe to the edge of screen.

**Comment by Montell2099** [comment] 2018-09-16 20:50
@8bitPit What would you think of [something like this](https://imgur.com/a/GSSIq8i)? I love the way you implemented the fade-out in the app-drawer & the new way to access the search bar. Looks very simplistic!

**Comment by 8bitPit** [comment] 2018-09-17 21:33
@Montell2099 for better orientation I would not show apps above the selected letter, like there: #26

**Comment by 8bitPit** [comment] 2019-04-16 20:59
Duplicate of #26

**Closed by 8bitPit** 2019-04-16 20:59 UTC
