### ISSUE TITLE
App Search - Spellcheck/fuzzy search

### ISSUE THREAD

**Issue by dgoncalves81** [8bitPit/Niagara-Issues#2224] opened 2023-03-20 17:33 UTC
### Is your feature request related to a problem?

When searching for an app a slight misspelling results it in not being displayed

Using a fuzzy search logic to preference closest match would result in a more searchable and quicker access to apps.

### Describe the solution you'd like

For example typing "Mapd" when you mean "Maps" should still offer Maps on the app search dialog - at the moment it does not.

Likewise mis-typing "Chrume" when the user meant "Chrome" should still offer the closest app/spelling match.. That being Chrome. 

This feature would work like the good search powered app launchers that already exist. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment] 2023-03-20 20:21
Hi @dgoncalves81, it appears that your request is similar to issue #411. Please follow the linked issue.

Duplicate of #411

**Closed** 2023-03-20 20:21 UTC
