### ISSUE TITLE
Issues with gesture navigation when notifications access is granted

### ISSUE THREAD

**Issue by TheKineticz** [8bitPit/Niagara-Issues#2659] opened 2024-04-16 01:42 UTC
### Describe the bug

When notifications access is granted to Niagara, the launcher will often hitch when closing apps and apps will not cleanly close into their icons, often either appearing from the lower-centre of the screen or skipping the animation entirely.

This is not unique to Niagara Launcher. I have found it occurs with Nova Launcher Prime as well when notifications access is granted for notification dots, so this is likely an issue with Android not Niagara, but it may be worth investigating a workaround.

### Steps to reproduce

1. Ensure gesture navigation is enabled
2. Grant Niagara Launcher notification access in android settings (Note: Notification-related features do not need to be enabled)
3. Open any app and return home

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Other 3rd-party launcher(s) tested

Nova Launcher

### Device name

Nothing Phone (2a)

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/50476983/a17c34f2-d1d5-4803-8150-c33ebbda9c54

**Comment by NiagaraSupport** [comment] 2024-04-24 13:01
Thanks for the report, and sorry to hear it's still causing issues. 
For simplicity's sake, I'll close this as a duplicate of #2636. I trust the `/togglecloseappanimation` command doesn't help here either?

**Closed by NiagaraSupport** 2024-04-24 13:01 UTC
Labels: bug
