### ISSUE TITLE
Problem with music widget

### ISSUE THREAD

**Issue by Ggnida** [8bitPit/Niagara-Issues#2716] opened 2024-05-31 08:13 UTC
### Describe the bug

Previously, I opened the music application through a widget, but now I don’t.

### Steps to reproduce

On video

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Realme gt neo 3t

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/171326301/979482eb-0b5d-48e7-a5a3-ecfc8f9e0cd9

**Comment by TFackler** [comment] 2024-06-06 15:34
Duplicate of #2713

**Closed** 2024-06-06 15:34 UTC
Labels: bug, duplicate
