### ISSUE TITLE
Change Colors of Dots Icons in favorites

### ISSUE THREAD

**Issue by LDM1973** [8bitPit/Niagara-Issues#2088] opened 2022-10-15 01:59 UTC
### Is your feature request related to a problem?

I want to change the colors of the Niagara dots icons individually for the folders on my home screen

### Describe the solution you'd like

Choose individual colors for each folder, for example: health related apps have a red dot and money related apps have a green dot.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment] 2022-10-16 06:14
good one.Few extra goodies can also be added to enhance this pro feature like
- round around dot
- when notification, enhance the color of dot or highlight it any way(bigger, star over dot). Why because dots are too small and we can not increase size without increasing padding between favorite icons
- Increasing app icon size to MAX make it look weird(when 2 or more app have active notification) due to huge padding, Please see it also. I have no suggestion in this

**Comment by notepadnine** [comment] 2022-11-02 16:47
@8bitPit  is @Oddward  on holiday. We see no activity

**Comment by topsy-turvy99** [comment] 2022-11-11 17:53
Duplicate of #1604

**Closed** 2022-12-12 12:29 UTC
Labels: duplicate
