### ISSUE TITLE
Launcher does not support reverse portrait orientation

### ISSUE THREAD

**Issue by ralismark** [8bitPit/Niagara-Issues#1051] opened 2019-11-07 22:28 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the launcher does work in reverse portrait (i.e. 180 degrees rotation). Instead, it automatically rotates to normal portrait (0 degrees rotation).

**Describe the solution you'd like**
The launcher should remain in reverse portrait if the phone is in that orientation. No UI changes should be necessary.

**Comment by 8bitPit** [comment] 2019-11-08 17:17
Hi @ralismark, I think your request is a duplicate of: #1027

**Comment by 8bitPit** [comment] 2019-11-08 17:18
Duplicate of #1027

**Closed by 8bitPit** 2019-11-08 17:18 UTC
Labels: duplicate
