### ISSUE TITLE
Jittery animation immediately after unlock on Galaxy Oneui 4.0

### ISSUE THREAD

**Issue by hexboxlabs** [8bitPit/Niagara-Issues#1973] opened 2022-06-04 14:42 UTC
The favourites slide down animation that happens while closing an app, happens while unlocking the phone. The animation creates 2 layers which slide over each other causing jittery motion. (Though it last only for a few milli seconds, it's taking away the seemless experience from the user)
I suggest to give an option to turn off in-app animations...

**Comment by Maxr1998** [comment] 2022-06-07 08:11
This was reported in #1804 already, thus I'm closing it as duplicate.

**Closed** 2022-06-07 08:11 UTC
Labels: duplicate

**Comment by NiphraDil** [comment] 2022-07-20 14:33
Both this and [#1804](https://github.com/8bitPit/Niagara-Issues/issues/1804) have been closed, but the issue is remaining, jittery animation (2 layers) after unlocking screen on OneUI 4.x. Is it possible to re-open the ticket, or should a new issue be opened?
