### ISSUE TITLE
Notification Summary disables itself 

### ISSUE THREAD

**Issue by trustosas** [8bitPit/Niagara-Issues#2699] opened 2024-05-21 14:52 UTC
### Describe the bug

I turn on notification summary and select the desired apps for the summary, but soon enough, it disables itself...

### Steps to reproduce

1. Turn on notification summary
2. Select the desired apps for the summary (but soon enough, it disables itself...)

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Vivo Y12s

### Android version

Android 11

**Comment by NiagaraSupport** [comment] 2024-05-22 14:40
Hey there, thanks for the report.
I'll close this as a duplicate of #2687. Be sure to check there for potential updates as well.

**Closed** 2024-05-22 14:53 UTC
Labels: bug, duplicate
