### ISSUE TITLE
Smart app suggestions

### ISSUE THREAD

**Issue by VincentJoshuaET** [8bitPit/Niagara-Issues#203] opened 2018-09-13 17:48 UTC
The Pixel Launcher (from Google, not the other AOSP-built ones that try to emulate it) has an app suggestions feature that selects apps based on the time of the day and the user's regular activity, not just based on how many times the user clicked the app icon.

Can we have something like that on the homescreen? So on the setup wizard, we will have the options to choose what apps to show on the desktop, or, let the launcher do it automatically. The app list should also change regularly and intelligently.

P.S. Google Feed on swipe left is nice as well

_Sent from my Redmi Note 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 8bitPit** [comment] 2018-09-14 12:30
Thanks for the request. To my mind a time best app recommendation system would be too dynamic, it would constantly change your favorite page.

**Comment by VincentJoshuaET** [comment] 2018-09-14 12:36
> it would constantly change your favorite page

That's how the Pixel Launcher app suggestions behave, and I actually want that.

**Comment by keep-flying** [comment] 2018-09-15 20:47
Completely agree, the suggested apps list is pretty much bang on the money 9 times out of 10 the app I want is shown.

**Comment by cauerego** [comment] 2018-10-06 13:18
agreed in retrospect #27 ! :)

however, if Google doesn't offer a simple way to use their implementation, i can see how this should be left for much later, when big G will notice this, buy it and make 8bitpit work there...

or simply when they release their code/API for that! :D

because it is indeed a very difficult thing to implement.

meanwhile, dev could play with it in the auto suggested apps. why not? it should be interesting. perhaps rootless launcher actually have done it already? https://www.androidpolice.com/2018/08/26/rootless-pixel-launcher-non-google-devices-hits-play-store-rootless-launcher/

as for the g feed, Vincent, try #3.

**Comment by 8bitPit** [comment] 2018-10-06 22:04
@cauerego afaik, Rootles launcher uses only a an open app counter. My prediction system is also based on usage (duh), but I only regard only app opens which happened in the last month. I also give more recent app starts a higher weight in the calculation, I use this curve for my interpolation: https://www.wolframalpha.com/input/?i=2.5*x%5E1.5+from+0+to+1

**Comment by VincentJoshuaET** [comment] 2018-10-07 10:50
Correct all other Pixel-like launchers (except for the modded Pixel Launcher by paphonb, which isn't built from source and is just a port) use a simple app suggestions implementation, I read that using the Google implementation causes lag to the launchers.

**Comment by 8bitPit** [comment] 2019-02-24 14:02
@kevinparish suggested:
> It seems most used apps by time of day is too problematic right now. I would be happy with 4 sets of favorites by time of day. You pick a set of pinned apps for morning, afternoon, evening and night. Ive been looking for launcher like this.. can't find one.

**Comment by disacrol** [comment] 2019-02-28 09:53
@8bitPit Doesn't this fit the proposed feature to have favorites tweaked based on conditions? Time of day, location, connected devices, etc... I could swear you were into such feature a while ago.

**Comment by 8bitPit** [comment] 2019-02-28 23:07
@disacrol Oh, you're right, I found it now: https://github.com/8bitPit/Niagara-Issues/issues/165

**Comment by 8bitPit** [comment] 2019-05-03 12:46
Duplicate of #165

**Closed by 8bitPit** 2019-05-03 12:46 UTC
Labels: duplicate, enhancement, problematic
