### ISSUE TITLE
Swipe down for search

### ISSUE THREAD

**Issue by Feckweed405** [8bitPit/Niagara-Issues#862] opened 2019-05-05 17:42 UTC
One finger swip down for Google or (when it comes) sesame search please.

**Comment by 8bitPit** [comment] 2019-05-05 20:08
The swipe down gesture is already reserved for opening the notification shade. However, the swipe up gesture is unused. See: #122

**Comment by 8bitPit** [comment] 2019-05-05 20:16
Duplicate of #122

**Closed by 8bitPit** 2019-05-05 20:16 UTC
Labels: duplicate
